### ISSUE TITLE
Unable to render git icons in prompt

### ISSUE THREAD

**Issue by rjcoelho** [romkatv/powerlevel10k#210] opened 2019-09-10 09:29 UTC
Hi,

This is what I get. Exclamation and question marks should be icons correct ?
~/Repos/dotfiles.rcm master !1 ?1 ❯

I'm using iterm2, and I tried recommended font (installed using the wizard). Same issue with all the nerd fonts I brew cask installed. Same issue in integrated vscode terminal, even after i changed fontFamily.

Any help is welcomed,
Thanks

**Comment by romkatv** [comment] 2019-09-10 10:29
Does this help? https://github.com/romkatv/powerlevel10k/blob/master/README.md#why-do-i-have-a-question-mark-symbol-in-my-prompt-is-my-font-broken

**Comment by romkatv** [comment] 2019-09-11 06:55
Closing as *working as intended*. Unstaged changes and untracked files are indeed designated by the exclamation and question marks respectively. These symbols can be changed by editing `~/.p10k.zsh`. See [FAQ](https://github.com/romkatv/powerlevel10k/blob/master/README.md#why-do-i-have-a-question-mark-symbol-in-my-prompt-is-my-font-broken).

**Closed by romkatv** 2019-09-11 06:55 UTC
