### ISSUE TITLE
POWERLEVEL9K_JAVA_VERSION_PROJECT_ONLY not working on MacOS

### ISSUE THREAD

**Issue by bjorntj** [romkatv/powerlevel10k#1750] opened 2022-02-01 11:45 UTC
I have the following in mye .p10k.zsh file:

typeset -g POWERLEVEL9K_JAVA_VERSION_PROJECT_ONLY=true

and was expecting the prompt to only show the java version when inside a java project but on my MacBook it shows all the time. (it works on my Linux desktop).
(Using the latest Montery version and latest p10k version)

**Comment by romkatv** [comment] 2022-02-01 11:51
What is the output of the following command when java version is shown on macOS?

```zsh
print -rC1 -- $PWD/(../)#(pom.xml|build.gradle.kts|build.sbt|deps.edn|project.clj|build.boot|*.(java|class|jar|gradle|clj|cljc))(#qN)
```

**Comment by bjorntj** [comment] 2022-02-01 11:55
Aaaah... I have old java files in my home directory, it seems like that is messing up... I see it checks for any files above current folder...
Thx for quick response... :)

**Comment by romkatv** [comment] 2022-02-01 11:57
You are welcome. Closing as Working As Intended.

**Closed by romkatv** 2022-02-01 11:57 UTC
