### ISSUE TITLE
Os Icon rendering white when POWERLEVEL9K_OS_ICON_FOREGROUND is not set

### ISSUE THREAD

**Issue by Breigner01** [romkatv/powerlevel10k#2133] opened 2022-12-25 07:51 UTC
So the title is pretty self-explanatory when I set `POWERLEVEL9K_OS_ICON_FOREGROUND` to nothing, the os icon renders white instead of black.
So, I've been using p10k on my personal computers, etc and now that I've set it up on a server, I don't know if I may have something badly set up in my conf or something but as far as I remember, I don't see why there would be any issue there.
I have a custom color for my personal computers, running arch, and wanted to have a nice blue.
But on a server not running arch where it defaults to just the tux logo. When I copy-paste my config and remove the value for `POWERLEVEL9K_OS_ICON_FOREGROUND`, the logo renders white instead of black.
Hope you guys can help me get this logo back to black.

**Comment by romkatv** [comment] 2022-12-25 07:55
If you set `POWERLEVEL9K_OS_ICON_FOREGROUND` to empty value, powerlevel10k will print the icon without specifying any foreground color. It'll be rendered with the same color that you see in the output of `echo TEST`.

**Comment by Breigner01** [comment] 2022-12-25 07:59
I'm not sure I follow because the default is for this value to be empty so how did it render black before and now it's white?
My friend rocking p10k hasn't modified its config file after it's been generated by the set-up wizard and this value is empty and his os icon is black so that's weird then.

**Comment by romkatv** [comment] 2022-12-25 08:01
Please describe what you do, what you observe and what you expect.

**Comment by Breigner01** [comment] 2022-12-25 08:08
## Before

setting the value of `POWERLEVEL9K_OS_ICON_FOREGROUND` to empty gave a black os icon

## Now

setting the value of `POWERLEVEL9K_OS_ICON_FOREGROUND` to empty gives a white os icon

## Note

I've seen that on the 4 themes that implement the os icon in the repo (in the `config` folder), 2 of them have a value for `POWERLEVEL9K_OS_ICON_FOREGROUND` and the other 2 don't.

So now I'm mostly asking myself, have there been any changes as to which color it defaults to compared to before?

**Comment by romkatv** [comment] 2022-12-25 08:22
There have been no changes related to `POWERLEVEL9K_OS_ICON_FOREGROUND`. If you set this parameter to empty, you'll get no foreground. If you don't set this parameter at all, you'll get foreground 7. If you want to change the color, see https://github.com/romkatv/powerlevel10k#how-do-i-change-prompt-colors.

**Comment by Breigner01** [comment] 2022-12-25 08:23
Ok well that's weird then I don't understand why it was working before with an empty value and now it doesn't anymore

**Comment by romkatv** [comment] 2022-12-25 08:25
Setting `POWERLEVEL9K_OS_ICON_FOREGROUND` to an empty value has always been causing the icon to be rendered with no foreground color. How that looks in your terminal depends on the terminal settings. See the link I posted above.

Closing as working as intended.

**Closed by romkatv** 2022-12-25 08:25 UTC
