### ISSUE TITLE
Git segment disappears after running git commands

### ISSUE THREAD

**Issue by tharakadesilva** [romkatv/powerlevel10k#2037] opened 2022-09-27 14:58 UTC
Operating system: CentOS 7

Here is an example of the issue in a new repository:

<img width="494" alt="image" src="https://user-images.githubusercontent.com/16497653/192560257-e2f555b3-0c83-4ac8-b32e-3c91b880690f.png">

For repositories that already exist, simply running a git status after the clone will break it.

**Comment by romkatv** [comment] 2022-09-27 15:00
Is it reproducible 100% of the time?

What are the commands that reproduce it?

**Comment by tharakadesilva** [comment] 2022-09-27 15:10
Any repo I clone, I run `git status` it breaks.

Here are the logs from the attached screenshot:

```
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/gitstatus.cc:186] argv[0]: "/home/tdesilva/.cache/gitstatus/gitstatusd-linux-x86_64"
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/gitstatus.cc:186] argv[1]: "-G"
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/gitstatus.cc:186] argv[2]: "v1.5.4"
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/gitstatus.cc:186] argv[3]: "-s"
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/gitstatus.cc:186] argv[4]: "-1"
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/gitstatus.cc:186] argv[5]: "-u"
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/gitstatus.cc:186] argv[6]: "-1"
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/gitstatus.cc:186] argv[7]: "-d"
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/gitstatus.cc:186] argv[8]: "-1"
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/gitstatus.cc:186] argv[9]: "-c"
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/gitstatus.cc:186] argv[10]: "-1"
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/gitstatus.cc:186] argv[11]: "-m"
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/gitstatus.cc:186] argv[12]: "-1"
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/gitstatus.cc:186] argv[13]: "-v"
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/gitstatus.cc:186] argv[14]: "DEBUG"
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/gitstatus.cc:186] argv[15]: "-t"
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/gitstatus.cc:186] argv[16]: "16"
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/thread_pool.cc:81] Spawning 16 thread(s)
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/gitstatus.cc:201] Processing request: "}hello" for ""
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/response.cc:69] Replying without git status
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/timer.cc:67] Timing for: request: 0.031ms cpu, 0.029166ms wall
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/gitstatus.cc:204] Successfully processed request: "}hello" for ""
+_gitstatus_daemon_p9k_:93> sleep 5
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/gitstatus.cc:201] Processing request: "1664291045.5142357349 _p9k_vcs_resume 0" for "/home/tdesilva" [no-diff]
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/response.cc:69] Replying without git status
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/timer.cc:67] Timing for: request: 0.132ms cpu, 0.124761ms wall
[2022-09-27 17:04:05 00007efe5ab1fc38 INFO src/gitstatus.cc:204] Successfully processed request: "1664291045.5142357349 _p9k_vcs_resume 0" for "/home/tdesilva" [no-diff]
[2022-09-27 17:04:07 00007efe5ab1fc38 INFO src/gitstatus.cc:201] Processing request: "1664291047.9676311016 _p9k_vcs_resume 0" for "/home/tdesilva/test" [no-diff]
[2022-09-27 17:04:07 00007efe5ab1fc38 INFO src/repo_cache.cc:132] Initializing new repository: "/home/tdesilva/test/.git/"
[2022-09-27 17:04:07 00007efe5ab1fc38 INFO src/response.cc:69] Replying with git status
[2022-09-27 17:04:07 00007efe5ab1fc38 INFO src/timer.cc:67] Timing for: request: 1.302ms cpu, 1.04486ms wall
[2022-09-27 17:04:07 00007efe5ab1fc38 INFO src/gitstatus.cc:204] Successfully processed request: "1664291047.9676311016 _p9k_vcs_resume 0" for "/home/tdesilva/test" [no-diff]
[2022-09-27 17:04:07 00007efe5ab1fc38 INFO src/gitstatus.cc:201] Processing request: "1664291047.9697146416 _p9k_vcs_resume 1" for "/home/tdesilva/test"
[2022-09-27 17:04:07 00007efe5ab1fc38 ERROR src/repo.cc:155] !git_repository_index(&git_index_, repo_): unsupported mandatory extension: 'link'
[2022-09-27 17:04:07 00007efe5ab1fc38 INFO src/response.cc:69] Replying without git status
[2022-09-27 17:04:07 00007efe5ab1fc38 INFO src/timer.cc:67] Timing for: request: 3.811ms cpu, 3.7563ms wall
[2022-09-27 17:04:07 00007efe5ab1fc38 ERROR src/gitstatus.cc:206] Error processing request: "1664291047.9697146416 _p9k_vcs_resume 1" for "/home/tdesilva/test"
[2022-09-27 17:04:08 00007efe5a911b20 INFO src/check_dir_mtime.cc:149] All mtime checks have passes. Enabling untracked cache: "/home/tdesilva/test/.git/"
+_gitstatus_daemon_p9k_:93> [[ -e /tmp/gitstatus.POWERLEVEL9K.1515363.20851.1664291045.2.lock ]]
[2022-09-27 17:04:38 00007efe5ab1fc38 INFO src/gitstatus.cc:201] Processing request: "1664291078.6425604820 _p9k_vcs_resume 0" for "/home/tdesilva/test" [no-diff]
[2022-09-27 17:04:38 00007efe5ab1fc38 INFO src/response.cc:69] Replying with git status
[2022-09-27 17:04:38 00007efe5ab1fc38 INFO src/timer.cc:67] Timing for: request: 0.227ms cpu, 0.221983ms wall
[2022-09-27 17:04:38 00007efe5ab1fc38 INFO src/gitstatus.cc:204] Successfully processed request: "1664291078.6425604820 _p9k_vcs_resume 0" for "/home/tdesilva/test" [no-diff]
[2022-09-27 17:04:38 00007efe5ab1fc38 INFO src/gitstatus.cc:201] Processing request: "1664291078.6436197758 _p9k_vcs_resume 1" for "/home/tdesilva/test"
[2022-09-27 17:04:38 00007efe5ab1fc38 ERROR src/repo.cc:155] !git_repository_index(&git_index_, repo_): unsupported mandatory extension: 'link'
[2022-09-27 17:04:38 00007efe5ab1fc38 INFO src/response.cc:69] Replying without git status
[2022-09-27 17:04:38 00007efe5ab1fc38 INFO src/timer.cc:67] Timing for: request: 0.367ms cpu, 0.305241ms wall
[2022-09-27 17:04:38 00007efe5ab1fc38 ERROR src/gitstatus.cc:206] Error processing request: "1664291078.6436197758 _p9k_vcs_resume 1" for "/home/tdesilva/test"
[2022-09-27 17:04:46 00007efe5ab1fc38 INFO src/gitstatus.cc:201] Processing request: "1664291086.8880715370 _p9k_vcs_resume 0" for "/home/tdesilva/test" [no-diff]
[2022-09-27 17:04:46 00007efe5ab1fc38 INFO src/response.cc:69] Replying with git status
[2022-09-27 17:04:46 00007efe5ab1fc38 INFO src/timer.cc:67] Timing for: request: 0.295ms cpu, 0.277719ms wall
[2022-09-27 17:04:46 00007efe5ab1fc38 INFO src/gitstatus.cc:204] Successfully processed request: "1664291086.8880715370 _p9k_vcs_resume 0" for "/home/tdesilva/test" [no-diff]
[2022-09-27 17:04:46 00007efe5ab1fc38 INFO src/gitstatus.cc:201] Processing request: "1664291086.8891899586 _p9k_vcs_resume 1" for "/home/tdesilva/test"
[2022-09-27 17:04:46 00007efe5ab1fc38 ERROR src/repo.cc:155] !git_repository_index(&git_index_, repo_): unsupported mandatory extension: 'link'
[2022-09-27 17:04:46 00007efe5ab1fc38 INFO src/response.cc:69] Replying without git status
[2022-09-27 17:04:46 00007efe5ab1fc38 INFO src/timer.cc:67] Timing for: request: 0.284ms cpu, 0.24193ms wall
[2022-09-27 17:04:46 00007efe5ab1fc38 ERROR src/gitstatus.cc:206] Error processing request: "1664291086.8891899586 _p9k_vcs_resume 1" for "/home/tdesilva/test"
[2022-09-27 17:04:48 00007efe5ab1fc38 INFO src/gitstatus.cc:201] Processing request: "1664291088.3136749268 _p9k_vcs_resume 0" for "/home/tdesilva/test" [no-diff]
[2022-09-27 17:04:48 00007efe5ab1fc38 INFO src/response.cc:69] Replying with git status
[2022-09-27 17:04:48 00007efe5ab1fc38 INFO src/timer.cc:67] Timing for: request: 0.312ms cpu, 0.318321ms wall
[2022-09-27 17:04:48 00007efe5ab1fc38 INFO src/gitstatus.cc:204] Successfully processed request: "1664291088.3136749268 _p9k_vcs_resume 0" for "/home/tdesilva/test" [no-diff]
[2022-09-27 17:04:48 00007efe5ab1fc38 INFO src/gitstatus.cc:201] Processing request: "1664291088.3149344921 _p9k_vcs_resume 1" for "/home/tdesilva/test"
[2022-09-27 17:04:48 00007efe5ab1fc38 ERROR src/repo.cc:155] !git_repository_index(&git_index_, repo_): unsupported mandatory extension: 'link'
[2022-09-27 17:04:48 00007efe5ab1fc38 INFO src/response.cc:69] Replying without git status
[2022-09-27 17:04:48 00007efe5ab1fc38 INFO src/timer.cc:67] Timing for: request: 0.229ms cpu, 0.195661ms wall
[2022-09-27 17:04:48 00007efe5ab1fc38 ERROR src/gitstatus.cc:206] Error processing request: "1664291088.3149344921 _p9k_vcs_resume 1" for "/home/tdesilva/test"
```

**Comment by romkatv** [comment] 2022-09-27 15:16
```text
[2022-09-27 17:04:48 00007efe5ab1fc38 ERROR src/repo.cc:155] !git_repository_index(&git_index_, repo_): unsupported mandatory extension: 'link'
```

This is the culprit ☝️ 

"link" extension is used by [split index](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresplitIndex). [libgit2](https://libgit2.org/) cannot handle repos with split index enabled, and since gitstatusd relies on libgit2 for some of its features it cannot handle split index either.

There are a few things you can do:

1. Add support for split index to libgit2. Once done, I can add support to gitstatusd.
2. Disable split index in your git config. This may slow down operations that write to the index. On a modern machine it becomes noticeable when working on repositories with over 1M files.
3. Disable gitstatusd with `POWERLEVEL9K_DISABLE_GITSTATUS=true`. This will make your prompt much slower and likely unusable when in a large git repo.

**Comment by tharakadesilva** [comment] 2022-09-27 15:22
Thank you for the help, @romkatv! I'll chose option 2 for now and see how bad the perf impact is.

I am curious though, is libgit2 only used for Linux? I have a similar setup in MacOS and it's working as expected.

Do you want me to keep this issue open or should I close it?

**Comment by romkatv** [comment] 2022-09-27 15:29
libgit2 is used on all operating systems. If gitstatusd works for you on macOS, you aren't using split index there.

You won't notice performance impact in repos that aren't humongous. Repos like Linux kernel, for example, are way too small to see any difference.

Closing because I don't intend to do anything here.

**Closed** 2022-09-27 15:29 UTC
