### ISSUE TITLE
Responsive directory truncation doesn't work in the right prompt

### ISSUE THREAD

**Issue by MarkLodato** [romkatv/powerlevel10k#250] opened 2019-10-08 03:52 UTC
The [Responsive directory truncation](https://asciinema.org/a/258376) behavior only works in the left-side prompt. On the right side, the directory always gets truncated fully. Example:

[![https://imgur.com/Iv2i0YP.png](https://imgur.com/Iv2i0YP.png)](https://imgur.com/Iv2i0YP.png)

In this example, `dir` is in the left prompt before the `source` call, and in the right prompt after. You can see that it is truncated incorrectly (or at least to my understanding).

**Comment by romkatv** [comment] 2019-10-08 08:22
> I would like to print my path untruncated if there is room, and only truncate the path as needed. Moreover, I'd love `truncate_to_unique` to only truncate the minimum necessary pieces for the path to fit.

You need to set `POWERLEVEL9K_DIR_MAX_LENGTH=''`. If `dir` segment is on the last line (the same line where you are typing commands), you also need to set `POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=0` and `POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=0`. I don't recommend this particular combination. In most circumstances it's better to truncate the current directory than to have no room for commands.

> Either way, I suggest updating these comments to make the behavior more clear.

I've updated comments above `POWERLEVEL9K_DIR_MAX_LENGTH` to clarify that it's not the only constraint that may cause directory truncation.

> The Responsive directory truncation behavior only works in the left-side prompt.

Indeed, and only for the first `dir` segment on the line. That is, with `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir dir)`, the second `dir` will always be maximally truncated.

Responsive directory truncation has a complex implementation. It kicks in only for the first `dir` of left prompt to make the implementation simpler. Since almost everyone uses only one `dir` segment and puts it on the left, this limitation rarely matters.

It's definitely possible to support responsive directory truncation on the right but it's very low on my priority list. If this matters to you, I'm open to PRs, provided the code doesn't get massively more complex.

**Comment by MarkLodato** [comment] 2019-10-08 13:23
Thanks for the response! Do you have any tips on how this might be implemented? The implementation is pretty complicated so I'm having a bit of a hard time getting started.

**Comment by romkatv** [comment] 2019-10-08 13:31
> Do you have any tips on how this might be implemented?

No, sorry. If I knew an easy way, I would've implemented it. I cannot recommend in good faith that you attempt this. It's really difficult and the payoff is small. If 99.99% of all shell users put their directory on the left, it might just be possible that you could also put it on the left and not lose too much productivity because of it. My recommendation would be to do that just and move on.

Having said that, I repeat that I'm open to PRs should you decide to remove this restriction from p10k.

**Comment by romkatv** [comment] 2019-10-09 10:38
I'm going to close this issue as Won't Fix. I acknowledge that the issue is valid. Responsive directory truncation indeed doesn't work in the right prompt, and it would be better if it did. The Won't Fix resolution is based on my personal cost/benefit analysis: I estimate that the amount of work doesn't justify the potential benefits. Weighting my costs against benefits to others is tricky. Users who value this feature highly are welcome to contribute PRs (although, as I mentioned above, my recommendation is to put `dir` on the left).

**Closed by romkatv** 2019-10-09 10:38 UTC
