### ISSUE TITLE
lsd alias not working

### ISSUE THREAD

**Issue by Zana-hex** [romkatv/powerlevel10k#1673] opened 2021-12-17 02:40 UTC
alias ls='lsd' or alias ls='/usr/bin/lsd' not working in .zshrc file, I used alias cat='/usr/bin/bat' and it works perfectly, but when I use ls, there is no lsd.

Can some one help me?

**Comment by guanhuali1018** [comment] 2021-12-17 02:50
you can try input lsd in terminal firstly, I guess maybe there is a problem with lsd itself.

**Comment by romkatv** [comment] 2021-12-17 06:39
@Zana-hex Does the problem persist if you disable powerlevel10k?

**Comment by Zana-hex** [comment] 2021-12-17 18:17
> you can try input lsd in terminal first, I guess maybe there is a problem with lsd itself.

Nope, lsd works fine by itself.

**Comment by romkatv** [comment] 2021-12-17 18:18
OK, let's try to figure out what's going on.

Please describe what you do, what you expect and what you observe.

**Comment by Zana-hex** [comment] 2021-12-17 18:19
> @Zana-hex Does the problem persist if you disable powerlevel10k?

Yes, when I use alias ls='/usr/bin/lsd' in terminal, works fine, but is temporarily.

**Comment by romkatv** [comment] 2021-12-17 18:20
> > @Zana-hex Does the problem persist if you disable powerlevel10k?
> 
> Yes, when I use alias ls='/usr/bin/lsd' in terminal, works fine, but is temporarily.

That's not the question I'm asking. Try disabling or ([uninstalling](https://github.com/romkatv/powerlevel10k#how-do-i-uninstall-powerlevel10k) if you don't know how to disable without uninstalling) and check whether you are still having the same issue.

**Comment by Zana-hex** [comment] 2021-12-17 18:34
> OK, let's try to figure out what's going on.
> 
> Please describe what you do, what you expect and what you observe.

I use type ls and it returns ls "is an alias for ls --color=auto", and I have the alias defined in .zshrc, and yes, I'm disabled the powerlevel10k.

**Comment by romkatv** [comment] 2021-12-17 18:42
If your alias doesn't work when you disable powerlevel10k, it means the issue is not caused by powerlevel10k, so I'm closing it.

Your alias gets overridden by something in your `~/.zshrc`. You can likely fix the problem by moving the alias definition to the very bottom of `~/.zshrc`.

**Closed by romkatv** 2021-12-17 18:42 UTC

**Comment by sidcodeme** [comment] 2024-06-09 21:56
@romkatv Thank you!! I fixed this!!!
