### ISSUE TITLE
Some machines generate a trailing '/' from prompt_dir, most don't - same config

### ISSUE THREAD

**Issue by joerohde** [romkatv/powerlevel10k#2426] opened 2023-09-08 18:28 UTC
I've got a dotfiles thing going and synced up configs.

2 Macs, both with ZSH_VERSION=5.9.

I configured an END for the dir to be '/' and it all worked fine.  But then when I went to this other Mac, I realized I had doubel '//'.

Is there any known issue where the right-most side of the prompt_dir inconsistently append a '/'?

Just no repro this if I sound crazy - because.... it seems crazy.

![image](https://github.com/romkatv/powerlevel10k/assets/25186855/fe328a89-bac2-4384-b93f-e5b515aaa659)

**Comment by romkatv** [comment] 2023-09-08 18:31
I've never seen anything like this and have no idea why this might happen. Since there is no way for me to reproduce this, I'm going to close this issue. If you find out what's going on, please post an update.

**Closed by romkatv** 2023-09-08 18:31 UTC
