### ISSUE TITLE
Issue "_p9k_worker_stop:zle:4: No handler installed for fd 14"

### ISSUE THREAD

**Issue by yilas** [romkatv/powerlevel10k#1999] opened 2022-08-30 09:21 UTC
Hi,

Sometimes, I get that behavior : when I start a terminal, the shell seems stuck. Here is the only displayed line : 

```bash
[zplug] no packages to install
```

I have no choice but to Control+C and `source ~/.zshrc` to get a shell.
I've got no error until I type a command. For instance :

```bash
$ cd plop
_p9k_worker_stop:zle:4: No handler installed for fd 14                                                                                                                                                            
_p9k_worker_stop:5: failed to close file descriptor 14: bad file descriptor
```
Have you already met that issue ? How can I troubleshoot ?

I found the following command if it can help for the debugging : 

```bash
$ zsh --sourcetrace -lic 'command cat ${ZDOTDIR:-~}/.zshrc'
+/etc/zsh/zshenv:1> <sourcetrace>
+/etc/zsh/zprofile:1> <sourcetrace>
+/etc/zsh/zshrc:1> <sourcetrace>
+/home/yann/.zshrc:1> <sourcetrace>
+/home/yann/.cache/p10k-instant-prompt-yann.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/oh-my-zsh.sh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/tools/check_for_upgrade.sh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/cache/.zsh-update:1> <sourcetrace>
+/home/yann/.oh-my-zsh/lib/compfix.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/lib/bzr.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/lib/clipboard.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/lib/cli.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/lib/compfix.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/lib/completion.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/lib/correction.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/lib/diagnostics.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/lib/directories.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/lib/functions.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/lib/git.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/lib/grep.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/cache/grep-alias:1> <sourcetrace>
+/home/yann/.oh-my-zsh/lib/history.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/lib/key-bindings.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/lib/misc.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/lib/nvm.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/lib/prompt_info_functions.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/lib/spectrum.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/lib/termsupport.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/lib/theme-and-appearance.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/lib/vcs_info.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/custom/example.zsh:1> <sourcetrace>
+/home/yann/.oh-my-zsh/themes/robbyrussell.zsh-theme:1> <sourcetrace>
+/home/yann/.asdf/asdf.sh:1> <sourcetrace>
+/home/yann/.asdf/lib/asdf.sh:1> <sourcetrace>
+/usr/share/zplug/init.zsh:1> <sourcetrace>
+/usr/share/zplug/base/init.zsh:1> <sourcetrace>
+/usr/share/zplug/autoload/init.zsh:1> <sourcetrace>
+/home/yann/.zplug/packages.zsh:1> <sourcetrace>
[zplug] no packages to install
+/home/yann/.zplug/cache/plugin.zsh:1> <sourcetrace>
+/home/yann/.zplug/repos/robbyrussell/oh-my-zsh/lib/git.zsh:1> <sourcetrace>
+/home/yann/.zplug/cache/lazy_plugin.zsh:1> <sourcetrace>
+/home/yann/.zplug/cache/theme.zsh:1> <sourcetrace>
```

**Comment by romkatv** [comment] 2022-08-30 10:30
This issues is caused by a bug in one of the plugins you are using. More specifically, some plugin is closing the file descriptor that it didn't open. If you disable everything except powerlevel10k, this issue won't happen.

**Comment by yilas** [comment] 2022-08-30 11:48
> This issues is caused by a bug in one of the plugins you are using. More specifically, some plugin is closing the file descriptor that it didn't open. If you disable everything except powerlevel10k, this issue won't happen.

Thank you very much for your reply. I will make some tests with plugins.

**Closed** 2022-09-06 09:15 UTC
