### ISSUE TITLE
battery segment does not display on Linux/Ubuntu

### ISSUE THREAD

**Issue by ynavott** [romkatv/powerlevel10k#858] opened 2020-07-01 21:58 UTC
Using latest GNOME terminal on Ubuntu 20.04, the battery segment does not show up when uncommented in  `.p10k.zsh`:
![Screenshot from 2020-07-02 00-51-14](https://user-images.githubusercontent.com/48953594/86294914-27ada480-bbfe-11ea-8cdc-5e57eb31b4ec.png)
This is after I enabled it.

My [.p10k.zsh](https://gist.github.com/ynavott/96ab1af0fb068dfefb8235418453c3b4) and [.zshrc](https://gist.github.com/ynavott/0caeab60bf3159177b60c4f7905f7496).

In fact, none of the segments that are placed by default after the `newline` (such as `public_ip`) show up when uncommented, both when placed before and after the `newline`.

**Comment by romkatv** [comment] 2020-07-02 04:37
> Using latest GNOME terminal on Ubuntu 20.04, the battery segment does not show up when uncommented in `.p10k.zsh`:

Does your device have an internal battery? Is it a laptop? Which model? What is the output of the following command?

```zsh
print -rC1 -- /sys/class/power_supply/(BAT*|battery)/(energy_full|charge_full|charge_counter)(#qN)
```

> In fact, none of the segments that are placed by default after the `newline` (such as `public_ip`) show up when uncommented, both when placed before and after the `newline`.

Please run the following command and post a screenshot when prompt appears.

```zsh
( 
  emulate -L zsh -o err_return
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
  {
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $tmp/powerlevel10k
    curl -fsSLo $tmp/.p10k.zsh https://gist.githubusercontent.com/ynavott/96ab1af0fb068dfefb8235418453c3b4/raw/fe13c8481e742cad3f00b5f9658638ebbf26b69a/.p10k.zsh
    sed -i -E 's/^    # (ip|public_ip|example) /    \1   /' $tmp/.p10k.zsh
    >$tmp/.zshrc <<\END
source $ZDOTDIR/.p10k.zsh
source $ZDOTDIR/powerlevel10k/powerlevel10k.zsh-theme
END
    ZDOTDIR=$tmp zsh
  } always {
    cd /
    command rm -rf -- $tmp
  }
)
```

**Comment by ynavott** [comment] 2020-07-02 06:35
> Does your device have an internal battery? Is it a laptop? Which model?

It's an LG Gram 15" (Z990 model, the newest) laptop so I'm pretty sure it has a battery :)

> What is the output of the following command?
`print -rC1 -- /sys/class/power_supply/(BAT*|battery)/(energy_full|charge_full|charge_counter)(#qN)`

Output copied from shell:
`zsh: unknown file attribute: #`

Probably not the output I should expect.

Output of the 2nd command:
![Screenshot from 2020-07-02 09-31-33](https://user-images.githubusercontent.com/48953594/86324190-db3a8700-bc46-11ea-96cb-b6292354cdfc.png)

Seems to be working, although I'm not sure why the star is there (maybe it's the `example`?).

**Comment by romkatv** [comment] 2020-07-02 06:43
> Output copied from shell:
> `zsh: unknown file attribute: #`

Let's try this:

```zsh
() {
  emulate -L zsh -o extended_glob -o xtrace
  local files=(/sys/class/power_supply/{BAT*,battery}/{energy_full,charge_full,charge_counter}(N))
  (( $#files )) && command ls -ld -- $files
}
```

> Seems to be working

How do you reconcile it with the original report?

> although I'm not sure why the star is there (maybe it's the `example`?).

Yes, it is. You've mentioned in the bug description that no segments below `newline` work, so I've asked you to send me a screenshot with those segments uncommented.

**Comment by ynavott** [comment] 2020-07-02 06:53
The output:
![Screenshot from 2020-07-02 09-50-25](https://user-images.githubusercontent.com/48953594/86325881-851b1300-bc49-11ea-968f-898402b8a195.png)
According to the indicator, the command failed.

> How do you reconcile it with the original report?

Excuse me for not being very well-versed in zsh or sh language in general, but I'm pretty sure that this command loaded the p10k theme by sourcing it directly in the `.zshrc` file instead of using `ZSH_THEME=powerlevel10k/powerlevel10k`. I am not sure though, so I'd like your confirmation about this being the fix and the problem stemming from the oh-my-zsh configuration I have.

**Comment by romkatv** [comment] 2020-07-02 07:08
> The output:
> ![Screenshot from 2020-07-02 09-50-25](https://user-images.githubusercontent.com/48953594/86325881-851b1300-bc49-11ea-968f-898402b8a195.png)

Thanks.

Can you tell me where the battery dev files are? They should be somewhere under `/sys` or `/dev`.

> Excuse me for not being very well-versed in zsh or sh language in general, but I'm pretty sure that this command loaded the p10k theme by sourcing it directly in the `.zshrc` file instead of using `ZSH_THEME=powerlevel10k/powerlevel10k`.

Correct. oh-my-zsh does the same thing. Here's another command that loads powerlevel10k via oh-my-zsh.

```zsh
( 
  emulate -L zsh -o err_return
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
  {
    git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh.git $tmp/.oh-my-zsh
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $tmp/.oh-my-zsh/custom/themes/powerlevel10k
    curl -fsSLo $tmp/.p10k.zsh https://gist.githubusercontent.com/ynavott/96ab1af0fb068dfefb8235418453c3b4/raw/fe13c8481e742cad3f00b5f9658638ebbf26b69a/.p10k.zsh
    sed -i -E 's/^    # (ip|public_ip|example) /    \1   /' $tmp/.p10k.zsh
    >$tmp/.zshrc <<\END
ZSH=$ZDOTDIR/.oh-my-zsh
DISABLE_AUTO_UPDATE=true
ZSH_THEME=powerlevel10k/powerlevel10k
source $ZSH/oh-my-zsh.sh
source $ZDOTDIR/.p10k.zsh
END
    ZDOTDIR=$tmp zsh
  } always {
    cd /
    command rm -rf -- $tmp
  }
)
```

Does it show any prompt segments on the second line of right prompt?

> so I'd like your confirmation about this being the fix and the problem stemming from the oh-my-zsh configuration I have.

Before suggesting a fix I need to see a problem. You've described steps necessary to reproduce the problem but when I asked you to follow these steps turned out they don't show any problem. I need instructions for how to reproduce before I can do anything. Make sure these instructions actually reproduce the problem for you if you follow them.

**Comment by ynavott** [comment] 2020-07-02 07:29
> Can you tell me where the battery dev files are? They should be somewhere under /sys or /dev.

I think I have discovered the issue here. When running `ls /sys/class/power_supply` the output is `ADP1  CMB0`, so my battery device is named `CMB0` instead of `BAT0`, which probably explains the reason why the commands you gave me couldn't find a device named `BAT0`, and probably explains why no battery was found by the segment.

> Before suggesting a fix I need to see a problem. You've described steps necessary to reproduce the problem but when I asked you to follow these steps turned out they don't show any problem. I need instructions for how to reproduce before I can do anything. Make sure these instructions actually reproduce the problem for you if you follow them.

Well, this is very confusing. when I re-enabled `public_ip` below `newline` now it worked just fine while yesterday it didn't show up when I put it on neither the 2nd line nor the 1st line. I guess there is no issue with this part then, sorry for wasting your time with this (incorrect) sighting by me.

**Comment by romkatv** [comment] 2020-07-02 08:30
> I think I have discovered the issue here. When running `ls /sys/class/power_supply` the output is `ADP1 CMB0`, so my battery device is named `CMB0` instead of `BAT0`, which probably explains the reason why the commands you gave me couldn't find a device named `BAT0`, and probably explains why no battery was found by the segment.

What's the output of this command?

```zsh
() {
  emulate -L zsh -o extended_glob -o xtrace
  local files=(/sys/class/power_supply/{CMB*,BAT*,battery}/{energy_full,charge_full,charge_counter}(N))
  (( $#files )) && command ls -ld -- $files
}
```

> Well, this is very confusing. when I re-enabled `public_ip` below `newline` now it worked just fine while yesterday it didn't show up when I put it on neither the 2nd line nor the 1st line. I guess there is no issue with this part then, sorry for wasting your time with this (incorrect) sighting by me.

Maybe there was a disruption with Internet connection. However, since you couldn't see *any* segments, including `example`, this means you haven't saved the config, or haven't restarted zsh, or something along the lines.

**Comment by ynavott** [comment] 2020-07-02 08:34
> What's the output of this command?

Copied from shell:
```+(anon):2> local files=( /sys/class/power_supply/CMB0/energy_full )
+(anon):3> ((  1  ))
+(anon):3> ls -ld -- /sys/class/power_supply/CMB0/energy_full
-r--r--r-- 1 root root 4096 Jul  2 03:00 /sys/class/power_supply/CMB0/energy_full
```
Prompt symbol also showed green this time instead of red. seems like it does recognize the battery now when looking for `CMB*`.

**Comment by romkatv** [comment] 2020-07-02 08:40
> Copied from shell

Thanks! Copying from shell is the way to go when I ask for command output. If I need a screenshot I'll ask for it explicitly.

Please update powerlevel10k, restart zsh and let me know if battery shows up in prompt.

**Comment by ynavott** [comment] 2020-07-02 08:44
> Please update powerlevel10k, restart zsh and let me know if battery shows up in prompt.

Shows up perfectly!
![Screenshot from 2020-07-02 11-43-13](https://user-images.githubusercontent.com/48953594/86337032-3ecdb000-bc59-11ea-8f83-c7c5ef292959.png)

Thank you so much for the quick response and for working so hard on making this theme, it's absolutely amazing.

Can probably close this now.

**Comment by romkatv** [comment] 2020-07-02 08:45
Thanks for the confirmation. Closing.

**Closed by romkatv** 2020-07-02 08:45 UTC
