### ISSUE TITLE
Even after successfully built gitstatusd, "Powerlevel10k is unable to use gitstatus. Git prompt will be slow."

### ISSUE THREAD

**Issue by usernein** [romkatv/powerlevel10k#589] opened 2020-03-27 03:19 UTC
Hello, i'm using powerlevel10k at Termux using Oh-My-Zsh.
![](https://i.imgur.com/IUHKAe4.jpg)

I read the docs and i successfully built a 'gitstatusd-android-armv7l' file. It works, but somehow powerlevel10k cannot find it.
![](https://i.imgur.com/r7q40Nw.jpg)

![](https://i.imgur.com/2kF9hhI.jpg)
It's already on `$ZSH/custom/themes/powerlevel10k/gitstatus/usrbin`.
I also tried to move to gitstatus/bin, tried to rename the file (to use 'linux', 'Linux', 'Android') and even tried to move to $PATH but none worked.
To test each try i'm not running 'source' command, i'm closing then opening the terminal.

![](https://i.imgur.com/bGgyuF7.jpg)
The file is executable, i already tried everything i could think and i don't know what to do to make it work :(

**Comment by romkatv** [comment] 2020-03-27 05:31
Thanks for the report! The issue is caused by a stupidly embarrassing typo in powerlevel10k. Should be fixed now. Please [update powerlevel10k](https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-update-powerlevel10k) and try again.

By the way, soon (in a day or two) gitstatus will work on android-armv7l out of the box. You won't have to compile the binary anymore.

**Comment by usernein** [comment] 2020-03-27 10:44
Ahh, thank you very much!

**Closed** 2020-03-27 10:52 UTC

**Comment by romkatv** [comment] 2020-03-29 16:51
> By the way, soon (in a day or two) gitstatus will work on android-armv7l out of the box. You won't have to compile the binary anymore.

This is done. Once you update powerelvel10k, you can remove your custom-built binary. Powerlevel10k now works on armv7l out of the box.
