### ISSUE TITLE
Slow zsh boot with powerlevel10k

### ISSUE THREAD

**Issue by marselmustafin** [romkatv/powerlevel10k#103] opened 2019-07-04 10:43 UTC
Tried to set powerlevel10k instead of powerline to my zsh shell, since powerline took most of shell boostrap time, but I found that powerlevel10k takes even more time. Is there some opportunity to make powerlevel10k bootstrap faster than powerline does? 

Bootstrap log with powerline:
<img width="915" alt="Снимок экрана 2019-07-04 в 13 05 26" src="https://user-images.githubusercontent.com/19539397/60660862-5bc27e00-9e61-11e9-95be-098f051020df.png">

Bootstrap log with powerlevel10k:
![image](https://user-images.githubusercontent.com/19539397/60660981-988e7500-9e61-11e9-9ee3-769ac5f12593.png)

**Comment by romkatv** [comment] 2019-07-04 10:59
How can I read the profiles? How long does it say powerline takes vs powerlevel10k?

**Comment by romkatv** [comment] 2019-07-04 13:35
> How can I read the profiles? How long does it say powerline takes vs powerlevel10k?

Does the profile say that powerline loads in 80 ms and powerlevel10k loads in 160 ms? If so, I'm inclined to close this issue as working as intended. While having shorter load time is better, 160 ms is within the expected range for Powerlevel10k. I except a typical user to start under a dozen interactive ZSH sessions per day, so shaving off 80 ms per session would have little impact.

I added https://github.com/romkatv/powerlevel10k#is-powerlevel10k-fast-to-load to set the right expectations on load latency.

**Closed by romkatv** 2019-07-04 13:35 UTC

**Comment by romkatv** [comment] 2019-10-02 14:45
FYI: The latest commits have made Powerlevel10k 2.5-3 times faster to load. If you zcompile sources and configs, it's over 3 times faster. See https://github.com/romkatv/powerlevel10k/issues/234#issuecomment-537508560 and below.
