### ISSUE TITLE
High CPU usage when loading with Zplugin 

### ISSUE THREAD

**Issue by psprint** [romkatv/powerlevel10k#225] opened 2019-09-20 01:10 UTC
I was experiencing this first on OS X and I was thinking that it's related to that OS. But now I'm on Linux and having the same issue: after loading the prompt with Zplugin the CPU usage goes 100%. It's unrelated to Zplugin's Turbo mode.

Before investigating this, as it seems that it'll be hard, I thought that I'll ask:
  - did any user report such issue?
  - did you encounter such issue during development?

One thing that will cause such issue is an zle -F handler that doesn't withdraw the file descriptor with `zle -F $1`:

```zsh
callback() { IFS=$'\n'; read -u "$1" line }
exec {__FD}< <( echo test )
zle -F $__FD callback
```

The above code does trigger the 100% CPU usage. I know that you're using the feature (to communicate with gitstatus?) and I suspect that you're opening the file descriptor once and not closing/withdrawing it (with zle -F $fd). I wonder how do you manage to not trigger the issue? (in general, as sourcing the prompt manually doesn't cause any problems).

**Comment by romkatv** [comment] 2019-09-20 09:39
How can I reproduce this?

Here's what I've tried:

```zsh
docker run -e LANG=C.UTF-8 -e TERM -it --rm ubuntu bash -uexc '
  apt update && apt install -y curl git zsh
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"
  echo "zplugin light romkatv/powerlevel10k" >>~/.zshrc
  exec zsh'
```

It works fine.

> did any user report such issue?

No.

> did you encounter such issue during development?

No. I don't use zplugin though.

> I wonder how do you manage to not trigger the issue?

The code is here: https://github.com/romkatv/gitstatus/blob/master/gitstatus.plugin.zsh.

**Comment by romkatv** [comment] 2019-09-23 09:28
Closing due to insufficient information. If you can find a way to reproduce this and something suggests that powerlevel10k is at fault, please reopen.

**Closed by romkatv** 2019-09-23 09:28 UTC

**Comment by romkatv** [comment] 2019-09-27 12:10
Might be related: https://www.zsh.org/mla/workers//2019/msg00820.html.

**Comment by psprint** [comment] 2019-10-10 03:32
I've switched from Mageia to Gentoo and now the problem doesn't occur. This is weird. I confirm that it also doesn't occur on the docker image.

**Comment by psprint** [comment] 2020-01-30 19:01
I've noticed that you do:

```zsh
    sysopen -r -o cloexec -u _p9k__worker_resp_fd <(
…
```
instead of 
```
exec {_p9k__worker_resp_fd}< <(
…
```

Can I ask why?

**Comment by romkatv** [comment] 2020-01-30 19:03
For `O_CLOEXEC` on the descriptor.

**Comment by psprint** [comment] 2020-01-30 19:14
I guess that you've come up with it with the gitstatus daemon, to close the
descriptor when exec zsh will be done?

**Comment by romkatv** [comment] 2020-01-30 19:20
Here it's just for hygiene. In 99% of cases where you open a file descriptor in a library (or "plugin" in zsh ecosystem parlance), you should slap `O_CLOEXEC` on it. Everywhere in my code where it's just `exec`, it's simply out of laziness/sloppiness. It really should be `sysopen`.

If you are looking for a good way to spawn a daemon in Zsh, gitstatus isn't the best choice. In powerlevel10k it is done much better. I need to switch to the same pattern in gitstatus.
