### ISSUE TITLE
Powerlevel10k changes exit behavior in vim/vifm shell

### ISSUE THREAD

**Issue by KodyVB** [romkatv/powerlevel10k#717] opened 2020-05-14 22:04 UTC
I just did a fresh install of Arch on my computer and wanted to get away from OhMyZsh since it had so many things I just never use, so I made a new zshrc. I downloaded powerlevel10k via pacman and went through the usual procedures, resulting in the following zshrc and .config files in [this gitlab link](https://gitlab.com/KodyVB/zshstuff/-/tree/master) (ignore commands.txt as that's just the programs I installed, and was part of my initial Reddit question linked below). The problem comes when I use vim or vifm, and use the `:shell` command.

Normally, when you're in vim or vifm, you can use `:shell` to go to the normal terminal screen, do your stuff, then use `exit` to go back to vim or vifm. But with p10k installed, it outputs:
```
[me ~ ] exit
zsh: suspended (tty output)   vim
[me ~ ] exit
zsh: You have suspended jobs.
[me ~ ] exit
<terminal closes>
```
[This link](https://www.reddit.com/r/archlinux/comments/gju5y6/my_exit_command_is_behaving_weirdly/) goes further into details about my problem, when I asked about it on Reddit.

This problem only happens when I use Powerlevel10k, and after I found that out I tried doing the direct install method (as opposed to the Arch install method) and had the same problems.

I use zsh 5.8, my kernel is 5.6.12-arch1-1, and this problem persisted with all four terminals I tested, being: Alacritty, ST, Konsole, and Gnome-terminal.

**Comment by romkatv** [comment] 2020-05-15 05:01
Thanks for the report.

Looks like a bug in zsh. I've reported it upstream: https://www.zsh.org/mla/workers//2020/msg00652.html.

I've pushed a workaround to powerlevel10k. Please update (from master branch), restart zsh and try again.

**Comment by romkatv** [comment] 2020-05-15 10:59
Closing as the OP has confirmed the workaround is working: https://www.reddit.com/r/archlinux/comments/gju5y6/my_exit_command_is_behaving_weirdly/fqoq1r2/.

**Closed by romkatv** 2020-05-15 10:59 UTC
