### ISSUE TITLE
Transient prompt removes two preceding lines when going from insert mode to normal mode with zsh-vi-mode inside tmux

### ISSUE THREAD

**Issue by itsfarseen** [romkatv/powerlevel10k#1618] opened 2021-10-30 05:54 UTC
Here's a recording of the bug.
https://asciinema.org/a/gxwaBQ4dmYTMnJ2gNgyGH0Q0L

Steps to reproduce:
* Install Oh My Zsh
* Install https://github.com/jeffreytse/zsh-vi-mode
* Install powerlevel10k
* Enable transient prompt.
* Open zsh inside tmux
* Go to insert mode and back to normal mode.

Minimal repro: https://github.com/romkatv/powerlevel10k/issues/1618#issuecomment-955654497

**Comment by romkatv** [comment] 2021-10-30 21:47
I've never used heard of https://github.com/jeffreytse/zsh-vi-mode and don't know what it does. A cursory look suggests that it sometimes invokes `zle reset-prompt`. When using powerlevel10k, powerlevel10k manages prompt. Using other plugins that attempt to control prompt can cause issue. If this answer doesn't help, please open a bug against https://github.com/jeffreytse/zsh-vi-mode.

**Comment by itsfarseen** [comment] 2021-10-31 04:56
Could you roughly describe when does powerlevel10k try to remove previous lines?  
Is it mistaking that `zle-reset-prompt` to be the end of a command execution and trying to reposition the prompt line?

**Comment by romkatv** [comment] 2021-10-31 07:36
> Could you roughly describe when does powerlevel10k try to remove previous lines?

Powerlevel10k doesn't remove previous lines. The removal of lines that you observe is clearly a bug.

> Is it mistaking that `zle-reset-prompt` to be the end of a command execution and trying to reposition the prompt line?

No.

My comment about `zle reset-prompt` meant to point to a potential problem. zsh-vi-mode doesn't control prompt, so it shouldn't invoke `zle reset-prompt`. I now also see that zsh-vi-mode can prevent `reset-prompt` from being called. You need to bring up this issue with https://github.com/jeffreytse/zsh-vi-mode.

By the way, I wasn't able to reproduce this issue based on the provided description. Here's what I tried:

```zsh
docker run -e TERM -e COLORTERM -e LC_ALL=C.UTF-8 -w /root -it --rm alpine sh -uexc '
  apk add curl git zsh
  curl -fsSLO https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
  sh ./install.sh --unattended --skip-chsh </dev/null
  git clone --depth=1 https://github.com/jeffreytse/zsh-vi-mode.git ~/.oh-my-zsh/custom/plugins/zsh-vi-mode
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
  cp ~/.oh-my-zsh/custom/themes/powerlevel10k/config/p10k-lean.zsh ~/.p10k.zsh
  sed -i.bak -E "s|POWERLEVEL9K_TRANSIENT_PROMPT=.*|POWERLEVEL9K_TRANSIENT_PROMPT=always|" ~/.p10k.zsh
  sed -i.bak -E "s|^ZSH_THEME=.*|ZSH_THEME=powerlevel10k/powerlevel10k|" ~/.zshrc
  sed -i.bak -E "s|^plugins=.*|plugins=(zsh-vi-mode)|" ~/.zshrc
  echo "source ~/.p10k.zsh" >>~/.zshrc
  exec zsh'
```

This works fine.

**Comment by itsfarseen** [comment] 2021-10-31 08:00
I just realized it only happens when I run inside tmux.
Here's the repro:
```sh
docker run -e TERM -e COLORTERM -e LC_ALL=C.UTF-8 -w /root -it --rm alpine sh -uexc '
  apk add curl git zsh tmux
  curl -fsSLO https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
  sh ./install.sh --unattended --skip-chsh </dev/null
  git clone --depth=1 https://github.com/jeffreytse/zsh-vi-mode.git ~/.oh-my-zsh/custom/plugins/zsh-vi-mode
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
  cp ~/.oh-my-zsh/custom/themes/powerlevel10k/config/p10k-lean.zsh ~/.p10k.zsh
  sed -i.bak -E "s|POWERLEVEL9K_TRANSIENT_PROMPT=.*|POWERLEVEL9K_TRANSIENT_PROMPT=always|" ~/.p10k.zsh
  sed -i.bak -E "s|^ZSH_THEME=.*|ZSH_THEME=powerlevel10k/powerlevel10k|" ~/.zshrc
  sed -i.bak -E "s|^plugins=.*|plugins=(zsh-vi-mode)|" ~/.zshrc
  echo "source ~/.p10k.zsh" >>~/.zshrc
  echo "set -g default-command \"exec zsh\"" >>~/.tmux.conf
  exec tmux'
```

**Comment by romkatv** [comment] 2021-10-31 08:12
Can you try this?

```zsh
sed -i.bak -E '/zle \.?reset-prompt/d' ~/.oh-my-zsh/custom/plugins/zsh-vi-mode/zsh-vi-mode.zsh
```

It fixes the issue but I cannot tell whether it breaks anything.

**Comment by itsfarseen** [comment] 2021-10-31 09:10
It fixes the issue, and so far it doesn't break anything :) I'll keep using this and update here.

**Comment by romkatv** [comment] 2021-10-31 09:13
Closing because so far there is no indication of a bug in powerlevel10k. Please reopen if you discover any evidence to the contrary.

**Closed by romkatv** 2021-10-31 09:13 UTC
