### ISSUE TITLE
gitstatus display error

### ISSUE THREAD

**Issue by oeyoews** [romkatv/powerlevel10k#1516] opened 2021-08-01 02:38 UTC
![](https://ftp.bmp.ovh/imgs/2021/08/1e5ec8a2f8406f91.png)

- I occasionally encounter this kind of error. 
- I don’t know how this kind of error occurs. I have no idea.

**Comment by romkatv** [comment] 2021-08-01 14:53
Try disabling all plugins except powerlevel10k. Your `~/.zshrc` would look something like this:

```zsh
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
source ~/powerlevel10k/powerlevel10k.zsh-theme
source ~/.p10k.zsh
```

You might need to modify the last two lines.

If this fixes the issue, it means it's caused by something else in your config. Something other than powerlevel10k. You can figure out what it is by disabling plugins one by one.

**Comment by oeyoews** [comment] 2021-08-02 10:36
> Try disabling all plugins except powerlevel10k. Your `~/.zshrc` would look something like this:
> 
> ```shell
> if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
>   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
> fi
> source ~/powerlevel10k/powerlevel10k.zsh-theme
> source ~/.p10k.zsh
> ```
> 
> You might need to modify the last two lines.
> 
> If this fixes the issue, it means it's caused by something else in your config. Something other than powerlevel10k. You can figure out what it is by disabling plugins one by one.

- Sorry, I can’t use this method for testing, because I haven’t figured out under what circumstances this error occurs. It only occurs occasionally;
-  but I will continue to pay attention to this error until I solve it.

**Comment by romkatv** [comment] 2021-08-02 10:43
Closing as not reproducible. Please reopen or open another issue when you figure out how to reproduce it. (FWIW, I'm 99% sure this bug is caused by another plugin that erroneously closes the file descriptor of powerlevel10k.)

**Closed by romkatv** 2021-08-02 10:43 UTC
