### ISSUE TITLE
latest commit broke git status prompt

### ISSUE THREAD

**Issue by lashoun** [romkatv/powerlevel10k#55] opened 2019-04-08 14:33 UTC
Hi, the latest commit you just made broke my git status prompt. Now it does not show anymore, and when I run
```
gitstatus_query POWERLEVEL9K && set | egrep '^VCS_STATUS'
```
in a git repository, I get

```
VCS_STATUS_RESULT=norepo-sync
```

**Comment by romkatv** [comment] 2019-04-08 14:37
Sorry to hear that.

I'll need your help to narrow it down.

1. Do you have this issue in every repo? For example, if you go to the repo of `powerlevel10k`, do you see git prompt?
2. If there is a public repo on which you can reproduce this problem, what is it?
3. If it's only on a private repo of yours, can you tell me what's different about it?
4. What does `uname -a` say?
5. Anything else that can help me debug this?

**Comment by romkatv** [comment] 2019-04-08 14:39
One more thing, perhaps most important.

Please put `GITSTATUS_ENABLE_LOGGING=1` at the top of your `~/.zshrc`, restart zsh and `cd` into your git repo. Then type `cat $GITSTATUS_DAEMON_LOG_POWERLEVEL9K` and post the output here.

**Comment by lashoun** [comment] 2019-04-08 16:06
Damn, so it doesn't happen to you?
1. Yeah every repo, I haven't cloned the `powerlevel10k` repo but it doesn't show in either public or private repos on my local filesystem.
2. All repos are affected.
3. /
4. `Linux *name-of-pc* 4.14.109-1-MANJARO #1 SMP PREEMPT Wed Mar 27 18:51:38 UTC 2019 x86_64 GNU/Linux`
5. I can't think of anything I did... If I have an idea I'll tell you asap. I use `zplug`, if it helps.

Well, while typing this message I think I get what's broken. I have Linux on dual boot on my PC and I usually write data on a mounted disk that is shared between Linux and Windows, and I just noticed that the prompt does appear on a repo that is on the /home partition, but not on the mounted disk...

**Comment by romkatv** [comment] 2019-04-08 16:29
So the repo is on ntfs mounted on Linux? This should be enough for me to reproduce this. Hold on.

**Comment by romkatv** [comment] 2019-04-08 16:32
Reproduced it. Fix incoming.

**Comment by romkatv** [comment] 2019-04-08 16:36
Should be fixed now. Please update.

**Comment by romkatv** [comment] 2019-04-08 17:46
By the way, gitstatus (and git in general) will be much faster if you put your git repositories on a decent filesystem. ntfs is pretty bad for git performance.

**Comment by romkatv** [comment] 2019-04-09 06:12
Closing, as I believe the issue is now fixed. Please reopen if not.

**Closed by romkatv** 2019-04-09 06:12 UTC

**Comment by lashoun** [comment] 2019-04-09 07:52
It was fixed, thanks! I give my hat to you. Thanks for the advice too, did not know ntfs was that bad. I'll see what I can do to change my partition.

**Comment by romkatv** [comment] 2019-04-09 07:58
If you want to have a git repo on a partition that's shared between Linux and Windows, then ntfs is the only viable choice. But working on this repo directly from Linux will be slow. An alternative is to `git clone` (you can clone one directory to another) the shared repo to an ext4 (or whatever) partition on Linux and work on _that_. You can synchronize with the shared repository with the usual git commands -- pull, push, etc. An added bonus of this approach is that you'll solve the problem with line endings in text files.
