### ISSUE TITLE
gitstatus failed to initialize

### ISSUE THREAD

**Issue by atg22896** [romkatv/powerlevel10k#236] opened 2019-09-24 21:51 UTC
```
[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  Run the following command to retry with extra diagnostics:

    GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 POWERLEVEL9K
    ~ ❯ GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 POWERLEVEL9K
[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  The content of /var/folders/f_/8ll4ckc519qbw9h8rw7qfmlxs92fcj/T//gitstatus.69155.xtrace.5ULh2H4Jey (gitstatus_start_impl xtrace):

    +gitstatus_start_impl:11> local os
    +gitstatus_start_impl:11> os=+gitstatus_start_impl:11> uname -s
    +gitstatus_start_impl:11> os=Darwin
    +gitstatus_start_impl:11> [[ -n Darwin ]]
    +gitstatus_start_impl:12> [[ Darwin != Linux ]]
    +gitstatus_start_impl:13> local arch
    +gitstatus_start_impl:13> arch=+gitstatus_start_impl:13> uname -m
    +gitstatus_start_impl:13> arch=x86_64
    +gitstatus_start_impl:13> [[ -n x86_64 ]]
    +gitstatus_start_impl:15> local daemon=/Users/algomez/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64
    +gitstatus_start_impl:16> [[ -x /Users/algomez/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 ]]
    +gitstatus_start_impl:18> lock_file=+gitstatus_start_impl:18> mktemp /var/folders/f_/8ll4ckc519qbw9h8rw7qfmlxs92fcj/T//gitstatus.69155.lock.XXXXXXXXXX
    +gitstatus_start_impl:18> lock_file=/var/folders/f_/8ll4ckc519qbw9h8rw7qfmlxs92fcj/T//gitstatus.69155.lock.2YKeekMCbG
    +gitstatus_start_impl:19> zsystem flock -f lock_fd /var/folders/f_/8ll4ckc519qbw9h8rw7qfmlxs92fcj/T//gitstatus.69155.lock.2YKeekMCbG
    +gitstatus_start_impl:21> req_fifo=+gitstatus_start_impl:21> mktemp -u /var/folders/f_/8ll4ckc519qbw9h8rw7qfmlxs92fcj/T//gitstatus.69155.pipe.req.XXXXXXXXXX
    +gitstatus_start_impl:21> req_fifo=/var/folders/f_/8ll4ckc519qbw9h8rw7qfmlxs92fcj/T//gitstatus.69155.pipe.req.ydc6Nd89hW
    +gitstatus_start_impl:22> mkfifo /var/folders/f_/8ll4ckc519qbw9h8rw7qfmlxs92fcj/T//gitstatus.69155.pipe.req.ydc6Nd89hW
    +gitstatus_start_impl:24> resp_fifo=+gitstatus_start_impl:24> mktemp -u /var/folders/f_/8ll4ckc519qbw9h8rw7qfmlxs92fcj/T//gitstatus.69155.pipe.resp.XXXXXXXXXX
    +gitstatus_start_impl:24> resp_fifo=/var/folders/f_/8ll4ckc519qbw9h8rw7qfmlxs92fcj/T//gitstatus.69155.pipe.resp.9NpRk8fs74
    +gitstatus_start_impl:25> mkfifo /var/folders/f_/8ll4ckc519qbw9h8rw7qfmlxs92fcj/T//gitstatus.69155.pipe.resp.9NpRk8fs74
    +gitstatus_start_impl:27> [[ -n DEBUG ]]
    +gitstatus_start_impl:28> log_file=+gitstatus_start_impl:28> mktemp /var/folders/f_/8ll4ckc519qbw9h8rw7qfmlxs92fcj/T//gitstatus.69155.daemon-log.XXXXXXXXXX
    +gitstatus_start_impl:28> log_file=/var/folders/f_/8ll4ckc519qbw9h8rw7qfmlxs92fcj/T//gitstatus.69155.daemon-log.u2CMj5lQRN
    +gitstatus_start_impl:30> typeset -g 'GITSTATUS_DAEMON_LOG_POWERLEVEL9K=/var/folders/f_/8ll4ckc519qbw9h8rw7qfmlxs92fcj/T//gitstatus.69155.daemon-log.u2CMj5lQRN'
    +gitstatus_start_impl:32> local -i threads=0
    +gitstatus_start_impl:33> ((  threads > 0 ))
    +gitstatus_start_impl:34> threads=8
    +gitstatus_start_impl:35> case Darwin (FreeBSD)
    +gitstatus_start_impl:35> case Darwin (*)
    +gitstatus_start_impl:37> ((  ! 1  ))
    +gitstatus_start_impl:37> threads=+gitstatus_start_impl:37> getconf _NPROCESSORS_ONLN
    +gitstatus_start_impl:37> threads=24
    +gitstatus_start_impl:39> ((  threads <= 32  ))
    +gitstatus_start_impl:42> local -a daemon_args=( '--lock-fd=3' '--parent-pid=69155' '--num-threads=24' '--max-num-staged=-1' '--max-num-unstaged=-1' '--max-num-conflicted=-1' '--max-num-untracked=-1' '--dirty-max-index-size=-1' '--log-level=DEBUG' )
    +gitstatus_start_impl:54> local cmd=$'\n      echo $$\n      /Users/algomez/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 --lock-fd=3 --parent-pid=69155 --num-threads=24 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --log-level=DEBUG\n      if [[ $? != (0|10) && $? -le 128 &&\n            -z \'\' &&\n            -f /Users/algomez/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static ]]; then\n        /Users/algomez/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static --lock-fd=3 --parent-pid=69155 --num-threads=24 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --log-level=DEBUG\n      fi\n      echo -nE $\'bye\\x1f0\\x1e\''
    +gitstatus_start_impl:63> local setsid=/usr/local/opt/util-linux/bin/setsid
    +gitstatus_start_impl:64> [[ -x /usr/local/opt/util-linux/bin/setsid ]]
    +gitstatus_start_impl:64> setsid=''
    +gitstatus_start_impl:65> cmd='cd /;  zsh -dfxc $'\''\n'\''\ \ \ \ \ \ echo\ \$\$$'\''\n'\''\ \ \ \ \ \ /Users/algomez/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64\ --lock-fd=3\ --parent-pid=69155\ --num-threads=24\ --max-num-staged=-1\ --max-num-unstaged=-1\ --max-num-conflicted=-1\ --max-num-untracked=-1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ if\ \[\[\ \$\?\ \!=\ \(0\|10\)\ \&\&\ \$\?\ -le\ 128\ \&\&$'\''\n'\''\ \ \ \ \ \ \ \ \ \ \ \ -z\ \'\''\'\''\ \&\&$'\''\n'\''\ \ \ \ \ \ \ \ \ \ \ \ -f\ /Users/algomez/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static\ \]\]\;\ then$'\''\n'\''\ \ \ \ \ \ \ \ /Users/algomez/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static\ --lock-fd=3\ --parent-pid=69155\ --num-threads=24\ --max-num-staged=-1\ --max-num-unstaged=-1\ --max-num-conflicted=-1\ --max-num-untracked=-1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ fi$'\''\n'\''\ \ \ \ \ \ echo\ -nE\ \$\'\''bye\\x1f0\\x1e\'\'' &!'
    +gitstatus_start_impl:71> sysopen -w -o cloexec,sync -u req_fd /var/folders/f_/8ll4ckc519qbw9h8rw7qfmlxs92fcj/T//gitstatus.69155.pipe.req.ydc6Nd89hW
    +gitstatus_start_impl:72> sysopen -r -o cloexec -u resp_fd /var/folders/f_/8ll4ckc519qbw9h8rw7qfmlxs92fcj/T//gitstatus.69155.pipe.resp.9NpRk8fs74
    +gitstatus_start_impl:74> read -u 15 daemon_pid
    +gitstatus_start_impl:69> zsh -dfmxc 'cd /;  zsh -dfxc $'\''\n'\''\ \ \ \ \ \ echo\ \$\$$'\''\n'\''\ \ \ \ \ \ /Users/algomez/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64\ --lock-fd=3\ --parent-pid=69155\ --num-threads=24\ --max-num-staged=-1\ --max-num-unstaged=-1\ --max-num-conflicted=-1\ --max-num-untracked=-1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ if\ \[\[\ \$\?\ \!=\ \(0\|10\)\ \&\&\ \$\?\ -le\ 128\ \&\&$'\''\n'\''\ \ \ \ \ \ \ \ \ \ \ \ -z\ \'\''\'\''\ \&\&$'\''\n'\''\ \ \ \ \ \ \ \ \ \ \ \ -f\ /Users/algomez/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static\ \]\]\;\ then$'\''\n'\''\ \ \ \ \ \ \ \ /Users/algomez/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static\ --lock-fd=3\ --parent-pid=69155\ --num-threads=24\ --max-num-staged=-1\ --max-num-unstaged=-1\ --max-num-conflicted=-1\ --max-num-untracked=-1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ fi$'\''\n'\''\ \ \ \ \ \ echo\ -nE\ \$\'\''bye\\x1f0\\x1e\'\'' &!'
    +gitstatus_start_impl:76> rm -f /var/folders/f_/8ll4ckc519qbw9h8rw7qfmlxs92fcj/T//gitstatus.69155.pipe.req.ydc6Nd89hW /var/folders/f_/8ll4ckc519qbw9h8rw7qfmlxs92fcj/T//gitstatus.69155.pipe.resp.9NpRk8fs74 /var/folders/f_/8ll4ckc519qbw9h8rw7qfmlxs92fcj/T//gitstatus.69155.lock.2YKeekMCbG
    +gitstatus_start_impl:87> zle -F 15 _gitstatus_process_response_POWERLEVEL9K
    +gitstatus_start_impl:89> local reply IFS=''
    +gitstatus_start_impl:90> echo -nE $'hello\C-_\C-^'
    +gitstatus_start_impl:91> read -r -d $'\C-^' -u 15 -t 5.0000000000 reply
                               ^ this command failed

  The content of /var/folders/f_/8ll4ckc519qbw9h8rw7qfmlxs92fcj/T//gitstatus.69155.daemon-log.u2CMj5lQRN (gitstatus daemon log):

    +zsh:1> cd /
    +zsh:1> zsh -dfxc $'\n      echo $$\n      /Users/algomez/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 --lock-fd=3 --parent-pid=69155 --num-threads=24 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --log-level=DEBUG\n      if [[ $? != (0|10) && $? -le 128 &&\n            -z \'\' &&\n            -f /Users/algomez/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static ]]; then\n        /Users/algomez/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static --lock-fd=3 --parent-pid=69155 --num-threads=24 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --log-level=DEBUG\n      fi\n      echo -nE $\'bye\\x1f0\\x1e\''
    +zsh:2> echo 69550
    +zsh:3> /Users/algomez/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 '--lock-fd=3' '--parent-pid=69155' '--num-threads=24' '--max-num-staged=-1' '--max-num-unstaged=-1' '--max-num-conflicted=-1' '--max-num-untracked=-1' '--dirty-max-index-size=-1' '--log-level=DEBUG'
    [2019-09-24 17:49:22 000000010308f5c0 INFO src/gitstatus.cc:157] argv[0]: "/Users/algomez/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64"
    [2019-09-24 17:49:22 000000010308f5c0 INFO src/gitstatus.cc:157] argv[1]: "--lock-fd=3"
    [2019-09-24 17:49:22 000000010308f5c0 INFO src/gitstatus.cc:157] argv[2]: "--parent-pid=69155"
    [2019-09-24 17:49:22 000000010308f5c0 INFO src/gitstatus.cc:157] argv[3]: "--num-threads=24"
    [2019-09-24 17:49:22 000000010308f5c0 INFO src/gitstatus.cc:157] argv[4]: "--max-num-staged=-1"
    [2019-09-24 17:49:22 000000010308f5c0 INFO src/gitstatus.cc:157] argv[5]: "--max-num-unstaged=-1"
    [2019-09-24 17:49:22 000000010308f5c0 INFO src/gitstatus.cc:157] argv[6]: "--max-num-conflicted=-1"
    [2019-09-24 17:49:22 000000010308f5c0 INFO src/gitstatus.cc:157] argv[7]: "--max-num-untracked=-1"
    [2019-09-24 17:49:22 000000010308f5c0 INFO src/gitstatus.cc:157] argv[8]: "--dirty-max-index-size=-1"
    [2019-09-24 17:49:22 000000010308f5c0 INFO src/gitstatus.cc:157] argv[9]: "--log-level=DEBUG"
    [2019-09-24 17:49:22 000000010308f5c0 INFO src/thread_pool.cc:81] Spawning 24 thread(s)

  Your system information:

    zsh:      5.7.1
    uname -a: Darwin C02XX1M4JG5M 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new

```

**Comment by romkatv** [comment] 2019-09-25 07:45
Are you perchance using a corporate macbook? If so, perhaps you can help with https://github.com/romkatv/gitstatus/issues/54?

**Comment by atg22896** [comment] 2019-09-25 19:32
Yes I am using a corporate macbook. Not Amazon either though. I'll read through and see what I can do.

**Comment by romkatv** [comment] 2019-09-25 20:46
duplicate of https://github.com/romkatv/gitstatus/issues/54

**Closed by romkatv** 2019-09-25 20:46 UTC
