### ISSUE TITLE
Feature request: make git status more colourful

### ISSUE THREAD

**Issue by Mellbourn** [romkatv/powerlevel10k#1337] opened 2021-04-02 23:35 UTC
I want git status to be more colorful. For example, this is how I've customized my git prompt:

<img width="268" alt="Colorful git prompt" src="https://user-images.githubusercontent.com/1785727/113461089-73a2a980-941b-11eb-9493-d0a64bed0a55.png">

Here I've made use of colorful (Unicode) characters (that are very portable, they work on macOS, Ubuntu, and WSL). I've also set the text color to red for modified and untracked files red and to green for staged files (matching the file colors of `git status`). The commits ahead/behind are colored dark blue. All shades are slightly different.

You can certainly argue that all other parts of the prompt have black foreground and one-colored nerd font glyphs, so this color scheme is inconsistent. However, I would argue that while many parts of the prompt are useful, the git parts are *crucial* for a developer. They change often and you keep looking at them. This, to me, is reason enough for using colorful icons to make them quick to find visually and making the numbers stand out using different colors. 

If you like this idea, and even like my variant of it, I can make a PR. (My [full custom prompt is here](https://github.com/Mellbourn/dotfiles/blob/master/.p10k.zsh))

(Oh, and one last argument, this issue is [leet](https://en.wikipedia.org/wiki/Leet)!)

**Comment by romkatv** [comment] 2021-04-05 10:40
Thanks for sharing.

Lean and Classic styles use color-coding for different parts of vcs prompt. Rainbow style doesn't. This is by design.

Closing as no action is necessary.

**Closed by romkatv** 2021-04-05 10:40 UTC
