### ISSUE TITLE
it doesn't show me the icons and I use the recommended font

### ISSUE THREAD

**Issue by mr-infinitehawk** [romkatv/powerlevel10k#1091] opened 2020-11-06 04:34 UTC
![image](https://user-images.githubusercontent.com/63200763/98326493-ca6c9a00-1fc7-11eb-81cf-656e6f10c412.png)

**Comment by romkatv** [comment] 2020-11-06 07:05
Please describe the issue.

**Comment by cese01** [comment] 2020-11-06 11:44
Same issue, I'm in a fresh install and at the first configuration of the theme the script don't ask question about icons, font, ascii or unicode, shape, tail, etc.

**Comment by romkatv** [comment] 2020-11-06 11:46
> I'm in a fresh install and at the first configuration of the theme the script don't ask question about icons, font, ascii or unicode, shape, tail, etc.

See https://github.com/romkatv/powerlevel10k/blob/master/README.md#some-prompt-styles-are-missing-from-the-configuration-wizard.

**Comment by cese01** [comment] 2020-11-06 11:55
> > I'm in a fresh install and at the first configuration of the theme the script don't ask question about icons, font, ascii or unicode, shape, tail, etc.
> 
> See https://github.com/romkatv/powerlevel10k/blob/master/README.md#some-prompt-styles-are-missing-from-the-configuration-wizard.

Oh my bad, I forgot to set it, fixed ... thanks a lot

**Comment by romkatv** [comment] 2020-11-08 07:13
Closing because the issue is missing a description and the OP has disappeared without providing one.

**Closed by romkatv** 2020-11-08 07:13 UTC

**Comment by mr-infinitehawk** [comment] 2020-11-10 00:24
srry, i have forgotten to configure the locale when i installed arch and thank you for responding so quickly.

**Comment by mr-infinitehawk** [comment] 2020-11-10 00:24
> Closing because the issue is missing a description and the OP has disappeared without providing one.
srry, i have forgotten to configure the locale when i installed arch and thank you for responding so quickly.

**Comment by mr-infinitehawk** [comment] 2020-11-10 00:25
> Closing because the issue is missing a description and the OP has disappeared without providing one.

srry, i have forgotten to configure the locale when i installed arch and thank you for responding so quickly.
