### ISSUE TITLE
Discolored and shifted prompt characters

### ISSUE THREAD

**Issue by Demetri65** [romkatv/powerlevel10k#1267] opened 2021-02-17 16:34 UTC
So I can't seem to understand what the issue is after looking through all of the troubleshooting I don't think I saw my problem and the solutions didn't seem to fix the discoloration and the shifted end characters and the separators.

<img width="555" alt="Screen Shot 2021-02-17 at 11 31 08 AM" src="https://user-images.githubusercontent.com/42951190/108235506-dfeb7700-7113-11eb-9a63-d3a6e1f5dd55.png">

**Comment by romkatv** [comment] 2021-02-17 16:37
For "shifted end characters", see https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols.

The color is controlled by your terminal. They effect you see is usually caused by the terminal using different colors for background and foreground. There might be a setting in your terminal that disables this unhelpful behavior.

**Comment by Demetri65** [comment] 2021-02-17 16:41
Thanks for the quick reply!

> The color is controlled by your terminal. They effect you see is usually caused by the terminal using different colors for background and foreground. There might be a setting in your terminal that disables this unhelpful behavior.

Yeah sorry, I fixed the colors just now. Ill try the other advice right now and get back to you!

**Comment by romkatv** [comment] 2021-02-17 16:43
Is that Apple Terminal? If so, the easiest solution is to install iTerm2, run `p10k configure` and say Yes when the wizard asks you whether to install the recommended font.

**Comment by Demetri65** [comment] 2021-02-17 16:49
> Is that Apple Terminal? If so, the easiest solution is to install iTerm2, run `p10k configure` and say Yes when the wizard asks you whether to install the recommended font.

I already have the proper font installed it came with the system actually, but I might just have to use it to make my life easier.

**Comment by romkatv** [comment] 2021-02-17 16:51
> I already have the proper font installed it came with the system actually, but I might just have to use it to make my life easier.

My comment still stands. If you heed it, you'll have pixel-perfect prompt.

Closing as fixed.

**Closed by romkatv** 2021-02-17 16:51 UTC
