### ISSUE TITLE
Extra blank line outputted after starting a new iTerm2 instance

### ISSUE THREAD

**Issue by zexxlin** [romkatv/powerlevel10k#1240] opened 2021-01-31 00:56 UTC
![iterm-p10k](https://user-images.githubusercontent.com/48289732/106371583-164d9600-63a1-11eb-9e6d-f6b8074dab13.png)
*new iTerm2 instance with p10k*

![vscode-p10k](https://user-images.githubusercontent.com/48289732/106371962-dd63f000-63a5-11eb-917e-8aa07271b704.png)
*new VSCode Integrated Terminal instance with p10k*

Like shown in the screenshots, an extra blank line **with fixed width** is outputted right after starting a new _iTerm2_ or _VSCode Integrated Terminal_ instance (instead of a window)

The steps I've taken to narrow down the issue scope: 
1. Issue persists with brand new p10k setups 
2. Fine when opening a new window instead of a new instance/process
3. Issue gone after switching to another zsh scheme
4. Fine with built-in Terminal

So I reckon the issue should be caused by both iTerm2 and how p10k interacts with it, but incapable to debug myself. Thanks for your help in advance.

**Comment by romkatv** [comment] 2021-01-31 07:24
Does the problem reproduce if you add the following 3 lines at the very top of `~/.zshrc`?

```zsh
PS1='> '
RPS1='<'
return
```

**Comment by zexxlin** [comment] 2021-01-31 09:45
@romkatv No, the issue is gone with just these 3 lines at the very top.

**Comment by romkatv** [comment] 2021-01-31 09:47
> @romkatv No, the issue is gone with just these 3 lines at the very top.

That's very surprising. I'm 100% sure the issue won't be gone at least with VS Code. Please double check. Do exactly the same thing twice but with different `~/.zshrc`.

**Comment by zexxlin** [comment] 2021-01-31 09:52
![Screen Shot 2021-01-31 at 5 48 23 PM](https://user-images.githubusercontent.com/48289732/106380345-a06f1c00-63ec-11eb-94f3-27b99e37ab0f.png)

![Screen Shot 2021-01-31 at 5 48 34 PM](https://user-images.githubusercontent.com/48289732/106380355-a8c75700-63ec-11eb-832e-b297ec9cea17.png)

It's gone indeed when starting new instance of either iTerm2 or VSCode. My .zshrc is newly set up with just oh-my-zsh and p10k. And if I switch to another zsh scheme, the issue would be gone as well.

**Comment by romkatv** [comment] 2021-01-31 09:54
Please verify 3 times that adding/removing those 3 lines at the top of `~/.zshrc` fixes/breaks both iTerm2 and VS Code deterministically.

**Comment by zexxlin** [comment] 2021-01-31 10:05
![Screen Shot 2021-01-31 at 6 03 46 PM](https://user-images.githubusercontent.com/48289732/106380672-de6d3f80-63ee-11eb-847b-f0f9d29997fe.png)

Thank you sir. Just rechecked, the issue on VSCode side still exists as you've mentioned, while iTerm2 is deterministically fixed.

**Comment by romkatv** [comment] 2021-01-31 10:09
> @romkatv Thank you sir. Just rechecked, the issue on VSCode side still exists as you've mentioned, while iTerm2 is deterministically fixed.

Thanks for the confirmation. These are bugs in the terminals. The bugs are similar but they have different manifestations. In short, these terminals report incorrect tty dimensions for a short time after they are started. You can verify this by adding the following line at the very top of `~/.zshrc`:

```zsh
stty size
```

When you open a terminal, you'll see something like this printed out:

```text
24 80
```

Try running `stty size` manually afterwards. If the output is not the same as the one you've got when you opened a terminal, this indicates a bug in the terminal.

**Comment by romkatv** [comment] 2021-01-31 10:10
You aren't affected by this bug when using other themes because they take a long time to initialize. Powerlevel10k, due to its being faster, is affected. You can work around this by adding `sleep 1` at the top of `~/.zshrc`. Naturally, this will slow down zsh startup.

**Comment by zexxlin** [comment] 2021-01-31 10:23
![Screen Shot 2021-01-31 at 6 12 57 PM](https://user-images.githubusercontent.com/48289732/106381028-0362b200-63f1-11eb-9c44-18da330f51d5.png)
![Screen Shot 2021-01-31 at 6 15 40 PM](https://user-images.githubusercontent.com/48289732/106381039-0c538380-63f1-11eb-8738-af87910515ab.png)

@romkatv  Just did a few experiments, and the result in iTerm2 seems to be consistent with your argument, while VSCode Terminal showed the opposite.

**Comment by romkatv** [comment] 2021-01-31 10:25
Try replacing `stty size` with `typeset -p LINES COLUMNS`.

**Comment by zexxlin** [comment] 2021-01-31 10:57
@romkatv The result is the same, just with different format.
typeset -i10 LINES=X
typeset -i10 COLUMNS=Y

**Comment by romkatv** [comment] 2021-01-31 11:05
> @romkatv The result is the same, just with different format.
> typeset -i10 LINES=X
> typeset -i10 COLUMNS=Y

Could you post a screenshot from VS Code that shows the output of this command, followed by the inverted percent sign and then again the output of this command?

**Comment by zexxlin** [comment] 2021-01-31 11:12
![Screen Shot 2021-01-31 at 7 10 44 PM](https://user-images.githubusercontent.com/48289732/106382074-0ca34d00-63f8-11eb-94f9-d8201c26da31.png)
@romkatv Here's the screenshot.

**Comment by romkatv** [comment] 2021-01-31 11:14
Is this the whole terminal?

**Comment by zexxlin** [comment] 2021-01-31 11:16
Yes exactly sir.

**Comment by romkatv** [comment] 2021-01-31 11:23
The width of the terminal on your screenshot is obviously less than 225 columns and yet VS Code reports it as being 225 columns wide. That's a bug in VS Code terminal.

Previously you've also confirmed a bug in iTerm2 where it reports incorrect tty dimensions soon after you open a new terminal. It reports the width of 80 columns when the real width is 78 columns.

**Comment by zexxlin** [comment] 2021-01-31 11:40
@romkatv Thanks for your time Sir. Sorry about not getting your point about "the _whole_ terminal" before, here I've attached the dimension reported by MacOS's built-in Terminal for comparison, and these two column counts appear reasonably close (227 and 225).

![Screen Shot 2021-01-31 at 7 34 32 PM](https://user-images.githubusercontent.com/48289732/106382562-622d2900-63fb-11eb-850d-860b70ac222a.png)

On the other hand, in the case of VSCode, when the initially reported dimension is **inconsistent** with the real one, the bug weirdly disappears.

![Screen Shot 2021-01-31 at 7 25 46 PM](https://user-images.githubusercontent.com/48289732/106382449-a5d36300-63fa-11eb-98eb-9f14289d1a1f.png)

**Comment by romkatv** [comment] 2021-01-31 11:46
> @romkatv Thanks for your time Sir. Sorry about not getting your point about "the _whole_ terminal" before, here I've attached the dimension reported by MacOS's built-in Terminal for comparison, and these two column counts appear reasonably close (227 and 225).

This means that sometimes these terminals report correct dimensions. This is not the issue. The issue is that sometimes they report incorrect dimensions. They must always report correct dimensions. When they report incorrect dimensions, you can have visual artifacts in your terminal.

> On the other hand, in the case of VSCode, when the initially reported dimension is **inconsistent** with the real one, the bug weirdly disappears.

The bug is still there, just the manifestations may not be apparent. The bug is that the dimensions are reported incorrectly. This is a bug in the terminal.

**Comment by zexxlin** [comment] 2021-01-31 12:24
@romkatv I see, and only built-in Terminal works as intended... So is there any workaround for now? Or if some issue tracker has been established on iTerm or VSCode's side?

**Comment by romkatv** [comment] 2021-01-31 12:27
> @romkatv So is there any workaround for now?

- Use another terminal.
- Disable Instant Prompt in powerlevel10k. This will increase zsh startup time and thus avoid triggering the bug in the terminal.

> Or if some issue tracker has been established on iTerm or VSCode's side?

I recall that this was reported to VS Code but I don't remember if anyone has filed this bug against iTerm2.

Closing as there is nothing to be done in powerlevel10k.

**Closed by romkatv** 2021-01-31 12:27 UTC
