### ISSUE TITLE
Display error when using tmux

### ISSUE THREAD

**Issue by JamesZhutheThird** [romkatv/powerlevel10k#1814] opened 2022-03-26 08:25 UTC
Hello, I've being using p10k for a year and it is wonderful. However tmux is no longer compatible with p10k after I update zsh this month. At first I thought it was a problem with the tmux version, so I updated it to the latest version(Since I don't have sudo permissions, I test on my own WSL), and although the output changed, it didn't look like the problem was fixed once for all. 

![图片](https://user-images.githubusercontent.com/35760593/160230582-9a4f8913-208f-412b-a28f-3724b9ce358e.png)
![Remote surver with tmux](https://user-images.githubusercontent.com/35760593/160230981-799029d8-29aa-4aad-aac6-0f2fdc01d54e.gif)
![Local WSL with updated tmux(3.0a-2ubuntu0.3)](https://user-images.githubusercontent.com/35760593/160230974-c3e00ecc-2fc2-4815-b06d-e3351402b491.gif)

Thanks a lot 😊

**Comment by romkatv** [comment] 2022-03-26 10:51
What happens if you disable powerlevl10k but other than that keep everything unchanged?

**Comment by JamesZhutheThird** [comment] 2022-03-26 11:11
> 

The problem persists, looks like it's caused by zsh. And when I change into the bash shell, the tmux works fine.

**Comment by romkatv** [comment] 2022-03-26 11:19
You probably have incorrect `TERM`.

**Comment by romkatv** [comment] 2022-03-26 11:19
Closing because the issue is not caused by powerlevel10k.

**Closed by romkatv** 2022-03-26 11:19 UTC

**Comment by JamesZhutheThird** [comment] 2022-03-26 11:34
Thanks a lot, and my final solution is

1. Inside `.zshrc`, put `[[ -n $TMUX ]] && export TERM="xterm-256color"`

2. And, inside `.tmux.conf`, put `set -g default-terminal "screen-256color"`

**Comment by romkatv** [comment] 2022-03-26 11:42
Step (2) looks good to me but step (1) shouldn't be there. For one, `xterm-256color` is invalid when running within tmux. And two, you should never set `TERM` in `.zshrc`.

**Comment by JamesZhutheThird** [comment] 2022-03-26 11:46
That's weird since step(2) was already set a long time ago, and just now I only followed step(1), and then run `exec zsh`, and the problem was somehow magically solved.

**Comment by JamesZhutheThird** [comment] 2022-03-26 11:47
BTW, I referred to this [webpage](https://unix.stackexchange.com/questions/139082/zsh-set-term-screen-256color-in-tmux-but-xterm-256color-without-tmux)
