### ISSUE TITLE
cowsay invoked twice || zshrc output appears twice

### ISSUE THREAD

**Issue by liordon** [romkatv/powerlevel10k#1769] opened 2022-02-13 10:04 UTC
I tried to print a welcome message to my terminal, but it always gets printed twice: once correctly and once uncolored.

I tried following the simple instructions of issue #1345 but to no avail. I suspect There's something very basic that I didn't understand yet.

my .zshrc file is:
```
fortune | cowsay | lolcat


# OK to perform console I/O before this point.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
# From this point on, until zsh is fully initialized, console input won't work and
# console output may appear uncolored.

source /opt/homebrew/opt/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
export JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk8-zulu/Contents/Home

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
```

it also produces a different quote at each appearance of the cow, so it seems as if the first line is invoked twice... why is that?
![Screen Shot 2022-02-13 at 12 04 00](https://user-images.githubusercontent.com/4543336/153748177-f14645bf-1fb1-4c58-83df-b7eee07c5233.png)

**Comment by romkatv** [comment] 2022-02-13 14:25
What is the output of the following command?

```zsh
zsh --sourcetrace -lic ''
```

**Comment by liordon** [comment] 2022-02-13 17:18
<img width="828" alt="Screen Shot 2022-02-13 at 19 18 01" src="https://user-images.githubusercontent.com/4543336/153766574-33815c50-8d8c-42c3-9d26-3c8883fca9f4.png">

**Comment by romkatv** [comment] 2022-02-14 08:33
Thanks. What's the output of the following command?

```zsh
() {
  emulate -L zsh -o xtrace
  command cat /etc/zprofile
  command cat ~/.zprofile
}
```

Please post it as text (not a screenshot).

**Comment by liordon** [comment] 2022-02-14 09:43
oh, sorry about the screenshot!

```
+(anon):2> cat /etc/zprofile
# System-wide profile for interactive zsh(1) login shells.

# Setup user specific overrides for this in ~/.zprofile. See zshbuiltins(1)
# and zshoptions(1) for more details.

if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi
+(anon):3> cat /Users/liorsam/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"
source ~/.zshrc

##
# Your previous /Users/liorsam/.zprofile file was backed up as /Users/liorsam/.zprofile.macports-saved_2022-01-12_at_21:17:58
##

# MacPorts Installer addition on 2022-01-12_at_21:17:58: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.


# MacPorts Installer addition on 2022-01-12_at_21:17:58: adding an appropriate MANPATH variable for use with MacPorts.
export MANPATH="/opt/local/share/man:$MANPATH"
# Finished adapting your MANPATH environment variable for use with MacPorts.
```

**Comment by liordon** [comment] 2022-02-14 10:14
I fixed the issue name, since anlthough the autocorrect was amusing someone might benefit from actually finding this in the future.

**Comment by romkatv** [comment] 2022-02-14 10:19
What do you get with this zshrc?

```zsh
fortune | cowsay | lolcat
export JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk8-zulu/Contents/Home
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
```

**Comment by liordon** [comment] 2022-02-14 11:01
```
 _________________________________________
/ In buying horses and taking a wife shut \
| your eyes tight and commend yourself to |
\ God.                                    /
 -----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
 ________________________________________
/ It is often the case that the man who  \
| can't tell a lie thinks he is the best |
| judge of one.                          |
|                                        |
| -- Mark Twain, "Pudd'nhead Wilson's    |
\ Calendar"                              /
 ----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```
seems to still occur twice (both times are colorful now.)
which seems to suggest the problem is in my iterm and not p10k

**Comment by romkatv** [comment] 2022-02-14 11:05
The problem is somewhere in your zsh rc files. Try commenting lines one by one. Closing because it's not specific to powerlvel10k.

**Closed by romkatv** 2022-02-14 11:05 UTC
