### ISSUE TITLE
_p9k_wrap_widgets breaks vi-repeat-change numeric argument

### ISSUE THREAD

**Issue by xPMo** [romkatv/powerlevel10k#1042] opened 2020-10-05 21:52 UTC
To reproduce:

1. Use Vi Mode (`bindkey -v`)
2. Enter viins (`i`) and type `aaaaaaaa`
3. Enter vicmd (Esc) and return to the start of the line (`^`)
4. Delete 2 characters (`d2l` or `2dl`)
5. Repeat the change with a different numeric argument (`5.`).

**Expected behavior**: Five characters are deleted upon `5.`, leaving `a`

**Actual behavior**: Two characters are deleted instead, leaving `aaaa`.

I believe I've narrowed it down to commenting out `zle-line-pre-redraw` in `_p9k_wrap_widgets`.

I have confirmed this with a clean ~/.p10k.zsh.

**Comment by romkatv** [comment] 2020-10-07 12:51
Thanks for letting me know. I've reported this upstream: https://zsh.org/workers/47432. I won't attempt to debug or fix this.

**Comment by romkatv** [comment] 2020-10-21 12:14
Closing because I don't intend to do anything here (see above). It doesn't appear that anyone is working on fixing the upstream bug in zsh. If this bothers you, please consider contributing a patch.

**Closed by romkatv** 2020-10-21 12:14 UTC

**Comment by xPMo** [comment] 2020-12-15 23:04
This seems to work:

```diff
diff --git a/Src/Zle/zle_main.c b/Src/Zle/zle_main.c
index 8c0534708..4a9290833 100644
--- a/Src/Zle/zle_main.c
+++ b/Src/Zle/zle_main.c
@@ -1063,7 +1063,7 @@ redrawhook(void)
     if ((initthingy = rthingy_nocreate("zle-line-pre-redraw"))) {
 	/* Duplicating most of zlecallhook() to save additional state */
 	int saverrflag = errflag, savretflag = retflag;
-	int lastcmd_prev = lastcmd;
+	int lastcmd_prev = lastcmd, viinrepeat_prev = viinrepeat;
 	int old_incompfunc = incompfunc;
 	char *args[2];
 	Thingy lbindk_save = lbindk, bindk_save = bindk;
@@ -1084,6 +1084,9 @@ redrawhook(void)
 	errflag = saverrflag | (errflag & ERRFLAG_INT);
 	retflag = savretflag;
 
+	/* Restore viinrepeat */
+	viinrepeat = viinrepeat_prev;
+
 	unrefthingy(initthingy);
 	unrefthingy(lbindk);
 	unrefthingy(bindk);
```

**Comment by xPMo** [comment] 2020-12-15 23:13
I've made a fix that works for me as a PR to the zsh-users/zsh repo since I'm not on the ML.

**Comment by romkatv** [comment] 2020-12-16 08:35
Thanks for the update. I can confirm that your fix works. I've forwarded your patch to zsh-workers.
