### ISSUE TITLE
powerlevel10K's icons are cracked....

### ISSUE THREAD

**Issue by azalealuv** [romkatv/powerlevel10k#1285] opened 2021-03-06 12:56 UTC
Hi....I am a Window10 user.
And I installed Ubuntu 18.04,oh my zsh,and powerlevel10k in my window terminal.
And also I installed 'MesloLGS NF Regular.ttf, MesloLGS NF Bold.ttf, MesloLGS NF Italic.ttf, MesloLGS NF Bold Italic.ttf' font.
and I all set up from powerlevel10K instruction.
But after that,I have been experiencing icon-cracked situation in my window terminal.
Ubuntu's icons are turned to 'question mark' as I attached.

After install powerlevel10K, it works fine, powerlevel10K's icons are fine.
But after a few days, it becomes broken.....

I can't solve this problem.
I need your help.
![Untitled-1](https://user-images.githubusercontent.com/77909851/110207445-d9585000-7ec6-11eb-98e5-b7dd5680c96e.jpg)

**Comment by romkatv** [comment] 2021-03-06 13:06
As I mentioned over email, you need to change the font used by Microsoft Terminal. See https://github.com/romkatv/powerlevel10k#manual-font-installation. Search for "Microsoft Terminal" to see the instructions pertaining to your terminal. Once you change the font, run `p10k configure`.

**Comment by azalealuv** [comment] 2021-03-06 13:16
As I said above,I did it above,I did MesloLGS NF font setup, fontFace, p10k configure...everything.....
As I said,after all set up,it works fine...icons are not cracked....
But after a few days,it becomes cracked......ㅜㅜ
Whenever it happened this,I used to install all of MesloLGS NF font again.....But it's pretty annoyed......

**Comment by romkatv** [comment] 2021-03-06 13:26
> As I said,after all set up,it works fine...icons are not cracked....

I don't see what you said it.

> But after a few days,it becomes cracked......ㅜㅜ

It means that something is modifying your terminal's settings, or modifying the installed font. Powerlevel10k doesn't do these things. You need to figure out what does.

**Comment by azalealuv** [comment] 2021-03-06 13:37
Thanks anyway!!!!

**Comment by romkatv** [comment] 2021-03-06 13:39
You are welcome.

Closing because the issue is not with Powerlevel10k.

**Closed by romkatv** 2021-03-06 13:39 UTC
