### ISSUE TITLE
Prompt Displays Loading

### ISSUE THREAD

**Issue by gregf** [romkatv/powerlevel10k#34] opened 2019-03-20 07:56 UTC
Soon as I cd to a directory (git or not) I get this loading section added to my prompt.

![2019-03-20-035608_1660x1006_scrot](https://user-images.githubusercontent.com/980/54667965-1baed980-4ac4-11e9-9b1e-05f3625b6ca1.png)

**Comment by romkatv** [comment] 2019-03-20 08:14
Good lord! What does the following say?

```zsh
gitstatus_check POWERLEVEL9K && echo gitstatus enabled
gitstatus_query POWERLEVEL9K && set | egrep '^VCS_STATUS'
```
Also, what happens if you `cd` into a git directory?

P.S.

I'll be offline for a few hours. Will debug as soon as I get back.

**Comment by gscalise** [comment] 2019-03-20 09:14
Hi! I'm having the same issue. By enabling logging I've found that the issue seems to be related to gitstatusd crashing trying to lock a lockfile:

```
+zsh:2> /Users/gscalise/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-romkatv-SLASH-powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 '--lock-fd=3' '--dirty-max-index-size=-1' '--num-threads=4'
[2019-03-20 08:59:55 INFO src/gitstatus.cc:120] argv[0]: /Users/gscalise/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-romkatv-SLASH-powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64
[2019-03-20 08:59:55 INFO src/gitstatus.cc:120] argv[1]: --lock-fd=3
[2019-03-20 08:59:55 INFO src/gitstatus.cc:120] argv[2]: --dirty-max-index-size=-1
[2019-03-20 08:59:55 INFO src/gitstatus.cc:120] argv[3]: --num-threads=4
[2019-03-20 08:59:55 INFO src/git.cc:72] Spawning 4 thread(s)
[2019-03-20 08:59:55 INFO src/gitstatus.cc:132] Processing request: hello []
[2019-03-20 08:59:55 INFO src/response.cc:49] Replying without git status
[2019-03-20 08:59:55 INFO src/gitstatus.cc:135] Successfully processed request: hello []
[2019-03-20 08:59:55 INFO src/gitstatus.cc:132] Processing request: 1553072395.2464621067 _p9k_vcs_resume [/Users/gscalise]
[2019-03-20 08:59:55 INFO src/response.cc:49] Replying without git status
[2019-03-20 08:59:55 INFO src/gitstatus.cc:135] Successfully processed request: 1553072395.2464621067 _p9k_vcs_resume [/Users/gscalise]
[2019-03-20 08:59:56 FATAL src/request.cc:51] fcntl(fd, F_GETLK, &flock) != -1: Invalid argument
+zsh:3> echo -nE $'bye\C-_0\C-^'
```

the output from `dtruss` shows:

```
51734/0x45b645:  fcntl(0x3, 0x7, 0x7FFEEC3471D8)		 = -1 Err#22
```

and the output from `lsof` for the gitstatusd daemon process:
```
COMMAND   PID     USER   FD   TYPE DEVICE   SIZE/OFF     NODE NAME
zsh     51731 gscalise  cwd    DIR    1,5       2848   932465 /Users/gscalise
zsh     51731 gscalise  txt    REG    1,5     610288   643663 /bin/zsh
zsh     51731 gscalise  txt    REG    1,5     841456  4309268 /usr/lib/dyld
zsh     51731 gscalise  txt    REG    1,5 1172107264  4653614 /private/var/db/dyld/dyld_shared_cache_x86_64h
zsh     51731 gscalise    0u  FIFO               0t0 10118452 /private/var/folders/w7/jv70gmh10k7bc95yntvqnb81hy7cw1/T/gitstatus.51179.pipe.req.NAo7p7Rqps
zsh     51731 gscalise    1u  FIFO               0t0 10118454 /private/var/folders/w7/jv70gmh10k7bc95yntvqnb81hy7cw1/T/gitstatus.51179.pipe.resp.PmvNP4s6VN
zsh     51731 gscalise    2w   REG    1,5        712 10118455 /private/var/folders/w7/jv70gmh10k7bc95yntvqnb81hy7cw1/T/gitstatus.51179.log.euiK3RrXMu
zsh     51731 gscalise    3r   REG    1,5          0 10118450 /private/var/folders/w7/jv70gmh10k7bc95yntvqnb81hy7cw1/T/gitstatus.51179.lock.szDmmNymLh
zsh     51731 gscalise   10u   CHR    2,0        0t0      316 /dev/tty
zsh     51731 gscalise   11r   CHR    3,2        0t0      317 /dev/null
zsh     51731 gscalise   12u  FIFO               0t0 10118452 /private/var/folders/w7/jv70gmh10k7bc95yntvqnb81hy7cw1/T/gitstatus.51179.pipe.req.NAo7p7Rqps
zsh     51731 gscalise   13u  FIFO               0t0 10118454 /private/var/folders/w7/jv70gmh10k7bc95yntvqnb81hy7cw1/T/gitstatus.51179.pipe.resp.PmvNP4s6VN
```

Meaning that fd #3 is the lock file.

I'm running OS X 10.13.6 and zsh 5.3

**Comment by gregf** [comment] 2019-03-20 09:25
![2019-03-20-052522_1660x1006_scrot](https://user-images.githubusercontent.com/980/54673425-9da4ff80-4ad0-11e9-8de7-a6bd40b46680.png)

Second command hangs

**Comment by romkatv** [comment] 2019-03-20 09:58
@gscalise  Thanks for the superb debugging info! I was able to guess what's going while reading your message on my phone riding a bus home.

When gitstatus loads, it performs a self-check, which goes through the same code path as the real thing. If self-check fails, gitstatus disables itself and makes powerlevel10k fall back to vcs_info. However, we can see in the logs that the self-check has succeeded, meaning that locking has succeeded, but then the real request complained that the lock file descriptor is invalid. The only difference is that in between two requests the log file was unlinked. I prefer to unlink files immediately after opening them (same with pipes) so that I don't have to perform any cleanup in the end. Both of you are using bsd-based kernels (which is arguably the real issue here, ha-ha). Apparently, on bsd you cannot lock a file descriptor for an unlinked file. I worked around this by not deleting the lock file until shell exits. This introduces a slight risk of having empty files in your temp directory when they aren't supposed to be there (e.g., if your zsh crashes).

Please pull powerlevel10k and let me know if things are alright again.

And once against thanks to both of you for speedy reporting of this issue.

**Comment by gregf** [comment] 2019-03-20 10:34
@romkatv still not working here

**Comment by gscalise** [comment] 2019-03-20 10:36
@romkatv same here... still not working.

**Comment by romkatv** [comment] 2019-03-20 10:41
That's odd. I reproduced this problem without the latest fix and observed it disappear with the fix. Debugging some more...

**Comment by gscalise** [comment] 2019-03-20 10:59
I think the issue could be the way you're initializing the flock struct in request.cc in gitstatus. I'm going to try initializing the struct by zeroing it and settings the fields by name.

**Comment by romkatv** [comment] 2019-03-20 11:03
Good call! Zeroing isn't a problem but the order of fields is.

I'm rebuilding the binaries with the fix.

**Comment by romkatv** [comment] 2019-03-20 11:10
Should be fixed now. Please pull.

**Comment by gscalise** [comment] 2019-03-20 11:24
Seems to be fixed now! I'll use this for some time and I'll report if I see a regression! 👍

**Comment by romkatv** [comment] 2019-03-20 11:29
This was the most embarrassing bug in powerlevel10k (the most embarrassing bug _so far_, he-he). Not only it caused a crash (intentionally triggered `abort()` but still a crash), but it was also in C++ code. It's one thing for me to mess up zsh which I have only just started using, and quite another to screw up C++ -- the language I make a living with.

The good news is that the churn rate in powerlevel10k is going to be close to zero starting today or tomorrow as I'll be working on something else. I'll still fix all reported bugs in powerlevel10k of course. With fewer changes there should also be fewer bugs and annoyances.

**Comment by gregf** [comment] 2019-03-20 11:33
Seems to be fixed for me. Thank you for your speedy fix @romkatv !

**Closed** 2019-03-20 11:33 UTC

**Comment by bebound** [comment] 2019-05-10 16:14
I just met the same issue as grepgf, and also the same output.
The reason is that my zsh was broken.
```
zsh --version 
dyld: Library not loaded: /usr/local/opt/gdbm/lib/libgdbm.4.dylib
  Referenced from: /usr/local/bin/zsh
  Reason: image not found
[1]    15210 abort      zsh --version
```
Fixed by reinstalling zsh.
It weird that everything works fine with `powerlevel9k`, and zsh works normally except the `loading` sign.
