### ISSUE TITLE
Paraview repository shown as "dirty"

### ISSUE THREAD

**Issue by rubendibattista** [romkatv/powerlevel10k#428] opened 2020-01-20 14:44 UTC
I just cloned Paraview repository from Github, but it is shown as "dirty": 
![image](https://user-images.githubusercontent.com/8077364/72735224-a99f9900-3b9b-11ea-8cd7-87f80d820738.png)

`git status` reports everything is ok. 
```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

is this a bug?

**Comment by romkatv** [comment] 2020-01-20 15:51
Very likely a bug. Let's try to figure out what's going on. Please run the following command and attach `/tmp/p10k.txt` to this issue.

```zsh
(
  emulate -L zsh -o err_return -o xtrace -o no_unset
  cd /home/ruben.di-battista/git/ParaView
  git status
  git config -l
  typeset -pm 'POWERLEVEL9K_*|ZSH_VERSION'
  uname -a
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/gitstatus.XXXXXXXXXX)"
  {
    git clone --depth=1 https://github.com/romkatv/gitstatus.git $tmp
    zsh -dfeic "
      GITSTATUS_LOG_LEVEL=DEBUG
      source ${(q)tmp}/gitstatus.plugin.zsh
      gitstatus_start -s -1 -u -1 -c -1 -d -1 -m -1 MY
      gitstatus_query -p MY
      typeset -m 'VCS_STATUS_*'
      sleep 2
      gitstatus_query -p MY
      typeset -m 'VCS_STATUS_*'
      cat \$GITSTATUS_XTRACE_MY
      cat \$GITSTATUS_DAEMON_LOG_MY"
  } always {
    rm -rf $tmp
  }
) &>/tmp/p10k.txt
```

**Comment by rubendibattista** [comment] 2020-01-20 17:11
```
+debugp10k.sh:3> cd /home/ruben.di-battista/git/ParaView
+debugp10k.sh:4> git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
+debugp10k.sh:5> git config -l
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
push.default=simple
color.ui=true
user.name=Ruben Di Battista
user.email=ruben.di-battista@polytechnique.edu
core.excludesfile=~/.gitignore
core.pager=diff-so-fancy | less --tabs=4 -RFX
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/Kitware/ParaView.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
submodule.ThirdParty/IceT/vtkicet.active=true
submodule.ThirdParty/IceT/vtkicet.url=https://gitlab.kitware.com/paraview/icet.git
submodule.ThirdParty/QtTesting/vtkqttesting.active=true
submodule.ThirdParty/QtTesting/vtkqttesting.url=https://gitlab.kitware.com/paraview/qttesting.git
submodule.Utilities/VisItBridge.active=true
submodule.Utilities/VisItBridge.url=https://gitlab.kitware.com/paraview/visitbridge.git
submodule.VTK.active=true
submodule.VTK.url=https://gitlab.kitware.com/vtk/vtk.git
+debugp10k.sh:6> typeset -pm 'POWERLEVEL9K_*|ZSH_VERSION'
typeset ZSH_VERSION=5.4.1
+debugp10k.sh:7> uname -a
Linux matisse.polytechnique.fr 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
+debugp10k.sh:8> local tmp
+debugp10k.sh:9> tmp=+debugp10k.sh:9> mktemp -d /tmp/gitstatus.XXXXXXXXXX
+debugp10k.sh:9> tmp=/tmp/gitstatus.jj5qFyPVtc 
+debugp10k.sh:11> git clone '--depth=1' https://github.com/romkatv/gitstatus.git /tmp/gitstatus.jj5qFyPVtc
Cloning into '/tmp/gitstatus.jj5qFyPVtc'...
+debugp10k.sh:12> zsh -dfeic $'\n      GITSTATUS_LOG_LEVEL=DEBUG\n      source /tmp/gitstatus.jj5qFyPVtc/gitstatus.plugin.zsh\n      gitstatus_start -s -1 -u -1 -c -1 -d -1 -m -1 MY\n      gitstatus_query -p MY\n      typeset -m \'VCS_STATUS_*\'\n      sleep 2\n      gitstatus_query -p MY\n      typeset -m \'VCS_STATUS_*\'\n      cat $GITSTATUS_XTRACE_MY\n      cat $GITSTATUS_DAEMON_LOG_MY'
VCS_STATUS_COMMITS_AHEAD=0
VCS_STATUS_COMMITS_BEHIND=0
VCS_STATUS_TAG=''
VCS_STATUS_REMOTE_NAME=origin
VCS_STATUS_NUM_STAGED=0
VCS_STATUS_HAS_UNTRACKED=0
VCS_STATUS_NUM_UNTRACKED=0
VCS_STATUS_RESULT=ok-sync
VCS_STATUS_STASHES=0
VCS_STATUS_INDEX_SIZE=0
VCS_STATUS_HAS_UNSTAGED=0
VCS_STATUS_NUM_UNSTAGED_DELETED=0
VCS_STATUS_WORKDIR=/users/ruben.di-battista/git/ParaView
VCS_STATUS_NUM_CONFLICTED=0
VCS_STATUS_NUM_UNSTAGED=0
VCS_STATUS_ACTION=''
VCS_STATUS_LOCAL_BRANCH=master
VCS_STATUS_REMOTE_BRANCH=master
VCS_STATUS_NUM_STAGED_DELETED=0
VCS_STATUS_COMMIT=2c438fd4cdf110e1d53cc38ca621961d718245ec
VCS_STATUS_REMOTE_URL=https://github.com/Kitware/ParaView.git
VCS_STATUS_NUM_STAGED_NEW=0
VCS_STATUS_HAS_CONFLICTED=0
VCS_STATUS_HAS_STAGED=0
VCS_STATUS_COMMITS_AHEAD=0
VCS_STATUS_COMMITS_BEHIND=0
VCS_STATUS_TAG=''
VCS_STATUS_REMOTE_NAME=origin
VCS_STATUS_NUM_STAGED=0
VCS_STATUS_HAS_UNTRACKED=0
VCS_STATUS_NUM_UNTRACKED=0
VCS_STATUS_RESULT=ok-sync
VCS_STATUS_STASHES=0
VCS_STATUS_INDEX_SIZE=0
VCS_STATUS_HAS_UNSTAGED=0
VCS_STATUS_NUM_UNSTAGED_DELETED=0
VCS_STATUS_WORKDIR=/users/ruben.di-battista/git/ParaView
VCS_STATUS_NUM_CONFLICTED=0
VCS_STATUS_NUM_UNSTAGED=0
VCS_STATUS_ACTION=''
VCS_STATUS_LOCAL_BRANCH=master
VCS_STATUS_REMOTE_BRANCH=master
VCS_STATUS_NUM_STAGED_DELETED=0
VCS_STATUS_COMMIT=2c438fd4cdf110e1d53cc38ca621961d718245ec
VCS_STATUS_REMOTE_URL=https://github.com/Kitware/ParaView.git
VCS_STATUS_NUM_STAGED_NEW=0
VCS_STATUS_HAS_CONFLICTED=0
VCS_STATUS_HAS_STAGED=0
+gitstatus_start_impl:6> ((  daemon_pid == -1  ))
+gitstatus_start_impl:7> local os
+gitstatus_start_impl:8> local daemon=''
+gitstatus_start_impl:9> [[ -n '' ]]
+gitstatus_start_impl:10> os=+gitstatus_start_impl:10> uname -s
+gitstatus_start_impl:10> os=Linux 
+gitstatus_start_impl:10> [[ -n Linux ]]
+gitstatus_start_impl:11> [[ Linux != Linux ||+gitstatus_start_impl:11> uname -o
+gitstatus_start_impl:11> [[ Linux != Linux || GNU/Linux != Android ]]
+gitstatus_start_impl:12> [[ linux != (mingw|msys)* ]]
+gitstatus_start_impl:13> local arch
+gitstatus_start_impl:13> arch=+gitstatus_start_impl:13> uname -m
+gitstatus_start_impl:13> arch=x86_64 
+gitstatus_start_impl:13> [[ -n x86_64 ]]
+gitstatus_start_impl:14> daemon=/tmp/gitstatus.jj5qFyPVtc/bin/gitstatusd-linux-x86_64 
+gitstatus_start_impl:16> [[ -x /tmp/gitstatus.jj5qFyPVtc/bin/gitstatusd-linux-x86_64 ]]
+gitstatus_start_impl:18> lock_file=/tmp/gitstatus.13808.lock.1579540229.1646237373.6360 
+gitstatus_start_impl:19> echo -n
+gitstatus_start_impl:20> zsystem flock -f lock_fd /tmp/gitstatus.13808.lock.1579540229.1646237373.6360
+gitstatus_start_impl:22> req_fifo=/tmp/gitstatus.13808.req.1579540229.1649093628.19559 
+gitstatus_start_impl:23> resp_fifo=/tmp/gitstatus.13808.resp.1579540229.1649353504.1093 
+gitstatus_start_impl:24> mkfifo /tmp/gitstatus.13808.req.1579540229.1649093628.19559 /tmp/gitstatus.13808.resp.1579540229.1649353504.1093
+gitstatus_start_impl:26> local -i threads=0
+gitstatus_start_impl:27> ((  threads > 0 ))
+gitstatus_start_impl:28> threads=8 
+gitstatus_start_impl:29> [[ -n Linux ]]
+gitstatus_start_impl:30> case Linux (FreeBSD)
+gitstatus_start_impl:30> case Linux (*)
+gitstatus_start_impl:32> ((  ! 1  ))
+gitstatus_start_impl:32> threads=+gitstatus_start_impl:32> getconf _NPROCESSORS_ONLN
+gitstatus_start_impl:32> threads=16 
+gitstatus_start_impl:34> ((  threads <= 32  ))
+gitstatus_start_impl:37> local -a daemon_args=( '--lock-fd=3' '--parent-pid=13808' '--num-threads=16' '--max-num-staged=-1' '--max-num-unstaged=-1' '--max-num-conflicted=-1' '--max-num-untracked=-1' '--dirty-max-index-size=-1' '--log-level=DEBUG' )
+gitstatus_start_impl:49> local cmd=$'\n        exec >&4\n        echo $$\n        /tmp/gitstatus.jj5qFyPVtc/bin/gitstatusd-linux-x86_64 --lock-fd=3 --parent-pid=13808 --num-threads=16 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --log-level=DEBUG\n        if [[ $? != (0|10) && $? -le 128 && -f /tmp/gitstatus.jj5qFyPVtc/bin/gitstatusd-linux-x86_64-static ]]; then\n          /tmp/gitstatus.jj5qFyPVtc/bin/gitstatusd-linux-x86_64-static --lock-fd=3 --parent-pid=13808 --num-threads=16 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --log-level=DEBUG\n        fi\n        echo -nE $\'bye\\x1f0\\x1e\''
+gitstatus_start_impl:57> local setsid=/usr/bin/setsid
+gitstatus_start_impl:58> [[ -x /usr/bin/setsid ]]
+gitstatus_start_impl:58> setsid=/usr/bin/setsid 
+gitstatus_start_impl:63> local zsh=/home/ruben.di-battista/.local/bin/zsh
+gitstatus_start_impl:64> [[ -x /home/ruben.di-battista/.local/bin/zsh ]]
+gitstatus_start_impl:65> cmd='cd /; read; unsetopt bg_nice; /usr/bin/setsid /home/ruben.di-battista/.local/bin/zsh -dfxc $'\''\n'\''\ \ \ \ \ \ \ \ exec\ \>\&4$'\''\n'\''\ \ \ \ \ \ \ \ echo\ \$\$$'\''\n'\''\ \ \ \ \ \ \ \ /tmp/gitstatus.jj5qFyPVtc/bin/gitstatusd-linux-x86_64\ --lock-fd=3\ --parent-pid=13808\ --num-threads=16\ --max-num-staged=-1\ --max-num-unstaged=-1\ --max-num-conflicted=-1\ --max-num-untracked=-1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ \ \ if\ \[\[\ \$\?\ !=\ \(0\|10\)\ \&\&\ \$\?\ -le\ 128\ \&\&\ -f\ /tmp/gitstatus.jj5qFyPVtc/bin/gitstatusd-linux-x86_64-static\ \]\]\;\ then$'\''\n'\''\ \ \ \ \ \ \ \ \ \ /tmp/gitstatus.jj5qFyPVtc/bin/gitstatusd-linux-x86_64-static\ --lock-fd=3\ --parent-pid=13808\ --num-threads=16\ --max-num-staged=-1\ --max-num-unstaged=-1\ --max-num-conflicted=-1\ --max-num-untracked=-1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ \ \ fi$'\''\n'\''\ \ \ \ \ \ \ \ echo\ -nE\ \$\'\''bye\\x1f0\\x1e\'\'' &!; rm -f /tmp/gitstatus.13808.req.1579540229.1649093628.19559 /tmp/gitstatus.13808.resp.1579540229.1649353504.1093 /tmp/gitstatus.13808.lock.1579540229.1646237373.6360' 
+gitstatus_start_impl:71> sysopen -w -o cloexec,sync -u req_fd /tmp/gitstatus.13808.req.1579540229.1649093628.19559
+gitstatus_start_impl:72> sysopen -r -o cloexec -u resp_fd /tmp/gitstatus.13808.resp.1579540229.1649353504.1093
+gitstatus_start_impl:73> echo -nE $'0\nhello\C-_\C-^'
+gitstatus_start_impl:76> ((  async  ))
+gitstatus_start_impl:79> local reply IFS=''
+gitstatus_start_impl:69> /home/ruben.di-battista/.local/bin/zsh -dfmxc 'cd /; read; unsetopt bg_nice; /usr/bin/setsid /home/ruben.di-battista/.local/bin/zsh -dfxc $'\''\n'\''\ \ \ \ \ \ \ \ exec\ \>\&4$'\''\n'\''\ \ \ \ \ \ \ \ echo\ \$\$$'\''\n'\''\ \ \ \ \ \ \ \ /tmp/gitstatus.jj5qFyPVtc/bin/gitstatusd-linux-x86_64\ --lock-fd=3\ --parent-pid=13808\ --num-threads=16\ --max-num-staged=-1\ --max-num-unstaged=-1\ --max-num-conflicted=-1\ --max-num-untracked=-1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ \ \ if\ \[\[\ \$\?\ !=\ \(0\|10\)\ \&\&\ \$\?\ -le\ 128\ \&\&\ -f\ /tmp/gitstatus.jj5qFyPVtc/bin/gitstatusd-linux-x86_64-static\ \]\]\;\ then$'\''\n'\''\ \ \ \ \ \ \ \ \ \ /tmp/gitstatus.jj5qFyPVtc/bin/gitstatusd-linux-x86_64-static\ --lock-fd=3\ --parent-pid=13808\ --num-threads=16\ --max-num-staged=-1\ --max-num-unstaged=-1\ --max-num-conflicted=-1\ --max-num-untracked=-1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ \ \ fi$'\''\n'\''\ \ \ \ \ \ \ \ echo\ -nE\ \$\'\''bye\\x1f0\\x1e\'\'' &!; rm -f /tmp/gitstatus.13808.req.1579540229.1649093628.19559 /tmp/gitstatus.13808.resp.1579540229.1649353504.1093 /tmp/gitstatus.13808.lock.1579540229.1646237373.6360'
+gitstatus_start_impl:80> read -ru 17 reply
+gitstatus_start_impl:81> [[ 13890 == <1-> ]]
+gitstatus_start_impl:82> daemon_pid=reply 
+gitstatus_start_impl:93> zle -F 17 _gitstatus_process_response_MY
+gitstatus_start_impl:95> read -r -d $'\C-^' -u 17 -t 5.0000000000 reply
+gitstatus_start_impl:96> [[ $'hello\C-_0' == hello0 ]]
+gitstatus_start_impl:107> add-zsh-hook zshexit _gitstatus_cleanup_13808_0_13890
+add-zsh-hook:15> emulate -L zsh
+add-zsh-hook:17> local -a hooktypes
+add-zsh-hook:18> hooktypes=( chpwd precmd preexec periodic zshaddhistory zshexit zsh_directory_name ) 
+add-zsh-hook:22> local usage='Usage: add-zsh-hook hook function\nValid hooks are:\n  chpwdprecmdpreexecperiodiczshaddhistoryzshexitzsh_directory_name'
+add-zsh-hook:24> local opt
+add-zsh-hook:25> local -a autoopts
+add-zsh-hook:26> integer del list help
+add-zsh-hook:28> getopts dDhLUzk opt
+add-zsh-hook:55> shift 0
+add-zsh-hook:57> ((  list  ))
+add-zsh-hook:60> ((  help || 2 != 2 || 6 == 0  ))
+add-zsh-hook:65> local hook=zshexit_functions
+add-zsh-hook:66> local fn=_gitstatus_cleanup_13808_0_13890
+add-zsh-hook:68> ((  del  ))
+add-zsh-hook:83> ((  0  ))
+add-zsh-hook:89> typeset -ga zshexit_functions
+add-zsh-hook:90> set -A zshexit_functions _gitstatus_cleanup_13808_0_13890
+add-zsh-hook:92> autoload -- _gitstatus_cleanup_13808_0_13890
+gitstatus_start_impl:110> ((  ! stderr_fd  ))
+gitstatus_start_impl:111> unsetopt xtrace
+zsh:1> cd /
+zsh:1> read
+zsh:1> unsetopt bg_nice
+zsh:1> rm -f /tmp/gitstatus.13808.req.1579540229.1649093628.19559 /tmp/gitstatus.13808.resp.1579540229.1649353504.1093 /tmp/gitstatus.13808.lock.1579540229.1646237373.6360
+zsh:1> /usr/bin/setsid /home/ruben.di-battista/.local/bin/zsh -dfxc $'\n        exec >&4\n        echo $$\n        /tmp/gitstatus.jj5qFyPVtc/bin/gitstatusd-linux-x86_64 --lock-fd=3 --parent-pid=13808 --num-threads=16 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --log-level=DEBUG\n        if [[ $? != (0|10) && $? -le 128 && -f /tmp/gitstatus.jj5qFyPVtc/bin/gitstatusd-linux-x86_64-static ]]; then\n          /tmp/gitstatus.jj5qFyPVtc/bin/gitstatusd-linux-x86_64-static --lock-fd=3 --parent-pid=13808 --num-threads=16 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --log-level=DEBUG\n        fi\n        echo -nE $\'bye\\x1f0\\x1e\''
+zsh:3> echo 13890
+zsh:4> /tmp/gitstatus.jj5qFyPVtc/bin/gitstatusd-linux-x86_64 '--lock-fd=3' '--parent-pid=13808' '--num-threads=16' '--max-num-staged=-1' '--max-num-unstaged=-1' '--max-num-conflicted=-1' '--max-num-untracked=-1' '--dirty-max-index-size=-1' '--log-level=DEBUG'
[2020-01-20 18:10:29 00007f37b324f740 INFO src/gitstatus.cc:154] argv[0]: "/tmp/gitstatus.jj5qFyPVtc/bin/gitstatusd-linux-x86_64"
[2020-01-20 18:10:29 00007f37b324f740 INFO src/gitstatus.cc:154] argv[1]: "--lock-fd=3"
[2020-01-20 18:10:29 00007f37b324f740 INFO src/gitstatus.cc:154] argv[2]: "--parent-pid=13808"
[2020-01-20 18:10:29 00007f37b324f740 INFO src/gitstatus.cc:154] argv[3]: "--num-threads=16"
[2020-01-20 18:10:29 00007f37b324f740 INFO src/gitstatus.cc:154] argv[4]: "--max-num-staged=-1"
[2020-01-20 18:10:29 00007f37b324f740 INFO src/gitstatus.cc:154] argv[5]: "--max-num-unstaged=-1"
[2020-01-20 18:10:29 00007f37b324f740 INFO src/gitstatus.cc:154] argv[6]: "--max-num-conflicted=-1"
[2020-01-20 18:10:29 00007f37b324f740 INFO src/gitstatus.cc:154] argv[7]: "--max-num-untracked=-1"
[2020-01-20 18:10:29 00007f37b324f740 INFO src/gitstatus.cc:154] argv[8]: "--dirty-max-index-size=-1"
[2020-01-20 18:10:29 00007f37b324f740 INFO src/gitstatus.cc:154] argv[9]: "--log-level=DEBUG"
[2020-01-20 18:10:29 00007f37b324f740 INFO src/thread_pool.cc:81] Spawning 16 thread(s)
[2020-01-20 18:10:29 00007f37b324f740 INFO src/gitstatus.cc:169] Processing request: "hello" for "":""
[2020-01-20 18:10:29 00007f37b324f740 INFO src/response.cc:69] Replying without git status
[2020-01-20 18:10:29 00007f37b324f740 INFO src/timer.cc:67] Timing for: request: 0.028ms cpu, 0.025178ms wall
[2020-01-20 18:10:29 00007f37b324f740 INFO src/gitstatus.cc:172] Successfully processed request: "hello" for "":""
[2020-01-20 18:10:29 00007f37b324f740 INFO src/gitstatus.cc:169] Processing request: "1579540229.1895668507 " for "/home/ruben.di-battista/git/ParaView/":"" [no-diff]
[2020-01-20 18:10:29 00007f37b324f740 INFO src/repo_cache.cc:124] Initializing new repository: "/users/ruben.di-battista/git/ParaView/.git/"
[2020-01-20 18:10:29 00007f37b1a74700 INFO src/tag_db.cc:188] Parsing "/users/ruben.di-battista/git/ParaView/.git/packed-refs"
[2020-01-20 18:10:29 00007f37b324f740 INFO src/response.cc:69] Replying with git status
[2020-01-20 18:10:29 00007f37b324f740 INFO src/timer.cc:67] Timing for: request: 1.248ms cpu, 1.23082ms wall
[2020-01-20 18:10:29 00007f37b324f740 INFO src/gitstatus.cc:172] Successfully processed request: "1579540229.1895668507 " for "/home/ruben.di-battista/git/ParaView/":"" [no-diff]
[2020-01-20 18:10:30 00007f37b2a76700 INFO src/check_dir_mtime.cc:149] All mtime checks have passes. Enabling untracked cache: "/users/ruben.di-battista/git/ParaView/.git/"
[2020-01-20 18:10:31 00007f37b324f740 INFO src/gitstatus.cc:169] Processing request: "1579540231.1929204464 " for "/home/ruben.di-battista/git/ParaView/":"" [no-diff]
[2020-01-20 18:10:31 00007f37b324f740 INFO src/response.cc:69] Replying with git status
[2020-01-20 18:10:31 00007f37b324f740 INFO src/timer.cc:67] Timing for: request: 0.46ms cpu, 0.386453ms wall
[2020-01-20 18:10:31 00007f37b324f740 INFO src/gitstatus.cc:172] Successfully processed request: "1579540231.1929204464 " for "/home/ruben.di-battista/git/ParaView/":"" [no-diff]
```

**Comment by romkatv** [comment] 2020-01-20 17:16
Sorry, I gave you the wrong command. Please run this one:

```zsh
(
  emulate -L zsh -o err_return -o xtrace -o no_unset
  cd /home/ruben.di-battista/git/ParaView
  git status
  git config -l
  typeset -pm 'POWERLEVEL9K_*|ZSH_VERSION'
  uname -a
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/gitstatus.XXXXXXXXXX)"
  {
    git clone --depth=1 https://github.com/romkatv/gitstatus.git $tmp
    zsh -dfeic "
      GITSTATUS_LOG_LEVEL=DEBUG
      source ${(q)tmp}/gitstatus.plugin.zsh
      gitstatus_start -s -1 -u -1 -c -1 -d -1 -m -1 MY
      gitstatus_query MY
      typeset -m 'VCS_STATUS_*'
      sleep 2
      gitstatus_query MY
      typeset -m 'VCS_STATUS_*'
      cat \$GITSTATUS_XTRACE_MY
      cat \$GITSTATUS_DAEMON_LOG_MY"
  } always {
    rm -rf $tmp
  }
) &>/tmp/p10k.txt
```

Also please post the exact command you've used to clone the ParaView repository.

**Comment by rubendibattista** [comment] 2020-01-20 17:18
```
```

**Comment by romkatv** [comment] 2020-01-20 17:52
Something weird is going on with 2 out of 4 submodules. Not clear what. Let's dig deeper. Please run this and attach `/tmp/p10k.txt` (you can drag-and-drop this file into the edit box):

```zsh
(
  emulate -L zsh -o err_return -o xtrace -o no_unset
  cd /home/ruben.di-battista/git/ParaView
  GIT_CONFIG_NOGLOBAL=1 GIT_CONFIG_NOSYSTEM=1 HOME= XDG_CONFIG_HOME= git config -l
  GIT_CONFIG_NOGLOBAL=1 GIT_CONFIG_NOSYSTEM=1 HOME= XDG_CONFIG_HOME= git status
  GIT_CONFIG_NOGLOBAL=1 GIT_CONFIG_NOSYSTEM=1 HOME= XDG_CONFIG_HOME= git submodule status
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k-debug.XXXXXXXXXX)"
  {
    git clone --depth=1 https://github.com/romkatv/gitstatus.git $tmp/gitstatus
    git clone --recursive https://github.com/Kitware/ParaView.git $tmp/ParaView
    cd $tmp/ParaView
    GIT_CONFIG_NOGLOBAL=1 GIT_CONFIG_NOSYSTEM=1 HOME= XDG_CONFIG_HOME= git config -l
    GIT_CONFIG_NOGLOBAL=1 GIT_CONFIG_NOSYSTEM=1 HOME= XDG_CONFIG_HOME= git status
    GIT_CONFIG_NOGLOBAL=1 GIT_CONFIG_NOSYSTEM=1 HOME= XDG_CONFIG_HOME= git submodule status
    zsh -dfeic "
      GITSTATUS_LOG_LEVEL=DEBUG
      source ${(q)tmp}/gitstatus/gitstatus.plugin.zsh
      gitstatus_start -s -1 -u -1 -c -1 -d -1 -m -1 MY
      gitstatus_query MY
      typeset -m 'VCS_STATUS_*'
      cat \$GITSTATUS_XTRACE_MY
      cat \$GITSTATUS_DAEMON_LOG_MY"
  } always {
    cd /
    rm -rf $tmp
  }
) &>/tmp/p10k.txt
```

**Comment by rubendibattista** [comment] 2020-01-21 14:04
[p10k.txt](https://github.com/romkatv/powerlevel10k/files/4091393/p10k.txt)

**Comment by romkatv** [comment] 2020-01-24 19:21
I think `SYS_getdents64` syscall on your machine returns zero `d_type` for all files. This could happen if your Linux kernel is very old (it is), or if your are using an unusual file system.

It's possible in theory to patch gitstatusd and libgit2 so that it works even on systems like yours, but this is frankly fairly low priority for me. Very few people are brave enough to run ancient Linux kernels that no longer get supported.

**Comment by romkatv** [comment] 2020-01-25 21:29
Closing as wont-fix. I acknowledge this is a bug. The workaround is to use a newer Linux kernel. If you really care about this problem, I'll be receptive to a patch if it doesn't make the code slower on newer kernels. A simple fix shouldn't be too difficult (the code needs a fallback for the case when `d_type` is `DT_UNKNOWN`) but I'm not sure whether it'll have performance implications.

**Closed by romkatv** 2020-01-25 21:29 UTC

**Comment by rubendibattista** [comment] 2020-01-26 00:54
Ehi, thanks for taking the time to go deeply into this. I'm on CentOS7, with the latest update, so I don't know if you consider this an "old" kernel. Moreover I'm on NFS. I'll try to see if on the physical HDD things are different and report back.

Thanks again!

**Comment by romkatv** [comment] 2020-01-26 11:03
> Ehi, thanks for taking the time to go deeply into this. I'm on CentOS7, with the latest update, so I don't know if you consider this an "old" kernel.

If CentOS 7 was a human, it would be finishing high school by now.

> Moreover I'm on NFS.

This may be an important part of it. The kernel by itself isn't old enough to predate the addition of `d_type`. You are hit either by kernel bugs that have since been fixed, or perhaps by having `d_type` disabled on NFS through `ftype=0`. It's possible that 16 years ago, when CentOS 7 was released, disabling `d_type` was the default. I don't know. It's generally a very bad idea to disable `d_type` as it'll cause massive performance penalty and will break things like docker.

**Comment by rubendibattista** [comment] 2020-01-28 00:35
Ok, I just tested on `macOS` and `Ubuntu`, and in both cases the repository is correctly reported as clean. 

I also checked on bare `ext4` filesystem instead of `NFS` on CentOS7 and still the repository is shown "dirty". So probably, as you said, is kernel-related.

**Comment by romkatv** [comment] 2020-01-28 06:30
My bad, I should've written down how I came to the conclusion based on which I've closed the issue.

After reading the original issue description I tried reproducing it on Linux, macOS, FreeBSD, Windows WSL and Windows Cygwin. I saw that ParaView repo has submodules, so I tried cloning it with `--recursive` and without in every test. Couldn't reproduce and asked you to run a command that would give me more diagnostic data.

In the output you posted I saw that your machine has 8 virtual cores while mine has 20, so I thought this might make a difference (the number of cores defines how the repository is sharded, and there were bugs in gitstatusd in the past where status was computed incorrectly for files on the boundaries of shards). I saw that you are using Linux, so I only tested on Linux this time. Couldn't reproduce. Your output indicated a few non-standard git config options that I couldn't easily emulate, so instead I asked you to run a command that would repeat the tests but without reading git config files. That command also cloned ParaView instead of using your existing clone in order to eliminate the possibility that your local ParaView repo has been modified somehow.

When you posted the output, it took me quite some time to unravel it. The first thing I noticed is that something low-level seems broken. After running these commands:

```zsh
git clone --recursive https://github.com/Kitware/ParaView.git $tmp/ParaView
cd $tmp/ParaView
git status
```

The repo came out unclean:

```zsh
Changes not staged for commit:

	modified:   VTK (modified content)
```

At this point I wanted to ask for `git --version` but then realized that it's not `git` that I really need to debug but my own code, which doesn't rely on `git`. Since both my code and `git` exhibit similar kinds of brokenness, there may be a shared underlying reason.

I then compared the log of gitstatusd from your machine with mine, line by line. I noticed this extra line in your output:

```text
[2020-01-21 15:02:53 00007f676bdd5700 DEBUG src/index.cc:156] Dirty candidate (new): ".git"
```

I traced through gitstatusd to see why on my machine this line doesn't get produced despite there obviously being `.git` in my clone of ParaView. The reason is that *directories* named `.git` get skipped by gitstatusd and what is and isn't a directory is determined by `d_name` in the results of `getdents64` syscall. Since gitstatusd invokes the syscall directly without going through glibc (or any other) wrapper, the difference must be in the kernel and/or filesystem.

To verify my hunch I hacked gitstatusd to behave as if `d_name` was zero (a.k.a. `DT_UNKNOWN`). This allowed me to reproduce the issue.

Then I looked at your kernel version (3.10.0-1062.9.1.el7.x86_64) and tried to figure out if `d_name` is supposed to work there. This version is older than 2.6.4, where `d_name` was added to `getdents64`. However, documentation from back then indicates that `d_name` support in filesystems is sketchy. I tried to find out if this kernel version had known bugs related to `d_name`. Found https://bugzilla.redhat.com/show_bug.cgi?id=1248140 but it doesn't seem to apply (not certain).

I checked how old this kernel is. It reached end-of-life in 2017, over 2 years ago. At this point I decided I don't have a moral obligation to fix gitstatusd so that it works on this kernel and closed the issue.

Then later you said you are on CentOS7, which I didn't know before. So I ran one more test.

```zsh
docker run -e LANG=en_US.utf8 -e TERM -it --rm centos:centos7 bash -uexc '
  cd
  yum update -y
  yum install -y git curl make ncurses-devel gcc autoconf man yodl
  git clone https://github.com/zsh-users/zsh.git
  git clone --recursive https://github.com/Kitware/ParaView.git
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
  cd ~/zsh
  git checkout zsh-5.4.1
  ./Util/preconfig
  ./configure
  make -j 20 install.bin install.modules install.fns
  cd ~/ParaView
  echo "
    GITSTATUS_NUM_THREADS=16
    POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
    source ~/powerlevel10k/powerlevel10k.zsh-theme" >~/.zshrc
  exec zsh'
```

This should give me the same userland as you have. I even installed the same version of zsh even thought it doesn't matter. It still uses my kernel and my filesystem though. ParaView repo came out clean in this test, which gave me another confirmation that it's either the kernel or the filesystem that causes issues.

Hopefully it clarifies things.

**Comment by rubendibattista** [comment] 2020-01-28 08:05
Thanks for the informative comment! :)
