### ISSUE TITLE
when not connect to the internet `public_ip` does not load/waiting time is long

### ISSUE THREAD

**Issue by sachinfrayne** [romkatv/powerlevel10k#92] opened 2019-06-21 11:58 UTC
My current workaround:

```
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(custom_ip)
POWERLEVEL9K_CUSTOM_IP="/usr/bin/curl -s ifconfig.co"
POWERLEVEL9K_CUSTOM_IP_BACKGROUND="red"
```

**Comment by sachinfrayne** [comment] 2019-06-21 12:02
whoops, this totally messes up the sizing, :(

**Comment by romkatv** [comment] 2019-06-21 17:53
Thanks for the report. Should be fixed now. Please update and try again (without your workaround). Is it fast enough?

**Comment by sachinfrayne** [comment] 2019-06-24 10:00
Hi,

Getting a different error now but it might be my environment though, I am debugging, ```_p9k_start_async_pump:zsystem:6: failed to lock file /var/folders/wf/28kj8wn91773j4tr15tdf4t80000gn/T//p9k.68789.async.pump.7LoaAudWCb: operation not supporte```

**Comment by sachinfrayne** [comment] 2019-06-24 10:03
Nope, it does not seem to like something, I think it is the double forward slash, `//`

**Comment by romkatv** [comment] 2019-06-24 11:14
It's unlikely that the error is caused by `//`. Could you run the following code and post its output?

```zsh
() {
  emulate -L zsh && setopt xtrace && setopt err_return
  zmodload zsh/system
  uname -a
  local x
  {
    x=$(mktemp ${TMPDIR:-/tmp}/regular.XXXXXXXXXX)
    ( zsystem flock $x )
    rm $x
    x=$(mktemp -u ${TMPDIR:-/tmp}/fifo.XXXXXXXXXX)
    mkfifo $x
    ( zsystem flock $x )
    true
  } always {
    rm -f "$x"
  }
}
```

**Comment by sachinfrayne** [comment] 2019-06-24 11:28
+(anon):1> setopt err_return
+(anon):2> zmodload zsh/system
+(anon):3> uname -a
Darwin Sachins-MBP 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
+(anon):4> local x
+(anon):6> x=+(anon):6> mktemp /var/folders/wf/28kj8wn91773j4tr15tdf4t80000gn/T//regular.XXXXXXXXXX
+(anon):6> x=/var/folders/wf/28kj8wn91773j4tr15tdf4t80000gn/T//regular.EQupFCrGGB
+(anon):7> zsystem flock /var/folders/wf/28kj8wn91773j4tr15tdf4t80000gn/T//regular.EQupFCrGGB
+(anon):8> rm /var/folders/wf/28kj8wn91773j4tr15tdf4t80000gn/T//regular.EQupFCrGGB
+(anon):9> x=+(anon):9> mktemp -u /var/folders/wf/28kj8wn91773j4tr15tdf4t80000gn/T//fifo.XXXXXXXXXX
+(anon):9> x=/var/folders/wf/28kj8wn91773j4tr15tdf4t80000gn/T//fifo.gDEayJSooH
+(anon):10> mkfifo /var/folders/wf/28kj8wn91773j4tr15tdf4t80000gn/T//fifo.gDEayJSooH
+(anon):11> zsystem flock /var/folders/wf/28kj8wn91773j4tr15tdf4t80000gn/T//fifo.gDEayJSooH
(anon):zsystem:11: failed to lock file /var/folders/wf/28kj8wn91773j4tr15tdf4t80000gn/T//fifo.gDEayJSooH: operation not supported
+(anon):14> rm -f /var/folders/wf/28kj8wn91773j4tr15tdf4t80000gn/T//fifo.gDEayJSooH

**Comment by romkatv** [comment] 2019-06-24 11:39
Thanks! Apparently, on BSD it's not possible to flock a fifo.

I've committed a fix. Please update powerlevel10k and try again.

**Comment by sachinfrayne** [comment] 2019-06-24 11:43
That is awesome!

Thank you, 😄.

**Comment by romkatv** [comment] 2019-06-24 11:46
Thanks for the confirmation and for opening the issue in the first place! :1st_place_medal:

**Closed by romkatv** 2019-06-24 11:46 UTC
