### ISSUE TITLE
Reload zshrc after reconfigure

### ISSUE THREAD

**Issue by tasmo** [romkatv/powerlevel10k#206] opened 2019-09-08 06:50 UTC
The configuration wizard should read the variables set in my local `zshrc`.

## What I have

p10k is configured already.

These are the last lines in my `~/.zshrc`:

```shell
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
```

## What I do

Open a new zshell session and reconfigure p10k while executing `p10k configure`.
Make some changes and confirm with "yes".

## What I expect

After finishing I expect that my prompt respects the `POWERLEVEL9K_$` variables from my `zshrc`.
The new prompt should have the same truncated path like the old before.

## What I observe

I get the new prompt configured from the wizard.
My local changes set in my `zshrc` are not respected.
When I source my `zshrc` manually or open a new zshell everything looks perfect.

**Comment by romkatv** [comment] 2019-09-08 16:00
Thanks for the clear description of the issue.

Powerlevel10k configuration wizard indeed doesn't source `~/.zshrc` after writing `~/.p10k.zsh`. The reason is that sourcing `~/.zshrc` can have unpredictable effect. User configs, in general, aren't idempotent, so executing the same configuration code twice may not be equivalent to executing it just once.

Please note the comment that the wizard adds to `~/.zshrc`:

```zsh
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
```

The officially supported way to further customize Powerlevel10k after running the wizard is to edit `~/.p10k.zsh`. If you know what you are doing, you can override/set extra parameters in `~/.zshrc` after sourcing `~/p10k.zsh`, but then you need to face the consequences of walking the unpaved road.

P.S.

If you like your current directory very short, consider replacing your parameters with this:

```zsh
# Shorten all non-anchor directories.
POWERLEVEL9K_DIR_MAX_LENGTH=1
```

There are two differences with your config:

1. Important directories (such as roots of Git repositories) won't get shortened. Which directories are important is controlled by `POWERLEVEL9K_SHORTEN_FOLDER_MARKER`. Search for this parameter in `~/.p10k.zsh` to see what it's set to.
2. Shortening is lossless. You can copy-paste the shortened directory and restore its original value by hitting `TAB`. This means that sometimes a directory is shortened not to 1 but 2 or more characters.

The default value of `POWERLEVEL9K_DIR_MAX_LENGTH` is 80. You might like to set it to something lower but not as low as 1. You can try different values by typing `POWERLEVEL9K_DIR_MAX_LENGTH=40` (for example) in your prompt. All p10k parameters can be changed live without restarting zsh.

**Comment by tasmo** [comment] 2019-09-09 07:43
@romkatv Thank you for explaining what happens! Will the values set in `~/.p10k.zsh` (like in the variable `POWERLEVEL9K_DIR_MAX_LENGTH`) be overwritten when executing `p10k configure` again?

**Comment by romkatv** [comment] 2019-09-09 08:52
> @romkatv Will the values set in `~/.p10k.zsh` (like in the variable `POWERLEVEL9K_DIR_MAX_LENGTH`) be overwritten when executing `p10k configure` again?

Yes. The wizard will override `~/.p10k.zsh` after your confirmation that it's OK to do so.

**Comment by romkatv** [comment] 2019-09-11 06:52
Closing as this is essentially working as intended.

**Closed by romkatv** 2019-09-11 06:52 UTC

**Comment by vvCat-git** [comment] 2023-08-22 04:06
I encountered the same issue. I modified .zshrc to display the full directory, but my changes were reverted when I ran p10k configure. Could you add an option in p10k configure to choose whether to display the full directory? Thank you.

**Comment by romkatv** [comment] 2023-08-22 05:58
@vvCat-git Adding this option will have a cost for everyone running the wizard and will benefit a tiny minority. For rarely used options you need to edit `~/.p10k.zsh` manually.
