### ISSUE TITLE
Terraform Version is not updating

### ISSUE THREAD

**Issue by delaskoff** [romkatv/powerlevel10k#2049] opened 2022-10-07 11:52 UTC
terraform_version is enabled and only 2 settings applied
`typeset -g POWERLEVEL9K_TERRAFORM_VERSION_SHOW_ON_COMMAND='terraform|terragrunt|tfenv'`
`typeset -g POWERLEVEL9K_TERRAFORM_VERSION_FOREGROUND=38
`<img width="1440" alt="Screenshot 2022-10-07 at 14 44 08" src="https://user-images.githubusercontent.com/26123204/194546414-f877b138-37bf-4bd7-85fb-dd6c32657255.png">

**Comment by romkatv** [comment] 2022-10-07 17:07
`terraform_version` segment is supposed to show the output of `terraform --version`. Could you post that?

There is also `terraform` segment. Perchance this would suit you?

**Comment by delaskoff** [comment] 2022-10-08 15:25
I have both `terraform` and `terraform_version` enabled
`terraform --version` is the same as `terraform version`
![Screenshot 2022-10-08 at 18 24 14](https://user-images.githubusercontent.com/26123204/194714995-c8239eb7-1785-4ebe-b3ba-0a9a9fc91ccb.png)

**Comment by DennyLoko** [comment] 2022-10-12 21:01
I have the `terraform` and `terraform_version` segments enabled and I'm having the same issue. These are the settings applied for `terraform_version`:
```
typeset -g POWERLEVEL9K_TERRAFORM_VERSION_FOREGROUND=5
typeset -g POWERLEVEL9K_TERRAFORM_VERSION_VISUAL_IDENTIFIER_EXPANSION=''
```

I noticed the terraform version only updates when the session is started. Worth noticing that I'm using tfenv to manage terraform versions.

**Comment by dou-oscarh** [comment] 2022-12-14 23:03
I can confirm the same behavior with the same settings. So far, the only thing I can do to have the version updated is manually running `source .zshrc`

**Comment by romkatv** [comment] 2022-12-15 08:40
> I can confirm the same behavior with the same settings.

Thanks. There must be a bug in powerlevel10k that causes this. I haven't looked at it yet.

> So far, the only thing I can do to have the version updated is manually running `source .zshrc`

Never run `source .zshrc`. Use `exec zsh` instead.

**Comment by jcgutier** [comment] 2023-04-22 01:52
I found the same issue and I think this is because (not sure how this works) it caching the terraform version:

[prompt_terraform_version](https://github.com/romkatv/powerlevel10k/blob/master/internal/p10k.zsh#L5013-L5020)

I found a discussing here #1622 where it is proposed a cool solution to this. I adopted it to my ~/.p10kzsh  with a little addition to show the segment only on terraform/tfenv commands as follows

```zsh
function prompt_tfenv() {
  if [[ -z $TFENV_TERRAFORM_VERSION ]]; then
    TFENV_TERRAFORM_VERSION=$(tfenv version-name)
  fi

  p10k segment -f 038 -i '' -t "${TFENV_TERRAFORM_VERSION}"
}
typeset -g POWERLEVEL9K_TFENV_SHOW_ON_COMMAND='terraform|tfenv'

function tfenv() {
  command tfenv "$@"

  if [[ "$1" == "use" ]]; then
    export TFENV_TERRAFORM_VERSION=$(tfenv version-name)
  fi
}
```

I think it works great with other plugins like direnv where environmental vars could be loaded per directories. It would be nice to include something similar (probably more efficient) to default p10k config.

**Comment by delaskoff** [comment] 2023-04-29 18:48
What should I modify to disable caching in original `prompt_terraform_version`?

**Comment by romkatv** [comment] 2023-04-29 18:51
Modifying the original `prompt_terraform_version` isn't a great idea. If you want to see the output of `terraform --version` with no caching, define a custom prompt segment. It'll be literally a one-liner.

**Comment by aschleifer** [comment] 2023-08-08 09:17
This also happens when using `tfenv` underneath. 

So for now the workaround is to create a custom prompt `my_terraform_version` which also just runs `terraform --version` but without the caching around it?

**Comment by romkatv** [comment] 2023-10-23 08:44
This is fixed. Please update powerlevel10k and check whether it's working for you now.

**Comment by loic-snauwaert** [comment] 2023-10-23 08:58
> This is fixed. Please update powerlevel10k and check whether it's working for you now.

Working on my side, thanks for the fix!

**Comment by romkatv** [comment] 2023-10-23 08:59
Thanks for verifying! Closing as fixed.

Sorry that it took so long.

**Closed by romkatv** 2023-10-23 08:59 UTC

**Comment by delaskoff** [comment] 2023-10-28 19:39
This one only adds support to read the contents of the `.terraform-version` file but this is not what the issue was intended for.
Let's imagine I use `tfenv` but not aware of `.terraform-version` or I'm using `tfswitch` while relying to such a block:
```hcl
terraform {
  required_version = ">= 0.12.9"
}
```
So it changes nothing. Is there no other way to solve it properly?

**Comment by romkatv** [comment] 2023-10-28 19:44
If you can describe how to reproduce the problem, I might take a look.

**Comment by delaskoff** [comment] 2023-10-28 19:56
The problem is the terraform_version uses the cached value of `terraform --version` and is not updated when you change the binary you're working with. Both `tfenv` and `tfswitch` use symlinks under the hood to substitute the binary required.

**Comment by romkatv** [comment] 2023-10-28 20:13
There are two things that would be useful to me: a clear description how to reproduce the problem or a clean PR that fixes it.

**Comment by kvendingoldo** [comment] 2024-04-03 14:01
btw. you can also use [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management and can do much more, than tfswitch.
