### ISSUE TITLE
when changing directory duplicate is shown

### ISSUE THREAD

**Issue by lenovolobo933** [romkatv/powerlevel10k#1152] opened 2020-12-08 15:35 UTC
when changing directory, the process is shown resulting in a duplication. how to hide the process so that it is more appealing visually, or if it cannot be done, to change both the process(which i have searched through the config file and cannot find) and the current directory(which i have found and modified) to the same color? thanks

please see attached file

![changing directory](https://user-images.githubusercontent.com/45091457/101503798-146ce500-39a5-11eb-811e-66a2654acae5.png)

**Comment by romkatv** [comment] 2020-12-08 18:07
Can you reproduce it if you remove everything from `~/.zshrc` except for powerlevel10k?

**Comment by lenovolobo933** [comment] 2020-12-09 15:54
i think the problem is i have 2 .zshrc files. 1 in root directory and the other in home. should i delete 1 of them and keep only 1?

i have attached both files. please take a look if it does not trouble you too much. thank you
[zshrc-root.txt](https://github.com/romkatv/powerlevel10k/files/5667048/zshrc-root.txt)
[zshrc-home.txt](https://github.com/romkatv/powerlevel10k/files/5667051/zshrc-home.txt)

**Comment by romkatv** [comment] 2020-12-09 16:00
Right now your `~/.zshrc` is loading 3 themes: Pure, Cobalt2 and Powerlevel10k. You should never load more than one theme at a time. To fix this issue,  open `~/.zshrc` (in your home directory) and delete the following lines from it:

```zsh
fpath+=$HOME/.oh-my-zsh/pure
autoload -U promptinit; promptinit
prompt pure

ZSH_THEME="cobalt2"
```

This will disable Pure and Cobalt2 themes. It will keep Powerlevel10k.

**Comment by lenovolobo933** [comment] 2020-12-09 16:06
also, i'm having problems getting the wifispeed to display. i have uncommented the following but they do not seem to be showing up(please see attached screenshot):

typeset -g my_wifi_fg=(68 68 68 68 68)    
typeset -g my_wifi_icon=('WiFi' 'WiFi' 'WiFi' 'WiFi' 'WiFi')
 typeset -g POWERLEVEL9K_WIFI_CONTENT_EXPANSION='%F{${my_wifi_fg[P9K_WIFI_BARS+1]}}$P9K_WIFI_LAST_TX_RATE Mbps'
  typeset -g POWERLEVEL9K_WIFI_VISUAL_IDENTIFIER_EXPANSION='%F{${my_wifi_fg[P9K_WIFI_BARS+1]}}${my_wifi_icon[P9K_WIFI_BARS+1]}'

also i would like to add the following but am not sure they belong to content expansion or visual identifier expansion and whether i should merge them together with the above or create a separate entry:
 
P9K_WIFI_RSSI        
P9K_WIFI_BARS      

please advise. thanks
![wifispeed not displaying](https://user-images.githubusercontent.com/45091457/101654385-0daca380-3a73-11eb-83a4-8bce82a41e1c.png)

**Comment by romkatv** [comment] 2020-12-09 16:13
> also, i'm having problems getting the wifispeed to display

If you are on Linux, you need to install `iw` for this segment to work. On macOS it works out of the box.

> P9K_WIFI_RSSI
> P9K_WIFI_BARS

Please read the comments. If you have a specific question, I'll be happy to answer it.

P.S.

From your screenshot it appears that you've provided incorrect information when you ran `p10k configure`. When it asked you whether all icons fit between the crosses, you've answered No when in fact they did fit between the crosses. Because of this you now have more whitespace in prompt than necessary because powerlevel10k thinks that you font is not monospace.

**Comment by lenovolobo933** [comment] 2020-12-09 16:20
i am not sure if the wifispeed not showing up

> Right now your `~/.zshrc` is loading 3 themes: Pure, Cobalt2 and Powerlevel10k. You should never load more than one theme at a time. To fix this issue, open `~/.zshrc` (in your home directory) and delete the following lines from it:
> 
> ```shell
> fpath+=$HOME/.oh-my-zsh/pure
> autoload -U promptinit; promptinit
> prompt pure
> 
> ZSH_THEME="cobalt2"
> ```
> 
> This will disable Pure and Cobalt2 themes. It will keep Powerlevel10k.

i have edited and saved the file. and then ran the following commands:

source /home/lenovo/.zshrc
source /home/lenovo/.p10k.zsh

the duplicate display is still showing when changing directory. i am using archlinux thanks

**Comment by romkatv** [comment] 2020-12-09 16:21
> i have edited and saved the file. and then ran the following commands:
>
> source /home/lenovo/.zshrc

You should never run this command. It has unpredictable effects. When you want to reload zsh after changing zsh startup files, run this:

```zsh
exec zsh
```

**Comment by lenovolobo933** [comment] 2020-12-09 16:39
thanks. running 

exec zsh fixed the duplicate directory issue

about wifispeed not showing, i already have iw installed. i am not sure how to proceed further to enable wifi related display.

**Comment by romkatv** [comment] 2020-12-09 16:42
> exec zsh fixed the duplicate directory issue

I'm glad.

> about wifispeed not showing, i already have iw installed. i am not sure how to proceed further to enable wifi related display.

What is the output of the following command?

```zsh
ls -l /proc/net/wireless && cat /proc/net/wireless
```

**Comment by lenovolobo933** [comment] 2020-12-09 17:04
ls -l /proc/net/wireless && cat /proc/net/wireless
-r--r--r-- 1 root root 0 Dec 10 00:03 /proc/net/wireless
Inter-| sta-|   Quality        |   Discarded packets               | Missed | WE
 face | tus | link level noise |  nwid  crypt   frag  retry   misc | beacon | 22
 wlan0: 0000   99.   40.    0.       0      0      0      0      0        0

**Comment by romkatv** [comment] 2020-12-09 17:06
What is the output of the following command?

```zsh
command iw dev wlan0 link
```

**Comment by lenovolobo933** [comment] 2020-12-09 17:10
`command` iw dev wlan0 link
Connected to 9a:ff:d0:92:97:c0 (on wlan0)
	SSID: IPMsg HotSpot(Lenovo A369i)
	freq: 2412
	signal: -56 dBm
	tx bitrate: 54.0 `MBit/s`

**Comment by romkatv** [comment] 2020-12-09 17:18
Please post the exact output. What you've posted looks manually edited.

**Comment by lenovolobo933** [comment] 2020-12-10 14:15
iw dev wlan0 link
Connected to 9a:ff:d0:92:97:c0 (on wlan0)
	SSID: IPMsg HotSpot(Lenovo A369i)
	freq: 2412
	signal: -66 dBm
	tx bitrate: 54.0 MBit/s
![iw-dev](https://user-images.githubusercontent.com/45091457/101783368-c387f880-3b2c-11eb-8fc1-74be63536a3b.png)

**Comment by romkatv** [comment] 2020-12-12 08:43
Thanks for the info. Should be fixed now.

**Comment by romkatv** [comment] 2020-12-19 07:47
Closing due to inactivity.

**Closed by romkatv** 2020-12-19 07:47 UTC
