### ISSUE TITLE
Can only use italic and bold italic MesloLGS NF

### ISSUE THREAD

**Issue by Amit-Weiss** [romkatv/powerlevel10k#487] opened 2020-02-11 16:09 UTC
Hello

I have followed the guide to install powerlevel10k, and got it to work. 
My os is macOS Mojave and when I try using MesloLGS NF fonts and the only fonts that are being installed are the Italic and the Bold Italic ones - forcing me to have italic font in my terminal. I'm currently working with iTerm but this issue is not terminal specific - I have also tried the built in terminal and the integrated terminal in VS code.

**What I Tried**
1. Restarting and re-installing the fonts a few times.
2. Installing both manually and via `p10k configure`.
d. Installing only the regular version and the bold version (that did not work - the fonts didn't appear in mac's Font Book after that).
4. Uninstalling the fonts and trying to add them to the font folder explicitly.
5. Playing around with iTerm's settings.
6. Verifying that other fonts do display the entire font family (they do).

If you need any more information in order to help me please let me know.
Thanks,
Amit

**Comment by romkatv** [comment] 2020-02-12 11:28
Interesting. Could you try the following?

1. Start iTerm2 and launch zsh with powerlevel10k in it.
2. Open *iTerm2 → Preferences → Profiles → Text* and set *Font* to `Monaco` (any other font will do as long as it's not Meslo).
3. Run this command:
```zsh
rm ~/Library/Fonts/Meslo*.ttf
```
4. Run this command:
```zsh
p10k configure
```
5. Answer `Yes` when asked whether to install *Meslo Nerd Font*.
6. Once the font is installed, click *iTerm2 → Quit iTerm2* or press *⌘ Q*.
7. Start iTerm2 and launch zsh with powerlevel10k in it.
8. Run this command:
```zsh
p10k configure
```

If everything goes well, you'll be able to answer `Yes` to all wizard's questions about your terminal font's capabilities. You should also see `Meslo` in Font Book.

Please let me know whether it works for you. If it doesn't, describe where things go wrong.

**Comment by Amit-Weiss** [comment] 2020-02-12 12:49
Hi @romkatv 

Thank you for the speedy response.

I followed your instructions and was able to perform stages 1 through 7. When I did, again the only fonts installed were the italic and italic bold:
![image](https://user-images.githubusercontent.com/23521723/74336365-c8620b80-4da6-11ea-9ae8-2fffb21067e9.png)

**Comment by romkatv** [comment] 2020-02-12 13:04
> I followed your instructions and was able to perform stages 1 through 7.

Have you tried continuing to step 8? What was the result?

What is the output of the following command?

```zsh
ls -l /System/Library/Fonts/Meslo*(N) ~/Library/Fonts/Meslo*
```

Could you post a screenshot of Font Book where *All Fonts* is selected on the left and *MesloLGS NF* is expanded on the right? Like this:

![fontbook](https://user-images.githubusercontent.com/1282067/74337433-9057ca00-4da0-11ea-8c25-29ef0a1268cd.png)

P.S.

I see that you've changed several settings in iTerm2 that will negatively affect your zsh experience. It's better to revert them.

- Uncheck *Use a different font for non-ASCII text*.
- Uncheck *Use built-in Powerline glyphs*.

**Comment by Amit-Weiss** [comment] 2020-02-12 13:17
- Since stage 8 requires me to go through the config again - I saw no use for it, Meslo Regular wasn't available to use from the iTerm settings. I did try it now, but after restart Monaco is still the loaded font and the disables me from answering 'Yes' to the wizard's questions

- The output of `ls -l /System/Library/Fonts/Meslo*(N) ~/Library/Fonts/Meslo*` is:
![image](https://user-images.githubusercontent.com/23521723/74338433-d2860900-4daa-11ea-91f4-dfaf69a295e7.png)

- Here is a screenshot of the font book:
![image](https://user-images.githubusercontent.com/23521723/74338051-280de600-4daa-11ea-9586-74a0cb28821a.png)

- Thank you for your suggestions regarding iTerm. This is because I tried to play with stuff thinking it might help the font to appear.

**Comment by romkatv** [comment] 2020-02-12 13:34
Try the following:

1. Start iTerm2 and launch zsh with powerlevel10k in it.
2. Open *iTerm2 → Preferences → Profiles → Text* and set *Font* to `Monaco`.
3. Run this command:
```zsh
rm ~/Library/Fonts/Meslo*.ttf
```
4. Remove font cache (commands copied [from this article](https://support.quark.com/en/support/solutions/articles/19000057216-how-to-clear-font-caches-on-mac-)).
```zsh
sudo atsutil databases -remove
atsutil server -shutdown
atsutil server -ping
```
5. Reboot.
6. Start iTerm2 and launch zsh with powerlevel10k in it.
7. Run this command:
```zsh
p10k configure
```
8. Answer `Yes` when asked whether to install *Meslo Nerd Font*.
9. Once the font is installed, click *iTerm2 → Quit iTerm2* or press *⌘ Q*.
10. Start iTerm2 and launch zsh with powerlevel10k in it.
11. Run this command:
```zsh
p10k configure
```

If this doesn't help, type `open ~/Library/Fonts`, right click `MesloLGS NF Regular.ttf` and select *Get Info*. Is there anything that suggests why this font isn't working?

If nothing explains why the font doesn't work, double-click on `MesloLGS NF Regular.ttf` and click *Install*. What happens?

Do you have any ideas why you might be experiencing this issue? There are on the order of 100k users of this font on macOS and your bug report is the first of its kind. If you can guess what makes your setup unique, this would help a lot.

**Comment by Amit-Weiss** [comment] 2020-02-12 13:56
@romkatv First of all thank you again for help. It is not trivial to get answers so fast with such detail.

Unfortunately, my problem persists. I followed the steps described and after restarting iTerm now the only font that appears is `MesloLGS NF Bold Italic`.
Following your advice, I took a closer look at the font's info and nothing seems to be out of order. I tried installing like before, but still even though it seems like the installation went well, the font doesn't appear afterwards.

The only problem I can think of with this font is during installation, when validating the font I get:
<img width="988" alt="Screen Shot 2020-02-12 at 15 51 16" src="https://user-images.githubusercontent.com/23521723/74341201-f4ce5580-4daf-11ea-906a-11c74255b7c9.png">

I have no other ideas, sorry. Other fonts seems to work well.
I'd also appreciate if you can suggest an alternative for the font.

**Comment by romkatv** [comment] 2020-02-12 14:07
> The only problem I can think of with this font is during installation, when validating the font I get:
> <img alt="Screen Shot 2020-02-12 at 15 51 16" width="988" src="https://user-images.githubusercontent.com/23521723/74341201-f4ce5580-4daf-11ea-906a-11c74255b7c9.png">

Wow, this is very surprising. The long name shown on your screenshot is the old name. The latest version found [here](https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf) has a different (shorter) name.

Can you try removing all Meso fonts again, dowloading the file I linked to above and trying to install it? Does it give you the same warning?

> I'd also appreciate if you can suggest an alternative for the font.

You can use any font. The recommended font is simply a font that is proven to work everywhere (apparently not anymore). You can use system fonts such as *SF Mono*, *Menlo* or *Monaco*. You can also download patched fonts from https://github.com/ryanoasis/nerd-fonts. If you go with Nerd Fonts (the best choice), it's a good idea to stick with monospace font variants. For example: [Hack Regular Nerd Font Complete Mono.ttf](https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete%20Mono.ttf).

**Comment by romkatv** [comment] 2020-02-12 14:08
Oh, I just noticed you also get a warning for "Duplicate fonts". This must be the culprit. What does it say if you try to get details?

**Comment by romkatv** [comment] 2020-02-12 14:12
You can also try installing the font from Font Book rather than by clicking on `*.ttf`. Here's an article I found: https://support.apple.com/guide/font-book/install-and-validate-fonts-fntbk1000/mac. It also mentions the duplicate fonts prompt and what to do about it.

**Comment by Amit-Weiss** [comment] 2020-02-12 14:32
It worked!

After using the latest version you supplied I was able to install the font and use it in iTerm!
I'm still unable to install the regular bold font and also the italic non-bold one, guess their versions are old as well (if you have the latest versions for these two I'd be happy to get them too).

Now for some debugging for the future:
1. The fonts I originally downloaded were from the following section in the Readme.md: 
https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k
For some reason the download via the wizard didn't work as well - maybe it also supplies an older version?

2. I tried installing both from Font Book and by clicking on `.ttf` files. So this is not likely to be the source of the issue.

3. The latest version of the regular font also gave me a "Duplicate fonts" warning, I guess this is also not the issue.

Thanks again for your help!

**Comment by romkatv** [comment] 2020-02-12 14:38
The links at https://github.com/romkatv/powerlevel10k/blob/master/README.md#manual-font-installation point to the latest versions of all font variants. Maybe try removing all Meslo fonts, downloading them again and installing?

FWIW, `p10k configure` downloads the same files from the same place.

> 3. The latest version of the regular font also gave me a "Duplicate fonts" warning, I guess this is also not the issue.

What does it say? Could you click on the warning to see the message?

**Comment by Amit-Weiss** [comment] 2020-02-12 14:42
> What does it say? Could you click on the warning to see the message?

Sure:
![image](https://user-images.githubusercontent.com/23521723/74345170-5396cd80-4db6-11ea-86f9-3a0f7a67dcbe.png)

**Comment by romkatv** [comment] 2020-02-12 14:43
What does it say when you highlight "Duplicate fonts"?

**Comment by Amit-Weiss** [comment] 2020-02-12 14:45
It doesn't change anything. The same text is displayed.

**Comment by romkatv** [comment] 2020-02-12 14:47
So it says this font is a dup of some other font but doesn't say what that other font is?

If you install this font and then click on *Validate* in Font Book, does it also say it's duplicate? Does it give you more details and/or offer to take action w.r.t. the dup?

Basically, it's not normal that Font Book says the font is a duplicate if you don't believe it's a duplicate. Would be nice to figure out what's going on.

**Comment by Amit-Weiss** [comment] 2020-02-12 14:53
> So it says this font is a dup of some other font but doesn't say what that other font is?

Not as far as I could observe. Just the message in my earlier comment

> If you install this font and then click on Validate in Font Book, does it also say it's duplicate?

Yes, it shows the same message

>  Does it give you more details and/or offer to take action w.r.t. the dup?

No, it doesn't give any other information.

> Basically, it's not normal that Font Book says the font is a duplicate if you don't believe it's a 
duplicate. Would be nice to figure out what's going on.

I agree. Another weird behavior I observed - for each font that went through the installation process but wasn't in the Font Book afterwards, changing its name (from `MesloLGS NF Regular` to `MesloLGS NF Regular (1)`, for example) solved the issue and made the font appear in the book.

**Comment by romkatv** [comment] 2020-02-12 15:02
I think the problem is that you have `MesloLGS NF Regular` somehow installed when it appears that you don't. That installed version is somehow broken, so you cannot use it. Unfortunately, it's preventing you front installing a working font with the same name.

I would try to figure out where that broken font is coming from. Remove all files with `Meslo` in their names from `/Library/Fonts`, `~/Library/Fonts` and `/System/Library/Fonts` and reboot. If you now download `MesloLGS NF Regular.ttf` and click on it (while it's still in the Downloads folder), it shouldn't say that the font is a duplicate. If it does, try to debug why. I don't own a mac, so you are in a better position to do this.

**Comment by Amit-Weiss** [comment] 2020-02-12 15:46
I took a look and wasn't able to solve this stuff, the duplicate warning kept appearing regardless of what I deleted and re-installed. 
I'll continue to investigate it on my own, but since my problem is fixed now feel free to close the issue.
Thanks

**Comment by romkatv** [comment] 2020-02-12 15:50
Alright, let's close this issue. If you get any new information, please post an update.

**Closed by romkatv** 2020-02-12 15:50 UTC

**Comment by romkatv** [comment] 2020-02-12 16:04
Found some extra info about font locations on macOS: https://support.apple.com/en-us/HT201722. Maybe it'll help.

**Comment by irshadmpm** [comment] 2020-02-20 08:23
I also faced the same issue. Only the Bold Italic variant of the font was showing in iTerm2 Preferences.

In the Font Book, I right clicked on the MesloLGS NF font and then clicked on **Show in Finder**. In Finder, it was showing the other three variants as well even though they were not visible in the Font Book! I deleted all four of them from the Finder window. Then installed the fonts again from Font Book. This time there were no duplicate errors and I was able to see all four font variants in iTerm2 Preferences.

**Comment by romkatv** [comment] 2020-02-20 08:26
@irshadmpm Thanks for the info!

Do you remember the location in Finder where you deleted these files? Which folder was it?

How did you install MesloLGS fonts? Did you use the configuration wizard to do it? Did you download the fonts from powerlevel10k and manually installed them? Did you ever download/install fonts from Nerd Fonts?

**Comment by irshadmpm** [comment] 2020-02-20 09:32
@romkatv 
The font install location is ~/Library/Fonts/

I had some customisation done to my terminal previously. I had installed fonts from https://github.com/powerline/fonts as part of the customisation. So that might be the cause of the issue.

I downloaded the font from powerlevel10k and manually installed them as I was trying many things to fix this issue. But I believe installing the fonts during the configuration wizard should also work fine if I didn't have the previous installation from the powerline fonts.

**Comment by romkatv** [comment] 2020-02-20 09:37
The files that you've deleted from `~/Library/Fonts/` had very long names, right? Now the short `MesloLGS NF Regular.ttf` like in the files you download from powerlevel10k.

It appears that @Amit-Weiss might have had (still has?) a different issue. His problem wasn't solved by running `rm ~/Library/Fonts/Meslo*.ttf`. Or maybe those rogue fonts didn't have names that start with `Meslo`?

**Comment by irshadmpm** [comment] 2020-02-20 09:53
Yes, it is possible that @Amit-Weiss might be having a different issue. My problem would have been fixed by running `rm ~/Library/Fonts/Meslo*.ttf`

**Comment by Amit-Weiss** [comment] 2020-02-23 13:14
Indeed, it seems like my problem was different. Just to verify, I tried following the instructions of @irshadmpm and still got the same duplicated fonts message as before. 
As I've said in the past - it doesn't bother me anymore since now I do have all the fonts installed (despite the duplicate warning).

**Comment by liby** [comment] 2020-05-09 18:54
> You can use any font. The recommended font is simply a font that is proven to work everywhere (apparently not anymore). You can use system fonts such as SF Mono, Menlo or Monaco. You can also download patched fonts from https://github.com/ryanoasis/nerd-fonts. If you go with Nerd Fonts (the best choice), it's a good idea to stick with monospace font variants. For example: Hack Regular Nerd Font Complete Mono.ttf.

I just happened to browse this issue and saw this place and I was confused.
1. Q1
   Why 'MesloLGS NF' is recommended instead of 'MesloLGS Nerd Font Mono'?
   Or to put it another way: why not choose mono, why not LGS, LGL?
2. Q2
   How is the font downloaded from [nerd-fonts](https://github.com/ryanoasis/nerd-fonts) different from the one installed via the `p10k configure` command?

For the second question, through my observations, two differences were discovered:
  1. They show different names in the font book.
      ![DiffName](https://user-images.githubusercontent.com/38807139/81482326-ce15a300-9268-11ea-9300-4c7c84961ec7.png)
  2. Problems with fonts downloaded from nerd-fonts.
      ![Problems](https://user-images.githubusercontent.com/38807139/81482377-22208780-9269-11ea-82c6-ae77faa9da45.png)

Of course, this is only a superficial phenomenon, but I'd still like to hear your answer.
I look forward to hearing from you!

**Comment by romkatv** [comment] 2020-05-09 19:03
> 1. Q1
>    Why 'MesloLGS NF' is recommended instead of 'MesloLGS Nerd Font Mono'?

MesloLGS NF is MesloLGS Nerd Font Mono with a bunch of fixes. See https://github.com/romkatv/powerlevel10k/#how-was-the-recommended-font-created. You can look at the https://github.com/romkatv/nerd-fonts for the fixes. Here's a summary:

- Block elements are proper size (they are broken in Nerd Fonts).
- All icons are 44% larger by area and still don't cause overlap without any padding.
- Powerline glyph alignment is better.

>  not LGL?

It leaves gap between lines. Looks awful. Box-drawing characters and block elements don't connect, etc.

> 2. Q2
>    How is the font downloaded from [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts) different from the one installed via the `p10k configure` command?

The one installed via `p10k configure` is MesloLGS NF. So it's the same questions as the first.

**Comment by liby** [comment] 2020-05-10 04:59
Thanks for the reply, I get it now. @romkatv

**Comment by stuart-warren** [comment] 2020-11-12 08:49
I think I had similar issues if I used Alacritty (terminal app) which was already pre-configured to use the fonts to download them. If I closed Alacritty removed the fonts and ran the following in regular MacOS Terminal they all seemed to install fine 😕 
```sh
curl -fLo "${HOME}/Library/Fonts/MesloLGS-NF-Regular.ttf" --create-dirs https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
curl -fLo "${HOME}/Library/Fonts/MesloLGS-NF-Bold.ttf" --create-dirs https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
curl -fLo "${HOME}/Library/Fonts/MesloLGS-NF-Italic.ttf" --create-dirs https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
curl -fLo "${HOME}/Library/Fonts/MesloLGS-NF-Bold-Italic.ttf" --create-dirs https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
```

**Comment by romkatv** [comment] 2020-11-12 08:58
> I think I had similar issues

Please describe the issues.

> if I used Alacritty (terminal app) which was already pre-configured to use the fonts to download them.

What does this mean? How can I reproduce this?

> If I closed Alacritty removed the fonts [...]

Which fonts? Removed how?

**Comment by stuart-warren** [comment] 2020-11-12 09:48
The issue for me appeared to be downloading the MesloLGS fonts into the `~/Library/Fonts` directory whilst having an application open trying to use those fonts, seemed to stop the fonts from being installed to Font Book and actually useable.

It was very odd and threw me for a good hour

The whole reason this came about was I have a replacement laptop and had migrated old configuration files for [Alacritty](https://github.com/alacritty/alacritty) over already but was missing the font files, but it seemed to affect MacOS Font Book from seeing them

**Comment by romkatv** [comment] 2020-11-12 09:50
> The issue for me appeared to be downloading the MesloLGS fonts into the `~/Library/Fonts` directory whilst having an application open trying to use those fonts, seemed to stop the fonts from being installed to Font Book and actually useable.

Could you provide more details? Did you have MesloLGS NF fonts installed? Where were they installed? Where did they come from?

If you can provide instructions how to reproduce, that would be absolutely best.

**Comment by stuart-warren** [comment] 2020-11-12 11:04
My initial comment was only meant as a hint to anyone else who ran into this, if this doesn't actually repo the issue I'm not too fussed about it now.

1. Don't have MesloLGS fonts installed
2. Install Alacritty
3. Start Alacritty copy over old configuration for .zshrc, .config/alacritty (with font info specifying MesloLGS fonts), .oh-my-zsh, .p10k.zsh, tmux.conf, etc
4. Restart Alacritty
5. Notice fonts don't look quite right (missing icons)
6. Download fonts using Alacritty 
```sh
curl -fLo "${HOME}/Library/Fonts/MesloLGS-NF-Regular.ttf" --create-dirs https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
curl -fLo "${HOME}/Library/Fonts/MesloLGS-NF-Bold.ttf" --create-dirs https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
curl -fLo "${HOME}/Library/Fonts/MesloLGS-NF-Italic.ttf" --create-dirs https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
curl -fLo "${HOME}/Library/Fonts/MesloLGS-NF-Bold-Italic.ttf" --create-dirs https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
```
7. Notice fonts still don't look right
8. Open MacOS font book and see that only 2 of the 4 fonts are showing
---
9. Delete fonts from ~/Library/Fonts
10. Close Alacritty
11. Open MacOS Terminal
12. Rerun curl commands to download fonts again
13. Open MacOS font book and see that all of the 4 fonts are showing

**Comment by romkatv** [comment] 2020-11-12 11:07
@stuart-warren Thanks! This should be enough for me to try to reproduce this.

**Comment by eddyg** [comment] 2020-11-12 11:47
Reminder about [this macOS bug](https://github.com/romkatv/powerlevel10k/issues/525#issuecomment-591484395) when you download directly to a Fonts directory, in case it applies.

**Comment by romkatv** [comment] 2020-11-12 11:53
> Reminder about [this macOS bug](https://github.com/romkatv/powerlevel10k/issues/525#issuecomment-591484395) when you download directly to a Fonts directory, in case it applies.

Good point. This might be the same bug indeed. `p10k configure` already has a workaround, so if the font is installed by p10k, everything would work fine. It's only when users install fonts manually that they trigger the bug in macOS.

**Comment by shrekuu** [comment] 2023-03-04 13:55
<img width="707" alt="image" src="https://user-images.githubusercontent.com/3136026/222906267-d59174cf-68d8-4aa0-8a5a-c462d74df110.png">

Sorry I'am late. I found out the solution: 
Remove this font previously installed. You select all 4 files and open with fontbook, and click install. This helps to install 4 font files at once and it appears in the font list of every application.
