### ISSUE TITLE
Instant prompt output error only in tmux

### ISSUE THREAD

**Issue by stepanzak** [romkatv/powerlevel10k#2299] opened 2023-05-08 21:19 UTC
Hi, first of all, thanks for this amazing prompt!
I recently started using tmux and I noticed something weird.
When I start tmux, even with no config and no plugins, I get this error:

`[WARNING]: Console output during zsh initialization detected.`
Then long instructions follow and at the end, this:
```
-- console output produced during zsh initialization follows --

╭─░▒▓    ~ ············································································································· ✔  23:04:09  ▓▒░
╰─
```
There's just one newline, but I don't know if that is part of the error or the console output.

This happens only in tmux and when I run `exec zsh` or `zsh` after that, no error occurs.
When I create a new tmux window or pane, new error happens there.
Sometimes, it doesn't happen when I start tmux but alway when I create new window or pane.

At first, I thought it's caused by some of my tmux plugins, but it happens even with the default tmux config on my pc.
On my Android phone with Termux, it doesn't happen, even though I have the same dotfiles here.
It cannot be caused by my terminal, it happens in konsole and wezterm.

Thank you for any help or at least pointing me to where can this error come from.

**Comment by romkatv** [comment] 2023-05-09 08:54
Does it happen if you remove everything from .zshrc except for powerlevel10k? Basically, your .zshrc should look like this:

```zsh
source ~/.p10k.zsh
source /path/to/powerlevel10k.zsh-theme
```

**Comment by stepanzak** [comment] 2023-05-09 17:56
I did some testing and in Arch Linux or Ubuntu docker container, this issue is not present.
I created a new user on my pc and did a clean manual install of p10k here. The issue was exactly the same.
I installed OS I'm running (EndeavourOS based on Arch) in a virtual machine and the issue was not there.
Therefore I assume it's something with my system, but I have no clue what can it be.
I am not able to reproduce it anywhere else than on my system, so I'm closing this issue as Can't repro.

**Comment by romkatv** [comment] 2023-05-09 17:59
Alright. Could you answer my question though? I'm curious.

**Comment by stepanzak** [comment] 2023-05-09 18:07
Sure.
When I put only these two lines in my .zshrc and start tmux, nothing special happens.
See the screenshot:
![Screenshot_20230509_200613](https://github.com/romkatv/powerlevel10k/assets/99094176/423f2b21-c871-4e76-aa9d-663d2ed18157)

**Comment by romkatv** [comment] 2023-05-09 18:08
So the error cannot be reproduced when your zsh config enabled just powerlevel10k? This suggest that something else in your zsh config is necessary for the error to trigger. You can try finding out what that is by enabling things one by one.

**Comment by stepanzak** [comment] 2023-05-09 18:13
When I add the instant prompt code it causes the error.
![Screenshot_20230509_201205](https://github.com/romkatv/powerlevel10k/assets/99094176/00264337-c400-404d-a3fa-6b0f858b9ddf)

**Comment by romkatv** [comment] 2023-05-09 18:17
That's nice! The next thing to check is the other rc files. You can do it with this command:

```zsh
zsh --sourcetrace -lic ''
```

If this shows any rc files in your home directory, delete them. If the error still reproduces after this, create `~/.zshenv` with this content:

```zsh
setopt no_global_rcs
```

Does the error reproduce then?

**Comment by romkatv** [comment] 2023-05-09 20:13
It's not a bug in wezterm, so no need to report this. I'll take a look at the file you linked tomorrow or later in the week.

**Comment by stepanzak** [comment] 2023-05-09 20:16
Oh, ok.
I thought it was a bug, but luckily I didn't submit the issue yet.

**Comment by stepanzak** [comment] 2023-05-09 20:25
One last thing I forgot to write is that I have tried it with GNU Screen and Zellij and the error was only in Tmux.
Hope that helps.

**Comment by romkatv** [comment] 2023-05-09 21:56
OK, I see what's going on in there. Will fix later this week.

P.S.

`wezterm.sh` makes your prompt significantly slower. `vte.sh` does too. If you don't need all that stuff, keep `setopt no_global_rcs` in `~/.zshenv`.

**Comment by romkatv** [comment] 2023-05-10 07:26
Should be fixed now. Please update powerlevel10k and verify.

**Comment by romkatv** [comment] 2023-05-10 08:24
Thanks for reporting, assisting in debugging end verifying!

**Closed by romkatv** 2023-05-10 08:24 UTC

**Comment by stepanzak** [comment] 2024-01-30 21:03
Hi, the exact same thing happened today again. And removing `/etc/profile.d/wezterm.sh`  fixed it again. I don't know if it's the exact same issue, but it looks like it is.

**Comment by romkatv** [comment] 2024-01-30 21:15
> I don't know if it's the exact same issue, but it looks like it is.

If it's the same issue, please use the same resolution. If that does not work, it's not the same issue, so please open a new issue.
