### ISSUE TITLE
_p9k_cache_set:3: no such file or directory: /tmp/p9k_cache_channel.71778

### ISSUE THREAD

**Issue by gregf** [romkatv/powerlevel10k#2] opened 2019-03-03 02:46 UTC
I get the following error printed several times when starting  up powerlevel10k with zplug.

```
_p9k_cache_set:3: no such file or directory: /tmp/p9k_cache_channel.71778
_p9k_cache_set:3: no such file or directory: /tmp/p9k_cache_channel.71778
_p9k_cache_set:3: no such file or directory: /tmp/p9k_cache_channel.71778
_p9k_cache_set:3: no such file or directory: /tmp/p9k_cache_channel.71778
_p9k_cache_set:3: no such file or directory: /tmp/p9k_cache_channel.71778
_p9k_cache_set:3: no such file or directory: /tmp/p9k_cache_channel.71778
_p9k_cache_set:3: no such file or directory: /tmp/p9k_cache_channel.71778
```

OS: FreeBSD 12.0
ZSH: zsh 5.7.1 (amd64-portbld-freebsd12.0)

**Comment by SultanSGillani** [comment] 2019-03-03 16:52
Getting the same here and I’m in Arch

**Comment by Perry3D** [comment] 2019-03-03 17:41
> Getting the same here and I’m on Arch
Also on Arch and prezto. No problems with powerlevel9k.
I think it worked with oh-my-zsh.

**Comment by romkatv** [comment] 2019-03-03 23:59
@gregf I don't have access to FreeBSD unfortunately but I've tried it with zplug on Ubuntu and didn't see any errors. Here's what did:

```zsh
docker run -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 -e TERM=$TERM -it --rm ubuntu bash -c '
  set -uex
  apt update
  apt install -y zsh git gawk
  git clone https://github.com/zplug/zplug ~/.zplug
  echo "
    source ~/.zplug/init.zsh &&
    zplug romkatv/gitstatus, use:gitstatus.plugin.zsh &&
    zplug romkatv/powerlevel10k, use:powerlevel10k.zsh-theme &&
    zplug check || zplug install &&
    zplug load --verbose" >~/.zshrc
  zsh -i
'
```

Is there a crucial difference from your setup?

**Comment by romkatv** [comment] 2019-03-04 00:01
@SultanSGillani I wasn't able to reproduce this on Arch with zplug. Here's what I did:

```
docker run -e LANG=en_US.utf8 -e LC_ALL=en_US.utf8 -e TERM=$TERM -it --rm archlinux/base bash -c '
  set -uex
  pacman -Sy --noconfirm zsh git gawk
  git clone https://github.com/zplug/zplug ~/.zplug
  echo "
    source ~/.zplug/init.zsh &&
    zplug romkatv/gitstatus, use:gitstatus.plugin.zsh &&
    zplug romkatv/powerlevel10k, use:powerlevel10k.zsh-theme &&
    zplug check || zplug install &&
    zplug load --verbose" >~/.zshrc
  zsh -i
'
```

What's different from your setup?

**Comment by SultanSGillani** [comment] 2019-03-04 00:04
Me specifically I’m on Arch and use zplugin. I used a normal zplugin light ‘your repo goes here’

I do have some extra powerlevel customizations but nothing else. 

Here is a link to them: https://github.com/SultanSGillani/dotfiles/blob/master/roles/zsh/themes/powerlevel9k.zsh
I have since switched back to powerlevel9k so my current config will not show that I’m using yours.

**Comment by SultanSGillani** [comment] 2019-03-04 00:05
I use ansible Here is my zplugin template: https://github.com/SultanSGillani/dotfiles/blob/master/roles/zsh/templates/zplugin.j2
Swap powerlevel10k for powerlevel9k and I started receiving the errors.

**Comment by romkatv** [comment] 2019-03-04 00:13
Thanks everyone. I managed to reproduce this. Debugging now...

**Comment by romkatv** [comment] 2019-03-04 00:24
Should be fixed now. Please try it.

P.S.

I've also verified that gitstatus works with zplug. Simply add this to your config for extra performance boost:

```
zplug romkatv/gitstatus, use:gitstatus.plugin.zsh
```

I ran out of patience trying to figure out how to enable a custom plugin on prezto. Can anyone post instructions? I'd like to check that gitstatus works with prezto too.

**Comment by gregf** [comment] 2019-03-04 01:31
@romkatv 

powerlevel10k is now fixed. gitstatus however is leaving files behind in my $HOME directory.

```
gitstatus.88296.pipe.8GsbzJGV05

```

Like this.

**Comment by SultanSGillani** [comment] 2019-03-04 06:07
Getting something similar as above:
https://github.com/romkatv/gitstatus/issues/2

**Comment by romkatv** [comment] 2019-03-04 09:31
> Getting something similar as above:
> romkatv/gitstatus#2

I added a comment to romkatv/gitstatus#2.

Closing this issue as I believe it's now fixed. Please reopen if you still see errors.

**Closed by romkatv** 2019-03-04 09:31 UTC
