### ISSUE TITLE
Battery high threshold

### ISSUE THREAD

**Issue by horseinthesky** [romkatv/powerlevel10k#454] opened 2020-02-02 18:28 UTC
From playing with `p10k configure` I've stopped on the following configuration of battery:
```
# Show battery in red when it's below this level and not connected to power supply.
typeset -g POWERLEVEL9K_BATTERY_LOW_THRESHOLD=20
typeset -g POWERLEVEL9K_BATTERY_LOW_FOREGROUND=red
# Show battery in green when it's charging.
typeset -g POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND=green
# Show battery in blue when not connected to power supply.
typeset -g POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND=blue
# Show battery in green when fully charged.
typeset -g POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND=green
# Battery pictograms going from low to high level of charge.
typeset -g POWERLEVEL9K_BATTERY_STAGES=$'\uf579\uf579\uf57a\uf57b\uf57c\uf57d\uf57e\uf57f\uf580\uf581\uf578'
# Pictogram to show when the battery is fully charged and connected to power supply.
typeset -g POWERLEVEL9K_BATTERY_CHARGED_VISUAL_IDENTIFIER_EXPANSION=$'\uf584'
# Don't show the remaining time to charge/discharge.
typeset -g POWERLEVEL9K_BATTERY_VERBOSE=false
```

Is there a way to have the following behavior in terms of color?:
Chaged/charging - green
Disconnected high - green
Disconnected average - yellow
Disconnected low - red

I've played with p10k configure and there is a `LOW_THRESHOLD` level but no `HIGH_THRESHOLD`.

**Comment by romkatv** [comment] 2020-02-02 18:37
Try this:

```zsh
# Show battery in green when it's charging or fully charged.
typeset -g POWERLEVEL9K_BATTERY_{CHARGING,CHARGED}_FOREGROUND=green
# Battery colors for different levels of charge when disconnected.
typeset -g POWERLEVEL9K_BATTERY_LEVEL_FOREGROUND=(
  red red yellow yellow yellow yellow yellow green green green)
# Battery pictograms going from low to high level of charge.
typeset -g POWERLEVEL9K_BATTERY_STAGES=$'\uf579\uf579\uf57a\uf57b\uf57c\uf57d\uf57e\uf57f\uf580\uf581\uf578'
# Pictogram to show when the battery is fully charged and connected to power supply.
typeset -g POWERLEVEL9K_BATTERY_CHARGED_VISUAL_IDENTIFIER_EXPANSION=$'\uf584'
# Don't show the remaining time to charge/discharge.
typeset -g POWERLEVEL9K_BATTERY_VERBOSE=false
```

`POWERLEVEL9K_BATTERY_LEVEL_FOREGROUND` works similarly to `POWERLEVEL9K_BATTERY_STAGES`. Colors defined for specific states (e.g., `POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND`) take precedence over `POWERLEVEL9K_BATTERY_LEVEL_FOREGROUND`.

**Comment by horseinthesky** [comment] 2020-02-02 18:56
Is there `CHARGING_STAGES` icons array?

**Comment by romkatv** [comment] 2020-02-02 19:04
No. If you explain what you want to achieve, I'll suggest how.

Does the config do what you wanted? If not, what do you want to work different?

**Comment by horseinthesky** [comment] 2020-02-02 19:08
Yes, it does exactly what I wanted. Thank you.

We have `POWERLEVEL9K_BATTERY_CHARGED_VISUAL_IDENTIFIER_EXPANSION` special icon for full charge and battery connected.
I wonder if it is possible to show charging stages icons similar to disconnected stages just to make even more awesome? =)

**Comment by romkatv** [comment] 2020-02-02 19:16
You want multiple icons for `CHARGING` and multiple **different** icons for `DISCONNECTED`? Is that correct?

**Comment by horseinthesky** [comment] 2020-02-02 19:17
Yes.

**Comment by romkatv** [comment] 2020-02-02 19:19
Got it. Not possible at the moment but easy to add. I'll implement it when I get to my dev station.

**Comment by romkatv** [comment] 2020-02-03 06:55
> Got it. Not possible at the moment but easy to add. I'll implement it when I get to my dev station.

This is done. When `battery` is in state `${state}`, the icon is picked from the first defined parameter in the following order:

1. `POWERLEVEL9K_BATTERY_${state}_STAGES`.
2. `POWERLEVEL9K_BATTERY_STAGES`.
3. `POWERLEVEL9K_BATTERY_${state}_BATTERY_ICON`.
4. `POWERLEVEL9K_BATTERY_BATTERY_ICON`.
5. `POWERLEVEL9K_BATTERY_ICON`.

Afterwards `VISUAL_IDENTIFIER_EXPANSION` is applied as usual.

I also added `POWERLEVEL9K_BATTERY_${state}_LEVEL_BACKGROUND` and `POWERLEVEL9K_BATTERY_${state}_LEVEL_FOREGROUND`.

Please give it a try and let me know whether it works for you.

**Comment by horseinthesky** [comment] 2020-02-03 07:48
Cool!
Should it be always 10 icons or could it be less?

**Comment by romkatv** [comment] 2020-02-03 07:53
It can be any number of icons. With one icon you'll have that icon for all charge levels. With two icons the cutoff will be at 50% charge level. With 3 icons the cutoffs are at 33% and 66%. With 10 icons the cutoffs are at 10%, 20%, 30%, and so on.

**Comment by romkatv** [comment] 2020-02-03 13:42
Did it work for you? Does it do what you wanted?

**Comment by horseinthesky** [comment] 2020-02-03 14:11
I can check it in a few hours. Sorry.

**Comment by romkatv** [comment] 2020-02-03 15:17
It's not urgent. I just wanted to let you know that I'd like to have a confirmation from you before closing this issue.

**Comment by horseinthesky** [comment] 2020-02-03 18:00
Yes. It works like a charm. Couldn't find 10 icons for the charging battery but 7 is fine too.
```
typeset -g POWERLEVEL9K_BATTERY_CHARGING_STAGES=$'\uf585\uf586\uf587\uf588\uf589\uf58a\uf584'
```

**Comment by romkatv** [comment] 2020-02-03 18:02
Hopefully 7 is enough. You can always launch FontForge and draw a few more :-D

Thanks for verifying that the new parameter works!

**Closed by romkatv** 2020-02-03 18:02 UTC

**Comment by horseinthesky** [comment] 2020-02-19 14:00
I don't think I need another issue as everything I wanted works perfectly well.

I just wanted to ask one thing I don't know how to achieve:
You have a great battery indicator which somehow detects that there is a battery in my device. I've checked the code and found this https://github.com/romkatv/powerlevel10k/blob/a6a2d9a4815534a0ddbd8f76e5e17b33af75d700/internal/p10k.zsh#L1254 but I don't really understand how it works.

Now I use this:
```
typeset -g POWERLEVEL9K_HOST_ICON='' # \uF108
if [[ -d /sys/class/power_supply/BAT1 ]] && grep -Fxq "1" /sys/class/power_supply/BAT1/present; then
  typeset -g POWERLEVEL9K_HOST_ICON='' # \uF109
elif [[ -d /sys/class/power_supply/battery ]] && grep -Fxq "1" /sys/class/power_supply/battery/present; then
  typeset -g POWERLEVEL9K_HOST_ICON='' # \uF109
fi
```
which is kind of ugly.

Is it possible write a single if statement to clearly know if there is a battery in my device or not?

**Comment by romkatv** [comment] 2020-02-19 14:13
As a one-liner that works with all options:

```zsh
emulate zsh -o extended_glob -c '[[ -n /sys/class/power_supply/(BAT*|battery)/(#qFN) ]]'
```

If you are putting it within `~/.p10k.zsh` and you haven't changed options in there, the surrounding defense can be dropped:

```zsh
[[ -n /sys/class/power_supply/(BAT*|battery)/(#qFN) ]]
```

This condition (although not in this form) was inherited from Powerlevel9k. Later I read the code of [acpiclient](https://sourceforge.net/projects/acpiclient/) and realized the condition is incorrect. No one has complained yet, so I haven't fixed it.

**Comment by horseinthesky** [comment] 2020-02-19 14:32
It does seem to work incorrect =(

From regular Ubuntu VM (no battery) through zsh:
```
ll /sys/class/power_supply/  
lrwxrwxrwx root root 0 B Tue Feb 18 17:27:17 2020   ACAD ⇒ ../../devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0003:00/power_supply/ACAD

if [[ -n /sys/class/power_supply/(BAT*|battery)/(#qFN) ]]; then echo "Battery"; else echo "NO battery"; fi
Battery
```

From WSL (version 1) on PC (no battery):
```
ll /sys/class/power_supply/
drwxr-xr-x root root 0 B Fri Feb 14 06:33:34 2020   ac
drwxr-xr-x root root 0 B Fri Feb 14 06:33:34 2020   battery
drwxr-xr-x root root 0 B Fri Feb 14 06:33:34 2020   usb

if [[ -n /sys/class/power_supply/(BAT*|battery)/(#qFN) ]]; then echo "Battery"; else echo "NO battery"; fi
Battery
```

**Comment by romkatv** [comment] 2020-02-19 14:34
> As a one-liner that works with all options:
> 
> ```shell
> emulate zsh -o extended_glob -c '[[ -n /sys/class/power_supply/(BAT*|battery)/(#qFN) ]]'
> ```

:point_up:

**Comment by horseinthesky** [comment] 2020-02-19 14:44
So even if I am in zsh I should do this emulation.

But still
Ubuntu VM:
```
emulate zsh -o extended_glob -c 'if [[ -n /sys/class/power_supply/(BAT*|battery)/(#qFN) ]]; then echo "Battery"; else echo "NO battery"; fi'
NO battery
```

WSL
```
emulate zsh -o extended_glob -c 'if [[ -n /sys/class/power_supply/(BAT*|battery)/(#qFN) ]]; then echo "Battery"; else echo "NO battery"; fi'
Battery
```

**Comment by romkatv** [comment] 2020-02-19 14:49
> So even if I am in zsh I should do this emulation.

Only if you are using zsh with unusual options. Is there a reason you have `extended_glob` unset?

> WSL

**Comment by horseinthesky** [comment] 2020-02-19 14:56
> What's in the directory?
> 
> ```shell
> ls -l /sys/class/power_supply/battery
> ```

```
ll /sys/class/power_supply/battery
.r--r--r-- root root 0 B Fri Feb 14 06:33:34 2020   capacity
.r--r--r-- root root 0 B Fri Feb 14 06:33:34 2020   charge_counter
.r--r--r-- root root 0 B Fri Feb 14 06:33:34 2020   current_now
.r--r--r-- root root 0 B Fri Feb 14 06:33:34 2020   health
.r--r--r-- root root 0 B Fri Feb 14 06:33:34 2020   present
.r--r--r-- root root 0 B Fri Feb 14 06:33:34 2020   status
.r--r--r-- root root 0 B Fri Feb 14 06:33:34 2020   technology
.r--r--r-- root root 0 B Fri Feb 14 06:33:34 2020   temp
.r--r--r-- root root 0 B Fri Feb 14 06:33:34 2020   type
.r--r--r-- root root 0 B Fri Feb 14 06:33:34 2020   voltage_now
```

The file `present` is empty where real notebooks have `1` inside.

**Comment by horseinthesky** [comment] 2020-02-19 14:56
> What's in the directory?
> 
> ```shell
> ls -l /sys/class/power_supply/battery
> ```

```
ll /sys/class/power_supply/battery
.r--r--r-- root root 0 B Fri Feb 14 06:33:34 2020   capacity
.r--r--r-- root root 0 B Fri Feb 14 06:33:34 2020   charge_counter
.r--r--r-- root root 0 B Fri Feb 14 06:33:34 2020   current_now
.r--r--r-- root root 0 B Fri Feb 14 06:33:34 2020   health
.r--r--r-- root root 0 B Fri Feb 14 06:33:34 2020   present
.r--r--r-- root root 0 B Fri Feb 14 06:33:34 2020   status
.r--r--r-- root root 0 B Fri Feb 14 06:33:34 2020   technology
.r--r--r-- root root 0 B Fri Feb 14 06:33:34 2020   temp
.r--r--r-- root root 0 B Fri Feb 14 06:33:34 2020   type
.r--r--r-- root root 0 B Fri Feb 14 06:33:34 2020   voltage_now
```

The file `present` is empty where real notebooks have `1` inside.

**Comment by horseinthesky** [comment] 2020-02-19 17:10
Both VM and WSL shows `No battery` with this one. I will check a real notebook tomorrow.

Could you explain what these `emulate zsh -o extended_glob -c` and `(#qFN)` and `(#qL+0N)` do?

**Comment by romkatv** [comment] 2020-02-19 17:16
> Both VM and WSL shows `No battery` with this one.

Too bad. FWIW, I'm posting them without testing, so there is indeed good chance they don't work. The idea is simple though, so you should be able to create the right condition after a few minutes of experimenting.

> Could you explain what these `emulate zsh -o extended_glob -c` and `(#qFN)` and `(#qL+0N)` do?

`emulate` is documented in `man zshbuiltins`. I'm using here simply because I don't know which options you are running with. If you ran with good options, there would be no need for it. The important option to have on is `extended_glob`. Other options also might affect it -- there is just a ton of options in Zsh.

`(#qL+0N)` is documented in `man zshexpn`. Search for "Glob Qualifiers".

**Comment by horseinthesky** [comment] 2020-02-19 17:25
> Too bad. FWIW, I'm posting them without testing, so there is indeed good chance they don't work. The idea is simple though, so you should be able to create the right condition after a few minutes of experimenting.

Sorry, I didn't mention that `No battery` is correct for these two.

I got the idea. Will look through the docs. If I won't find any suitable expression I'll just stick with an ugly one =)

**Comment by romkatv** [comment] 2020-02-19 17:29
> > Too bad. FWIW, I'm posting them without testing, so there is indeed good chance they don't work. The idea is simple though, so you should be able to create the right condition after a few minutes of experimenting.
> 
> Sorry, I didn't mention that `No battery` is correct for these two.

Then it probably works. It looks correct to me.

This expression checks if there is a non-empty file matching this glob pattern: `/sys/class/power_supply/(BAT*|battery)/(energy_full|charge_full|charge_counter)`. If you had `extended_glob` set, you could just `ls` it to see how it work:

```zsh
ls -l `/sys/class/power_supply/(BAT*|battery)/(energy_full|charge_full|charge_counter)`
```

You can also test it easily on any machine by replacing `/sys/` with `/tmp/` and then creating suitable files there and checking that the check works as intended.
