### ISSUE TITLE
Sourcing powerlevel10k.zsh-theme forces COLUMNS env var to exist and update, breaking ncurses.

### ISSUE THREAD

**Issue by BlazingPL** [romkatv/powerlevel10k#1478] opened 2021-07-07 18:25 UTC
- OS: Arch Linux
- zsh: 5.8-1
- p10k: AUR zsh-theme-powerlevel10k-git r3896.4bcc519-5
- terminal: alacritty 0.8.0-1 

Applications like htop, ncspot, nconfig take set `COLUMNS` and `LINES` vars as constant size of terminal, and wont resize accordingly to the changing terminal, at least on alacritty.

Line `source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme` in .zshrc needed to run p10k for some reason forces COLUMNS var to exist even with `unset LINES; unset COLUMNS` in .zshrc which in turn forces some aplication to be static in size.

My temporary solution is to alias every problematic application with `env -u COLUMNS -u LINES`, but i'd like to know if this is possible to fix at p10k level.

- To reproduce:
Run htop and resize terminal, if the terminal was half the screen, and then it is fullscreened htop uses only half of the space for me.
run `unset COLUMNS` then `echo $COLUMNS`, the number of columns is printed.
Remove `source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme`, run above in a new zsh instance and COLUMNS is empty.

**Comment by romkatv** [comment] 2021-07-07 18:32
How can I reproduce this? Which commands do I need to run to observe the effect you are describing?

**Comment by BlazingPL** [comment] 2021-07-07 18:33
> How can I reproduce this? Which commands do I need to run to observe the effect you are describing?

Run htop and resize terminal, if the terminal was half the screen, and then it is fullscreened htop uses only half of the space for me.

**Comment by romkatv** [comment] 2021-07-07 18:40
> Run htop and resize terminal, if the terminal was half the screen, and then it is fullscreened htop uses only half of the space for me.

There are incomplete instructions. They don't reproduce it for me. Please try them yourself.

1. Run `zsh -f`
2. Run `typeset +x LINES COLUMNS`
3. Run `source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme`
4. Run `htop`
5. Resize your terminal

Do you have issues if you follow these steps?

> run `unset COLUMNS` then `echo $COLUMNS`, the number of columns is printed.
> Remove `source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme`, run above and COLUMNS is empty.

This cannot affect `htop` unless something in your config has erroneously exported `COLUMNS`. The best fix would be find that place and stop exporting this parameter. If you cannot find it, add this at the bottom of `~/.zshrc`:

```zsh
typeset +x COLUMNS LINES
```

This simply undoes the damage caused by the prior `export`.

**Comment by BlazingPL** [comment] 2021-07-07 19:03
Thank you, you are very right, it does work that way, but I don't know where to look for the damaging export as it does break even when I pruned .zshrc to source only p10k. When it's empty it works as intended and that puzzles me. I'm doing some reading on zsh manpages, but i don't know how to debug it yet, is there some option to print all exports as they are executed? I also skimmed  /etc/profile, /etc/profile.d/ and it all seems quite normal.
I had ohmyzsh installed a month ago as I was exploring zsh, is it possible there are leftovers?
Thank you for any clues.

**Comment by romkatv** [comment] 2021-07-07 19:06
You can try this:

```zsh
( typeset +x LINES COLUMNS; zsh -xic '' 2>&1 | grep LINES )
```

If you cannot find the place where these parameters are exported, add this at the bottom of `~/.zshrc`:

```shell
typeset +x COLUMNS LINES
```

This simply undoes the damage caused by the prior `export`.

Closing as WAI.

**Closed by romkatv** 2021-07-07 19:06 UTC
