### ISSUE TITLE
Problem with POWERLEVEL9K_RPROMPT_ON_NEWLINE=true (at least in Pure Power)

### ISSUE THREAD

**Issue by albertmichaelj** [romkatv/powerlevel10k#79] opened 2019-06-06 13:27 UTC
I'm using PowerLevel10k with the `.purepower` config file linked to in the readme. I started running into a weird issue. When I set the `POWERLEVEL9K_RPROMPT_ON_NEWLINE=true` setting on `.purepower` (with nothing else changed, so otherwise a clean copy of `.purepower`), when I would get a tab completion a) the first letter of the prompt would be duplicated and b) the cursor would sit on top of the last character in the prompt causing me to have to write over it. I've attached pictures to indicate this problem
<img width="874" alt="Screen Shot 2019-06-06 at 9 09 42 AM" src="https://user-images.githubusercontent.com/5385923/59035471-5dd1f680-883b-11e9-9ae9-4fe6db22583b.png">
What it should look like is this (this is with PowerLevel9k, though there is a weird space after the right prompt that shouldn't be there):
<img width="877" alt="Screen Shot 2019-06-06 at 9 08 57 AM" src="https://user-images.githubusercontent.com/5385923/59035500-6c201280-883b-11e9-8dfa-d59d834d9951.png">
I'm using the Adobe Source Code Pro font, so it shouldn't be a font issue. I've tried with both Apple Terminal and iTerm2 and it happens in both terminal emulators. 

I still have this issue if I ssh into a linux machine with the same config. However, and weirdly, I  do not have this issue if I'm using `byobu` with a tmux backend in the terminal. In byobu, the `TERM` variable is either `tmux-256color` or `screen-256color` (depending on which computer I'm on), but on the local machine where it is messing up it is `xterm-256color`. So, I'm guessing that has something to do with it. However, I do not know why things work (nearly) correctly on PowerLevel9k and not on 10k.

Please let me know if I can provide additional information that is helpful.

**Comment by romkatv** [comment] 2019-06-06 13:35
This is because of a bug in ZSH. I've fixed it downstream but it hasn't made into a release yet. You can reproduce the same bug in a clean ZSH session. First, type `zsh -df`. Then paste this:

```zsh
ZLE_RPROMPT_INDENT=0
PROMPT='left> '
RPROMPT='right'
```

You'll notice that the position of the cursor is wrong (it's right after `>` without a space in between) and you'll get weird behavior if you press `Ctrl-R` or type `ls<tab>`.

If you are changing `POWERLEVEL9K_RPROMPT_ON_NEWLINE` in `.purepower` and your ZSH doesn't contain a fix for this bug, you'll need to remove the line that sets `ZLE_RPROMPT_INDENT=0` (it's in `.purepower`, too).

Once you restart ZSH, the issue should be gone. If not, type `echo $ZLE_RPROMPT_INDENT`. If it prints `0`, it means some other code in your config overrides it. You can either find that line and remove it, or add `ZLE_RPROMPT_INDENT=1` at the bottom of `~/.zshrc`.

Please let me know if this fixes the issue.

**Comment by albertmichaelj** [comment] 2019-06-06 13:57
That exactly fixes the issue (though it adds that space into the right hand side, which is fine for now). On my mac, the version I have of zsh is `5.7.1`, but the ubuntu repos are a bit older (`5.4.2`). Do you think this fix will be backported?

Thanks for your help! Feel free to either leave this issue open so that others can find it or just close it, whatever is best for the you and the repo.

**Comment by romkatv** [comment] 2019-06-06 14:04
This is the fix: https://github.com/zsh-users/zsh/commit/3eea35d0853bddae13fa6f122669935a01618bf9. It won't be backported but it should make it into the next ZSH release. ZSH without this fix can handle `ZLE_RPROMPT_INDENT=0` on some terminals but not on others.

The reason the stock Pure Power config isn't affected by this bug is because it doesn't set `RPROMPT`. What you see on the right side of the screen is actually left prompt. But when you set `POWERLEVEL9K_RPROMPT_ON_NEWLINE`, Powerlevel10k starts using the real right prompt and triggers the bug.

**Closed by romkatv** 2019-06-06 14:04 UTC

**Comment by romkatv** [comment] 2019-06-14 14:23
@albertmichaelj I've implemented a workaround in Powerlevel10k for the ZSH bug.

If you update powerlevel10k, your cursor should behave correctly even if you set ZLE_RPROMPT_INDENT=0. Please let me know whether it works for you.

**Comment by romkatv** [comment] 2019-06-14 14:24
Sorry for the confusion. The workaround won't kick in for your config, so there is no reason for you to try it.

**Comment by albertmichaelj** [comment] 2019-06-14 19:11
I did try it anyway, and it didn't change anything. Thanks for thinking of my issue though!
