### ISSUE TITLE
configuration script does not offer color management

### ISSUE THREAD

**Issue by k7faq** [romkatv/powerlevel10k#1164] opened 2020-12-16 17:04 UTC
The documentation talks about configuring the FOREGROUND and BACKGROUND colors using the configuration script. However the configuration script is not offering this ability to the end user.

**Comment by romkatv** [comment] 2020-12-16 17:05
Please elaborate.

**Comment by k7faq** [comment] 2020-12-16 17:10
The README.md (line 1542) states

```
In Rainbow style the current working directory is shown with bright white text on blue background.
The white is fixed and always looks the same but the appearance of "blue" is defined by your
terminal color palette. If it's very light, it may be difficult to see white text on it.

There are several ways to fix this.

- Type `p10k configure` and choose a more readable prompt style.
- [Change terminal color palette](#change-the-color-palette-used-by-your-terminal). Try Tango Dark
  or Solarized Dark, or change just the "blue" color.
- [Change directory background and/or foreground color](#set-colors-through-Powerlevel10k-configuration-parameters).
  The parameters you are looking for are called `POWERLEVEL9K_DIR_BACKGROUND`,
  `POWERLEVEL9K_DIR_FOREGROUND`, `POWERLEVEL9K_DIR_SHORTENED_FOREGROUND`,
  `POWERLEVEL9K_DIR_ANCHOR_FOREGROUND` and `POWERLEVEL9K_DIR_ANCHOR_BOLD`. You can find them in
  in `~/.p10k.zsh`.
```

When I run the `p10k configure` command the options mentioned are not displayed. Additionally there are no options presented to select which them you would like to use.

**Comment by romkatv** [comment] 2020-12-16 17:12
> When I run the `p10k configure` command the options mentioned are not displayed.

By options you mean `POWERLEVEL9K_DIR_BACKGROUND`, `POWERLEVEL9K_DIR_FOREGROUND`, `POWERLEVEL9K_DIR_SHORTENED_FOREGROUND`, `POWERLEVEL9K_DIR_ANCHOR_FOREGROUND` and `POWERLEVEL9K_DIR_ANCHOR_BOLD`, right? These are parameters. You can find them in `~/.p10k.zsh`. There are many parameters in this file and there are virtually infinitely many ways you can customize prompt by editing it. The configuration wizard exposes only the most basis choices.

Closing as working as intended.

**Closed by romkatv** 2020-12-16 17:12 UTC

**Comment by hahastudio** [comment] 2020-12-26 07:43
I found that in `wizard.zsh`, it will check your terminal color mode first.
If in your configuration, terminal is not in 256 color mode, `p10k configure` will just skip the whole color configuration part.
If you are using iTerm, you can check [its FAQ page](https://iterm2.com/faq.html) to configure 256 color mode.

**Comment by romkatv** [comment] 2020-12-26 07:51
> I found that in `wizard.zsh`, it will check your terminal color mode first.
> If in your configuration, terminal is not in 256 color mode, `p10k configure` will just skip the whole color configuration part.

This makes sense. If your terminal is configured to use 8 colors, printing colors with the codes above 8 will result in uncolored text. You can verify this yourself by running `TERM=xterm` and then printing the color table:

```zsh
for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done
```

When the wizard notices that your terminal cannot display colors above 8, it doesn't ask whether you want to use prompt with 256 colors. Since the latter would result in uncolored prompt, there is no reason to ask.

It's the same with unicode. If your terminal cannot display unicode, the wizard won't ask you whether prompt should contain unicode symbols. It'll go with ascii because it's the only thing that will work.
