### ISSUE TITLE
Icons overlapping and font size not changing

### ISSUE THREAD

**Issue by 8FordPrefect8** [romkatv/powerlevel10k#2171] opened 2023-01-23 12:07 UTC
I installed yesterday p10k and the patched nerd font from AUR.
I use foot terminal and have the font's set up that Source Code Pro is the main font and the patched nerd font the fallback.

I noticed that during config the symbols overlapp the crosses.  
Further I noticed that some symbols are not affected by size eg. arch symbol, home house symbol, but others like checkmark and hour glass are.

**Comment by romkatv** [comment] 2023-01-23 12:10
How did you install the font from AUR?

What happens if you use a different terminal?

**Comment by 8FordPrefect8** [comment] 2023-01-23 12:20
I cloned the repos and run `makepkg -si`
I checked with kitty without setting the font esplicitly and just ramping up font size. There it seems to work.

**Comment by romkatv** [comment] 2023-01-23 12:23
> I cloned the repos and run `makepkg -si`

Which repos?

> I checked with kitty without setting the font esplicitly and just ramping up font size. There it seems to work.

Sounds like a bug in foot.

Do you believe the issue is specifically with the font that I made? If so, why?

**Comment by 8FordPrefect8** [comment] 2023-01-23 12:28
This repo for the font:
https://aur.archlinux.org/packages/ttf-meslo-nerd-font-powerlevel10k
and this repo for p10k:
https://aur.archlinux.org/packages/zsh-theme-powerlevel10k-git

I can check later on how it works with the non patched font of meslo NF. I had the idea that it's related to this version, because I saw #2167 with pictures of patched font and not patched font and there the scaling issue was visible too.

**Comment by romkatv** [comment] 2023-01-23 12:32
> I can check later on how it works with the non patched font of meslo NF.

There is no non-patched meslo NF. All NF fonts are patched.

> I had the idea that it's related to this version, because I saw #2167 with pictures of patched font and not patched font and there the scaling issue was visible too.

That picture shows two patched Meslo NF fonts: one from https://www.nerdfonts.com/ and another from powerlevel10k. The latter has properly scaled icons.

Closing as Not Our Issue. If the foot devs tell you that my font is buggy, feel free to reopen with extra info.

**Closed by romkatv** 2023-01-23 12:32 UTC
