### ISSUE TITLE
Show java version via jenv

### ISSUE THREAD

**Issue by mgh87** [romkatv/powerlevel10k#402] opened 2019-12-31 08:34 UTC
Similar to #211 it would be usefull to have a prompt for the java version of projects.

I implemented it as custom prompt for jenv within java projects that use maven to have a scoped display.

If you are interested I would add gradle to the scope and migrate it to powerlevel10k and hook you up with a PR.

**Comment by romkatv** [comment] 2019-12-31 11:59
> Show java version via jenv

There is already #342 that requests jenv support. OK to close this issue as a duplicate?

> I implemented it as custom prompt for jenv within java projects that use maven to have a scoped display.
> If you are interested I would add gradle to the scope and migrate it to powerlevel10k and hook you up with a PR.

I didn't understand these two sentences. When I get around to implementing jenv prompt segment, I don't plan on incorporating any sort of dependency on maven or gradle. Are you saying you want such dependencies? Can you clarify?

**Comment by mgh87** [comment] 2019-12-31 23:24
> > Show java version via jenv
> 
> There is already #342 that requests jenv support. OK to close this issue as a duplicate?

Yeah I guess thats fine. Will read it in detail soonish :-)
> 
> > I implemented it as custom prompt for jenv within java projects that use maven to have a scoped display.
> > If you are interested I would add gradle to the scope and migrate it to powerlevel10k and hook you up with a PR.
> 
> I didn't understand these two sentences. When I get around to implementing jenv prompt segment, I don't plan on incorporating any sort of dependency on maven or gradle. Are you saying you want such dependencies? Can you clarify?

The idea behind is that I show the prompt only in java project folders, since those is the place I need that information and everywhere else it just clutters up the prompt. - That is my reasoning. Maybe have it configurable.

I hope that clarifies my intend.

**Comment by romkatv** [comment] 2020-01-01 10:27
> The idea behind is that I show the prompt only in java project folders

jenv is very similar to rbenv, pyenv and nodenv, which have been supported by powerlevel10k for quite some time. No one has ever asked for this feature. I wonder why.

> it just clutters up the prompt

The existing `*env` prompt segments have the following two parameters that specify when the segment should be hidden:

```zsh
# Hide ruby version if it doesn't come from one of these sources.
typeset -g POWERLEVEL9K_RBENV_SOURCES=(shell local global)

# If set to false, hide ruby version if it's the same as global:
# $(rbenv version-name) == $(rbenv global).
typeset -g POWERLEVEL9K_RBENV_PROMPT_ALWAYS_SHOW=false
```

These are the default settings created by `p10k configure`. Another popular combination is this:

```zsh
# Show ruby version only when it's explicitly overridden by `rbenv local` or `rbenv shell`.
typeset -g POWERLEVEL9K_RBENV_SOURCES=(shell local)
```

So far this has worked for everyone. Would this also work for you? If not, could you describe how you are using jenv, and perhaps make a guess where your usage pattern differs from everyone else?

**Comment by mgh87** [comment] 2020-01-01 11:09
Thanks for the feedback.
I wasn't aware of this configuration option. On the first look it looks like a good match.
I don't completely understand how the sources parameter functions, but I'll just try it with ruby to get a feeling how it works.

**Comment by romkatv** [comment] 2020-01-01 11:19
> I don't completely understand how the sources parameter functions.

When you type `rbenv version`, the output may look like this:

```text
2.5.3 (set by /home/romka/.rbenv/version)
```

`2.5.3` is the current ruby version configured by rbenv. It's followed by the explanation of the source of this configuration. In the example above the source is a global config file, meaning that this version was set via `rbenv global 2.5.3`. In p10k parlance, the source is `global`.

Here's `local` source:

```shell
$ rbenv local 2.5.3
$ rbenv version
2.5.3 (set by /home/romka/my-project/.ruby-version)
```

And `shell`:

```shell
$ rbenv shell 2.5.3
$ rbenv version
2.5.3 (set by RBENV_VERSION environment variable)
```

**Comment by romkatv** [comment] 2020-01-02 12:43
dup of #342

**Closed by romkatv** 2020-01-02 12:43 UTC

**Comment by romkatv** [comment] 2020-01-02 18:00
FYI: I've added `jenv` prompt segment. If you update powerlevel10k, restart zsh (source `~/.zshrc` is not enough) and run `p10k configure`, you'll have it enabled in the config.

**Comment by mgh87** [comment] 2020-01-02 19:43
That was quick thanks. I'll have you look.

**Comment by mgh87** [comment] 2020-01-03 09:56
Looks really neat.

One question I'd like to add: how you would do a proper conditional rendering of the jenv prompt?

My condition is that I only need the java versions in folders that contain a pom.xml/gradle.build, or any parent directory containing this file. (I only need the java versions in directories that are related to maven or gradle projects and I thought the pom/gradle files is the easiest way to check.

A.D.: the p10k configure is really nice wasn't aware of it!

**Comment by romkatv** [comment] 2020-01-03 10:01
> My condition is that I only need the java versions in folders that contain a pom.xml/gradle.build, or any parent directory containing this file.

This is possible with an experimental API but before I suggest trying it I'd like to ensure that the public API won't serve your needs. As I mentioned above, there are many users of `*env` prompt segments and I've never encountered this feature request.

Do those projects for which you want to display jenv version have local jenv configuration? In other words, do they have `.java-version` file somewhere?

How do you usually set the current version with jenv? Could you give an example of a `jenv` command?

**Comment by mgh87** [comment] 2020-01-03 11:31
The jenv part is working perfectly fine.

My idea would be to use the  `typeset -g POWERLEVEL9K_JENV_PROMPT_ALWAYS_SHOW=false` and replace the false with a function that is true, if in a maven/gradle project and false otherwise.

But I don't think it would work that way. -- Since this is not evaluated on every rendering right?

> Do those projects for which you want to display jenv version have local jenv configuration? In other words, do they have .java-version file somewhere?
Most of my project doesn't use local version so the conditional render, when it differs from the global one does not work.

I would not like to break the *env API, the idea would be to have a function that returns true/false to have the possibility to define a condition for the prompt.

**Comment by romkatv** [comment] 2020-01-03 11:58
How do you usually set the current version with jenv? Could you give an example of a `jenv` command?

P.S.

As I mentioned earlier, what you want is already supported. You don't have to suggest how the API should look like.

**Comment by mgh87** [comment] 2020-01-03 12:23
`Jenv local "version"` or `jenv global "version"`.
Your jenv implementation is working. I set it up with p10k configure. And i behaves as you described it.

> As I mentioned earlier, what you want is already supported. You don't have to suggest how the API should look like.

I might be just to stupid, but I don't see how it is supported currently. Looked through the p9k and p10k wiki, but I can't figure it out.

**Comment by romkatv** [comment] 2020-01-03 12:55
> Your jenv implementation is working.

I know, thanks.

> I might be just to stupid, but I don't see how it is supported currently. Looked through the p9k and p10k wiki, but I can't figure it out.

Earlier I wrote:

> This is possible with an experimental API but before I suggest trying it I'd like to ensure that the public API won't serve your needs.

I then asked a few questions and after a few rounds of replies you've provided the answers. I now see that the public API indeed doesn't server your needs. You could try the experimental API. Keep in mind that it doesn't have backward compatibility guarantee yet.

To use the experimental API, add the following to `~/.p10k.zsh`:

```zsh
function p10k-on-pre-prompt() {
  emulate -L zsh -o extended_glob
  # If there is pom.xml or gradle.build in the current directory or above,
  # show jenv. Otherwise hide it.
  if [[ -n ./(../)#(pom.xml|gradle.build)(#qN) ]]; then
    p10k display '1/right/jenv'=show
  else
    p10k display '1/right/jenv'=hide
  fi
}
```

**Comment by mgh87** [comment] 2020-01-03 13:11
Thanks for the solution. Sorry for the extra rounds didn't know how to describe it better.

You're a zsh wizard.

A.D.:
* Is there a reference what's current public or experimental API of p10k?
* If I have configuration issues what's the best approach? (Especially to safe your time from too many questions 😅)

**Comment by romkatv** [comment] 2020-01-03 13:19
> Sorry for the extra rounds didn't know how to describe it better.

I think the communication problem was caused by your attempts to guess what information I need rather than answering the exact questions I've asked. You've repeatedly told me that jenv works and made suggestions for new options that you could use. All the while I wanted you to tell me about your jenv workflow (you use `jenv local` and `jenv global` to set java version; not all your java projects have `.java-version` files).

> Is there a reference what's current public or experimental API of p10k?

All options used in `~/.p10k.zsh` generated by `p10k configure` are public. Their meaning won't change when you upgrade p10k.

All names that start with an underscore are private.

There are a few experimental (things such as `p10k-on-pre-prompt`) but there is no index of them.

By the way, the implementation of `p10k-on-pre-prompt` I wrote for you is unlikely to break with future updates. Can still happen but chances are low. This API will likely become public as is.

> If I have configuration issues what's the best approach?

If you cannot find the question by tweaking stuff in `~/.p10k.zsh`, open an issue.

**Comment by romkatv** [comment] 2020-01-03 13:41
> I think the communication problem was caused by your attempts to guess what information I need rather than answering the exact questions I've asked. You've repeatedly told me that jenv works and made suggestions for new options that you could use. All the while I wanted you to tell me about your jenv workflow (you use `jenv local` and `jenv global` to set java version; not all your java projects have `.java-version` files).

Just to clarify, this didn't annoy me or anything. I'm not saying you did anything wrong or should've done better. There was obvious miscommunication but we've resolved it quickly.

**Comment by mgh87** [comment] 2020-01-03 14:43
> Just to clarify, this didn't annoy me or anything. I'm not saying you did anything wrong or should've done better. There was obvious miscommunication but we've resolved it quickly.

Wasn't received that way. I was more annoyed of myself not being able to communicate it proper, so that we're on the same page.

Could you point me in a direction to learn some nice zsh script tricks? - the recursive search for pom.xml files blew me away! 🤯🤯

**Comment by romkatv** [comment] 2020-01-03 14:49
> Could you point me in a direction to learn some nice zsh script tricks?

I'm new to zsh myself, started using it less than a year ago. I've learned zsh primarily from the official documentation -- see links under *Documentation* at http://zsh.sourceforge.net/. I've also read the source code of zsh projects that looked good.

> the recursive search for pom.xml files blew me away!

I agree, it's cute :-) This approach has the downside of globbing more directories than necessary. In p10k I would implement it with a bit more code to make it faster. This makes no difference for 99% of users though.
