### ISSUE TITLE
Directory names containing spaces are not truncated

### ISSUE THREAD

**Issue by tobsz** [romkatv/powerlevel10k#1688] opened 2021-12-27 05:50 UTC
In case a directory name contains _spaces_ the truncation feature is no longer working properly and the prompt overflows. I tested it with very long space-free names, there the directory names are truncated as expected, but with spaces they aren't (see screenshots). To be sure it's not the terminal emulator, I tested it with Konsole and Kitty.

![p10k_path_shortening_spaces](https://user-images.githubusercontent.com/17267460/147438300-0a0afa69-1c12-4390-97f7-43211ab43a6a.png)

![p10k_path_shortening_no_spaces](https://user-images.githubusercontent.com/17267460/147438774-5859a63e-f7e4-43c4-bcbe-2e8ce2fa801c.png)

**Comment by romkatv** [comment] 2021-12-27 06:58
I wasn't able to reproduce this.

![image](https://user-images.githubusercontent.com/1282067/147443908-3c9aa206-43ba-49da-b410-fcd71e8ab441.png)

Make sure you are on the latest version of powerlevel10k. If updating doesn't solve this issue, attach all relevant configs so that I can try to reproduce this.

**Comment by tobsz** [comment] 2021-12-27 08:22
I checked and was almost on the latest version (only one commit behind), but even after updating the problems persists for me.

Here my [p10k.zsh](https://github.com/romkatv/powerlevel10k/files/7779181/p10k.zsh.txt) and my [zshrc](https://github.com/romkatv/powerlevel10k/files/7779202/zshrc.txt). Are there any other config files you might need?

**Comment by romkatv** [comment] 2021-12-27 08:29
I couldn't reproduce it with your p10k.zsh. I didn't try it with your zshrc though because it quite large. Please do the following:

1. Verify that the problem still reproduces if you replace your whole zshrc with this:
  ```zsh
  source /home/tobias/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme
  source ~/.p10k.zsh
  ```
2. If it does not reproduce, find out what in your zshrc is relevant for reproducing the problem.
3. If it does reproduce, post the complete listing of files and directories that are necessary to reproduce the problem.

**Comment by tobsz** [comment] 2021-12-27 08:47
The problem still reproduces with only these 2 lines in my .zshrc. I also cross-checked on one of my universities SSH servers, where I pretty much have the same setup, and recreated the same path. There the path is truncated as expected, which puts me at a total loss, which files and directories that might be in point 3.

**Comment by romkatv** [comment] 2021-12-27 08:55
> which files and directories that might be in point 3.

In the worst case it's the whole home directory. You can get the full list like this:

```zsh
command find ~
```

However, there is likely a smaller subset that's relevant. You can find it through experimentation.

Let's also rule out the possibility that there is human error somewhere. Please run the following command and let me know whether the problem reproduces in the shell that it creates (you can `exit` it to go back to your normal shell).

```zsh
() (
  emulate -L zsh -o err_return
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
  {
    builtin cd -q -- $tmp
    curl -fsSLo .p10k.zsh https://github.com/romkatv/powerlevel10k/files/7779181/p10k.zsh.txt
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
    >.zshrc <<\END
source $ZDOTDIR/powerlevel10k/powerlevel10k.zsh-theme
source $ZDOTDIR/.p10k.zsh
END
    builtin cd -q
    ZDOTDIR=$tmp zsh --no-global-rcs
  } always {
    cd /
    command rm -rf -- $tmp
  }
)
```

**Comment by romkatv** [comment] 2021-12-27 09:02
> However, there is likely a smaller subset that's relevant. You can find it through experimentation.

It's quite likely that the following command will provide the answer to this puzzle:

```zsh
command ls -A1 ~/Programming/Tutorials/Haskell
```

**Comment by tobsz** [comment] 2021-12-27 09:26
I ruled out the possibility of a human error with your script. 
[This](https://github.com/romkatv/powerlevel10k/files/7779487/directory-structure.txt) is the slightly abbreviated output of tree in `~/Programming/Tutorials/Haskell/`. Is it already enough for you to reproduce the problem?

**Comment by romkatv** [comment] 2021-12-27 09:32
> Is it already enough for you to reproduce the problem?

Is it enough for *you* to reproduce the problem? You have access to another server, and you also can create a new user on your local machine.

**Comment by tobsz** [comment] 2021-12-27 09:46
Of course! Sorry, I didn't want to let you do all the work.
I tested it on the other server in that I copied the directory `Haskell from First Principles` and all its contents over there and made the discovery, that the problem is present until I remove the `.git` directory in `Haskell from First Principles`. After it is gone, the path is truncated, and when I move it back, the problem is back as well.

**Comment by romkatv** [comment] 2021-12-27 09:51
You have this in your `.p10k.zsh`:

```zsh
# Don't shorten directories that contain any of these files. They are anchors.
local anchor_files=(
  .bzr
  .citc
  .git
  .hg
  .node-version
  .python-version
  .go-version
  .ruby-version
  .lua-version
  .java-version
  .perl-version
  .php-version
  .tool-version
  .shorten_folder_marker
  .svn
  .terraform
  CVS
  Cargo.toml
  composer.json
  go.mod
  package.json
  stack.yaml
)
typeset -g POWERLEVEL9K_SHORTEN_FOLDER_MARKER="(${(j:|:)anchor_files})"
```

Configs generated by `p10k configure` set different style for anchor and non-anchor directories so that you can see which directories are "important" (the root of a git repo usually is) and won't be shortened. You've manually disabled this by setting `POWERLEVEL9K_DIR_ANCHOR_BOLD=false`. If you didn't, the issue would be resolved just by looking at the screenshot.

**Comment by tobsz** [comment] 2021-12-27 10:03
I actually didn't change anything manually in the config and before I opend the issue, I even deleted .p10k.zsh and redid `p10k configure` to be sure it wasn't anything I introduced in the config file.

**Comment by romkatv** [comment] 2021-12-27 10:06
Oh, it's an 8-color config. I apologize. That one doesn't use bold by default. It also displays shortened segments in the same color as non-shortened. The 256-color config uses these features.

Closing as resolved. If you want directories with `.git` in them to be shortened, modify `anchor_files` in your `.p10k.zsh`.

**Comment by tobsz** [comment] 2021-12-27 10:07
Ok, thank you for your help!

**Closed by romkatv** 2021-12-27 10:06 UTC
