### ISSUE TITLE
Transient prompt issue with per-directory-history plugin from oh-my-zsh

### ISSUE THREAD

**Issue by Saduff** [romkatv/powerlevel10k#1779] opened 2022-02-18 07:52 UTC
When pressing Ctrl+G to switch between local and global histories, text should be printed, but it doesn't show up with the transient prompt enabled. An empty prompt is displayed with no text.

Relevant line from the per-directory-history plugin:
https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/per-directory-history/per-directory-history.zsh#L71

After pressing Ctrl+G:
![image](https://user-images.githubusercontent.com/11700507/154640516-f88a61b7-40f6-4468-b4d7-4dcb7d4ca48e.png)

**Comment by romkatv** [comment] 2022-02-18 08:23
Please submit a bug against Oh My Zsh. `per-directory-history-toggle-history` needs to be fixed.

**Comment by romkatv** [comment] 2022-02-18 09:17
Try this:

1. Use any prompt you like.
2. Type "test", press <kbd>ESC Enter</kbd>, type "test test test test test" and press <kbd>Ctrl+G</kbd>.
3. Observe brokenness.

If you press <kbd>Ctrl+A</kbd> twice before pressing <kbd>Ctrl+G</kbd>, you can observe different kind of brokenness.

**Comment by romkatv** [comment] 2022-02-18 13:26
Closing because the issues is caused by a bug in Oh My Zsh that can be reproduced without powerlevel10k.

**Closed by romkatv** 2022-02-18 13:27 UTC

**Comment by Saduff** [comment] 2022-02-18 18:21
Okay, I see. I was not familiar with ZLE widgets. After reading some docs, I see that you're not supposed to use `print` or `echo` there but `zle -M` instead.

**Comment by romkatv** [comment] 2022-02-18 18:30
Indeed. You can also use `zle -I` if you must print to TTY from a widget.
