### ISSUE TITLE
Prompt hangs indefinitely when changing directory into a certain folder

### ISSUE THREAD

**Issue by CorvetteCole** [romkatv/powerlevel10k#2261] opened 2023-04-12 18:25 UTC
Here is the log after running `cd problem_directory`. Meanwhile, `cd other_directory` works fine, even though both are git repos.

```
+_gitstatus_process_response_POWERLEVEL9K-_p9k_:1> emulate -L zsh -o no_aliases -o extended_glob -o typeset_silent
+_gitstatus_process_response_POWERLEVEL9K-_p9k_:2> local pair=POWERLEVEL9K-_p9k_
+_gitstatus_process_response_POWERLEVEL9K-_p9k_:3> local name=POWERLEVEL9K
+_gitstatus_process_response_POWERLEVEL9K-_p9k_:4> local fsuf=_p9k_
+_gitstatus_process_response_POWERLEVEL9K-_p9k_:5> [[ POWERLEVEL9K == POWERLEVEL9K && _p9k_ == _p9k_ ]]
+_gitstatus_process_response_POWERLEVEL9K-_p9k_:5> eval $'emulate -L zsh -o no_hist_expand -o extended_glob -o no_prompt_bang -o prompt_percent -o no_prompt_subst -o no_aliases -o no_bg_nice -o typeset_silent -o no_rematch_pcre\n  (( $+__p9k_trapped )) || { local -i __p9k_trapped; trap : INT; trap "trap ${(q)__p9k_trapint:--} INT" EXIT }\n  local -a match mbegin mend\n  local -i MBEGIN MEND OPTIND\n  local MATCH OPTARG IFS=$\' \\t\\n\\0\''
+(eval):1> emulate -L zsh -o no_hist_expand -o extended_glob -o no_prompt_bang -o prompt_percent -o no_prompt_subst -o no_aliases -o no_bg_nice -o typeset_silent -o no_rematch_pcre
+(eval):2> ((  0  ))
+(eval):2> local -i __p9k_trapped
+(eval):2> trap : INT
+(eval):2> trap 'trap _p9k_trapint\;\ return\ 130 INT' EXIT
+(eval):3> local -a match mbegin mend
+(eval):4> local -i MBEGIN MEND OPTIND
+(eval):5> local MATCH OPTARG IFS=$' \t\n\C-@'
+_gitstatus_process_response_POWERLEVEL9K-_p9k_:6> ((  ARGC == 1  ))
+_gitstatus_process_response_POWERLEVEL9K-_p9k_:7> _gitstatus_process_response_p9k_ POWERLEVEL9K 0 ''
+_gitstatus_process_response_p9k_:1> local name=POWERLEVEL9K timeout req_id='' buf
+_gitstatus_process_response_p9k_:2> local -i resp_fd=_GITSTATUS_RESP_FD_POWERLEVEL9K
+_gitstatus_process_response_p9k_:3> local -i dirty_max_index_size=_GITSTATUS_DIRTY_MAX_INDEX_SIZE_POWERLEVEL9K
+_gitstatus_process_response_p9k_:5> ((  0 >= 0  ))
+_gitstatus_process_response_p9k_:5> timeout=-t0 
+_gitstatus_process_response_p9k_:5> [[ -t 17 ]]
+_gitstatus_process_response_p9k_:6> sysread -t0 -i 17 'buf[$#buf+1]'
+_gitstatus_process_response_p9k_:18> [[ $'\C-A' != * ]]
+_gitstatus_process_response_p9k_:19> sysread -i 17 'buf[$#buf+1]'
+_gitstatus_process_response_p9k_:1> :
```

The last line is after pressing control+c. There is no way to recover at this point. The prompt just says "loading" and does not accept any further input.

**Comment by romkatv** [comment] 2023-04-12 18:37
That log you've posted, what is that? Where did you get it?

**Comment by CorvetteCole** [comment] 2023-04-12 21:39
Sorry for the late response, I put zsh into debug mode with `set -x`

**Comment by romkatv** [comment] 2023-04-12 21:41
How can I reproduce this on my machine?

**Comment by CorvetteCole** [comment] 2023-04-12 21:47
I can't reproduce it on my other machines either, it only seems to be with one specific folder on a particular host. I was hoping you'd help tell me what information I could gather to help

**Comment by romkatv** [comment] 2023-04-12 21:49
I'm afraid I don't have the time or desire for remote debugging. If you can figure out how to reproduce this, I might take a look and try to fix this (no guarantees though).

**Comment by CorvetteCole** [comment] 2023-04-12 21:52
Fair enough. I don't really have the time to commit to reproducing this elsewhere as well. Just hoping for a clue, can't see an obvious suspect

**Comment by romkatv** [comment] 2023-04-12 22:02
Since neither of us is planning to do anything here, I'm going to close this issue. Please post an update if you even find out what the problem was.

**Closed** 2023-04-12 22:03 UTC

**Comment by CorvetteCole** [comment] 2023-04-12 23:24
Unfortunately I doubt I'll ever find out, we'll probably fix it by re-imaging the device. Thank you for your work on this!
