### ISSUE TITLE
Transient prompt with elements

### ISSUE THREAD

**Issue by aserrallerios** [romkatv/powerlevel10k#1649] opened 2021-11-26 14:18 UTC
I have two use cases:

* Keep the exit code != 0 of past commands
* Show timestamp of past commands

Transient output is very useful, but sometimes you want to have a trace of your last commands, but command & output is not enough. For example, the timestamp is very useful to catch up of find stuff in your console if it has been opened for days.

I think, one good solution for this would be to add a third prompt section only available if you enable transient prompt:
LEFT_PROMPT
RIGHT_PROMPT
TRANSIENT_PROMPT

This would allow you to configure any existing element you want in the transient lines.

**Comment by romkatv** [comment] 2021-11-26 14:32
See https://github.com/romkatv/powerlevel10k/issues/917 and the issues linked at the bottom.

**Comment by aserrallerios** [comment] 2021-11-26 21:11
Probably super naive but I tried to copy this https://github.com/romkatv/powerlevel10k/issues/917#issuecomment-664791542 into my config and nothing changed. And I'm also a bit confused, because that solution doesn't look nothing like this one https://github.com/romkatv/powerlevel10k/issues/1277#issuecomment-787415848.

**Comment by aserrallerios** [comment] 2021-12-06 15:57
I finally managed to make it work, but it looks like with the `status` segment is not possible (I can see the status in the _next_ lines, not in the original line of the command producing the status). I guess it's because the transient prompt must be instant and `status` isn't, right? Is there any workaround to get it working?

Thanks a lot.

**Comment by romkatv** [comment] 2021-12-06 15:59
See https://github.com/romkatv/powerlevel10k#can-prompts-for-completed-commands-display-error-status-for-those-commands-instead-of-the-commands-preceding-them

**Comment by aserrallerios** [comment] 2021-12-06 16:11
Got it, I'll add status to the transient even when it only shows in the following lines. It's better than nothing ;) Thanks!

BTW, is this method planed to change in the future? Something like a higher level variables to control the transient segments? Or do you think this lower-level method is good enough?

**Comment by romkatv** [comment] 2021-12-06 16:14
The low-level API will definitely stay because it's very flexible. You can do much more with it than transient prompt. For example, things like [show on command](https://github.com/romkatv/powerlevel10k#show-on-command) and show on upglob (not in the docs but you can probably find "UPGLOB" parameters in your config) are implemented on top of `p10k display`.

I don't have any immediate plans for adding an additional API for transient prompt.

**Comment by romkatv** [comment] 2021-12-06 20:08
Closing as I believe the issue is resolved.

**Closed by romkatv** 2021-12-06 20:08 UTC
