### ISSUE TITLE
[BUG] configure tool leaves right prompt indented

### ISSUE THREAD

**Issue by cainy-a** [romkatv/powerlevel10k#1147] opened 2020-12-04 19:24 UTC
When you use the configure tool, either through `p10k configure`, or on initial installation, it does not set `ZLE_RPROMPT_INDENT=0`, leaving a one space gap to the right of the right prompt.

Maybe it's for Powerlevel9k compatibility, but I personally feel that the generated configs should contain `export ZLE_RPROMPT_INDENT=0` somewhere in them to make the prompt use the full screen width.

**Comment by romkatv** [comment] 2020-12-04 19:48
This parameter is not specific to powerlevel10k, so it’s not set. You can set it yourself if you like, and it’ll be applied to all themes you use.

Closing as Working as Intended.

**Closed by romkatv** 2020-12-04 19:48 UTC

**Comment by cainy-a** [comment] 2020-12-04 19:54
Ah ok.
