### ISSUE TITLE
Whenever iTerm2 is opened for the first time, will be duplicated prompt

### ISSUE THREAD

**Issue by liby** [romkatv/powerlevel10k#1497] opened 2021-07-21 17:06 UTC
I'm not sure if this is the same as #1432 

https://user-images.githubusercontent.com/38807139/126529172-ea0246e6-a2bd-4883-adcd-90898a736afc.mp4

As you can see from the video, when you first open iTerm2, the window size is adjusted.

But I don't quite understand how to fix this problem in this [place](https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window).

**Comment by romkatv** [comment] 2021-07-21 17:10
Please try the following:

1. Add this at the very top of `~/.zshrc`:
   ```zsh
   PS1=$'${(pl.$((COLUMNS))..-.)}\n> '
   RPS1='<'
   ZLE_RPROMPT_INDENT=0
   setopt prompt_subst
   return
   ```
2. Open iTerm2 and see whether the issue still happens.

**Comment by liby** [comment] 2021-07-21 17:14
@romkatv

It no longer exists. So it was `ZLE_RPROMPT_INDENT` that caused the window resize?

**Comment by romkatv** [comment] 2021-07-21 17:20
I don't know what caused it but maybe we can figure it out with a few experiments.

Please do the following:

1. Remove what you added earlier to `~/.zshrc`.
2. Add this at the very top of `~/.zshrc`:
   ```zsh
   typeset -p LINES COLUMNS
   ```
3. Open iTerm2.
4. When prompt appears, type `typeset -p LINES COLUMNS` and press <kbd>Enter</kbd>.
5. Post a screenshot of your terminal.

**Comment by liby** [comment] 2021-07-21 17:22
@romkatv 
![image](https://user-images.githubusercontent.com/38807139/126532121-4b2ae678-2ec4-4cf5-9f52-b07bb0c87608.png)

**Comment by romkatv** [comment] 2021-07-21 17:26
Your screenshot indicates a bug in iTerm2. When the terminal just opened, it told zsh that the terminal was 87 columns wide. A few seconds later the terminal told zsh that the terminal was 84 columns wide. Since we know that the width of the terminal didn't really change in the interim (that is, you haven't resized it), the first report must have been incorrect. iTerm2 gave zsh wrong information. This needs to be fixed in iTerm2.

**Comment by liby** [comment] 2021-07-21 17:28
@romkatv 
I see what you mean. Thank you.

**Comment by romkatv** [comment] 2021-07-21 17:29
You are welcome.

Closing because the issue is caused by a bug in iTerm2.

**Closed** 2021-07-21 17:29 UTC
