### ISSUE TITLE
gitstatus hangs when booting

### ISSUE THREAD

**Issue by Wryte** [romkatv/powerlevel10k#2552] opened 2024-01-31 21:22 UTC
I'm having problems with gitstatus hanging when booting p10k. I've even let it hang for over 20 minutes but it never comes alive. Eventually I have to use `ctrl+C` to stop it from hanging and I get the following output with `GITSTATUS_LOG_LEVEL=INFO`:

<expand>
Output:
<details>

```
[ERROR]: gitstatus failed to initialize.

  Zsh log (/tmp/gitstatus.POWERLEVEL9K.1000.73394.1706735572.1.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version && 'Linux version 6.2.0-1019-gcp (buildd@lcy02-amd64-032) (x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #21~22.04.1-Ubuntu SMP Thu Nov 16 18:18:34 UTC 2023' == *Microsoft* ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /tmp/gitstatus.POWERLEVEL9K.1000.73394.1706735572.1.lock
    +(anon):15> [[ 18 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ linux-gnu == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /proc/self/fd/17
    +(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=73552'
    +(anon):46> [[ 20 == <1-> ]]
    +(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):51> ((  ! async  ))
    +(anon):41> _gitstatus_daemon_p9k_
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd
    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 20 ]]
    +(anon):57> sysread -s 20 -t 10.0000000000 -i 20 'pgid[$#pgid+1]'
    +(anon):55> ((  20 < 20  ))
    +(anon):59> [[ '               73552' == \ #<1-> ]]
    +(anon):60> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=pgid'
    +(anon):62> sysopen -w -o cloexec -u req_fd -- /tmp/gitstatus.POWERLEVEL9K.1000.73394.1706735572.1.fifo
    +(anon):62> return 130
    (anon):sysopen:62: can't open file /tmp/gitstatus.POWERLEVEL9K.1000.73394.1706735572.1.fifo: interrupt

  Daemon log (/tmp/gitstatus.POWERLEVEL9K.1000.73394.1706735572.1.daemon.log):

    +_gitstatus_daemon_p9k_:3> local pgid=73552
    +_gitstatus_daemon_p9k_:4> [[ 73552 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:90> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:11> local uname_sm
    +_gitstatus_daemon_p9k_:93> zsystem flock -- /tmp/gitstatus.POWERLEVEL9K.1000.73394.1706735572.1.lock
    +_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:12> uname -sm
    +_gitstatus_daemon_p9k_:12> uname_sm='linux x86_64'
    +_gitstatus_daemon_p9k_:13> [[ 'linux x86_64' == [^\ ]##\ [^\ ]## ]]
    +_gitstatus_daemon_p9k_:14> local uname_s=linux
    +_gitstatus_daemon_p9k_:15> local uname_m=x86_64
    +_gitstatus_daemon_p9k_:17> [[ '' == <1-> ]]
    +_gitstatus_daemon_p9k_:20> local cpus
    +_gitstatus_daemon_p9k_:21> ((  ! 1  ))
    +_gitstatus_daemon_p9k_:21> [[ linux == linux ]]
    +_gitstatus_daemon_p9k_:23> ((  ! 1  ))
    +_gitstatus_daemon_p9k_:23> cpus=+_gitstatus_daemon_p9k_:23> getconf _NPROCESSORS_ONLN
    +_gitstatus_daemon_p9k_:23> cpus=2
    +_gitstatus_daemon_p9k_:27> args+=( -t 4 )
    +_gitstatus_daemon_p9k_:30> mkfifo -- /tmp/gitstatus.POWERLEVEL9K.1000.73394.1706735572.1.fifo
    +_gitstatus_daemon_p9k_:31> print -rnu 13 -- '               73552'

  Add the following parameter to ~/.zshrc for extra diagnostics on error:

    GITSTATUS_LOG_LEVEL=DEBUG

  Restart Zsh to retry gitstatus initialization:

    exec zsh
```
</details>
</expand>

I can confirm that if I surround [this line](https://github.com/romkatv/powerlevel10k/blob/master/gitstatus/gitstatus.plugin.zsh#L659) in echo statements it does not make it to the second one. I tested that file existed and the script had write access and they both were true.

Oddly if I do run `exec zsh` after cancelling the prompt starts up fine.

1. Any idea how to get this working?
2. Any other information needed to help debug?
3. Is there a way to use p10k without gitstatus in the mean time?

**Comment by romkatv** [comment] 2024-02-01 05:59
What is the output of `which exec`?

I see in the logs that this line starts executing: https://github.com/romkatv/powerlevel10k/blob/62341054d8aa40ade03fc55bdbc95b9ff2d8d2b6/gitstatus/gitstatus.plugin.zsh#L411. Does it finish executing? What about the next line?

To test this, you can insert a couple of `:` lines in there:

```zsh
print -rnu $pipe_fd -- ${(l:20:)pgid} || return
:
exec <$file_prefix.fifo               || return
:
```

Then we'll see more diagnostics in logs.

**Comment by Wryte** [comment] 2024-02-01 15:13
> What is the output of which exec?

```
> which exec
exec: shell built-in command
```

Added:

```
print -rnu $pipe_fd -- ${(l:20:)pgid} || return
:
exec <$file_prefix.fifo               || return
:
```

<expand>
Output:
<details>

```
[ERROR]: gitstatus failed to initialize.

  Zsh log (/tmp/gitstatus.POWERLEVEL9K.1000.193488.1706800207.1.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version && 'Linux version 6.2.0-1019-gcp (buildd@lcy02-amd64-032) (x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #21~22.04.1-Ubuntu SMP Thu Nov 16 18:18:34 UTC 2023' == *Microsoft* ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /tmp/gitstatus.POWERLEVEL9K.1000.193488.1706800207.1.lock
    +(anon):15> [[ 18 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ linux-gnu == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /proc/self/fd/17
    +(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=193647'
    +(anon):46> [[ 20 == <1-> ]]
    +(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):51> ((  ! async  ))
    +(anon):41> _gitstatus_daemon_p9k_
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd
    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 20 ]]
    +(anon):57> sysread -s 20 -t 10.0000000000 -i 20 'pgid[$#pgid+1]'
    +(anon):55> ((  20 < 20  ))
    +(anon):59> [[ '              193647' == \ #<1-> ]]
    +(anon):60> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=pgid'
    +(anon):62> sysopen -w -o cloexec -u req_fd -- /tmp/gitstatus.POWERLEVEL9K.1000.193488.1706800207.1.fifo
    +(anon):62> return 130
    (anon):sysopen:62: can't open file /tmp/gitstatus.POWERLEVEL9K.1000.193488.1706800207.1.fifo: interrupt

  Daemon log (/tmp/gitstatus.POWERLEVEL9K.1000.193488.1706800207.1.daemon.log):

    +_gitstatus_daemon_p9k_:3> local pgid=193647
    +_gitstatus_daemon_p9k_:4> [[ 193647 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:92> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:11> local uname_sm
    +_gitstatus_daemon_p9k_:95> zsystem flock -- /tmp/gitstatus.POWERLEVEL9K.1000.193488.1706800207.1.lock
    +_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:12> uname -sm
    +_gitstatus_daemon_p9k_:12> uname_sm='linux x86_64'
    +_gitstatus_daemon_p9k_:13> [[ 'linux x86_64' == [^\ ]##\ [^\ ]## ]]
    +_gitstatus_daemon_p9k_:14> local uname_s=linux
    +_gitstatus_daemon_p9k_:15> local uname_m=x86_64
    +_gitstatus_daemon_p9k_:17> [[ '' == <1-> ]]
    +_gitstatus_daemon_p9k_:20> local cpus
    +_gitstatus_daemon_p9k_:21> ((  ! 1  ))
    +_gitstatus_daemon_p9k_:21> [[ linux == linux ]]
    +_gitstatus_daemon_p9k_:23> ((  ! 1  ))
    +_gitstatus_daemon_p9k_:23> cpus=+_gitstatus_daemon_p9k_:23> getconf _NPROCESSORS_ONLN
    +_gitstatus_daemon_p9k_:23> cpus=2
    +_gitstatus_daemon_p9k_:27> args+=( -t 4 )
    +_gitstatus_daemon_p9k_:30> mkfifo -- /tmp/gitstatus.POWERLEVEL9K.1000.193488.1706800207.1.fifo
    +_gitstatus_daemon_p9k_:31> print -rnu 13 -- '              193647'
    +_gitstatus_daemon_p9k_:32> :

  Add the following parameter to ~/.zshrc for extra diagnostics on error:

    GITSTATUS_LOG_LEVEL=DEBUG

  Restart Zsh to retry gitstatus initialization:

    exec zsh
```
</details>
</expand>

Looks like the print finishes but not the exec

**Comment by romkatv** [comment] 2024-02-02 06:36
Here's my understanding of what's going on. The code invokes `mkfifo(1)` to create a named pipe. It then opens the pipe for reading and writing in two different processes. Both of these hang.

We can try to verify this. Please run the following command and post its output.

```zsh
(
  emulate -L zsh -o xtrace

  fifo=/tmp/test-fifo
  if [[ -e $fifo ]]; then
    rm -- $fifo || exit
  fi
  command mkfifo -- $fifo || exit

  ( exec <$fifo ) &
  pids=(${!})
  ( exec >$fifo ) &
  pids+=(${!})

  command sleep 3 || exit
  if kill -0 -- $pids 2>/dev/null; then
    print FAILURE
    kill -- $pids 2>/dev/null
  else
    print SUCCESS
  fi
  wait -- $pids
  rm -- $fifo
)
```

I've seen something like this once on a machine with corporate spyware. Are you using a corporate machine? Have you installed everything on it yourself or has some kind of IT department done it for you?

**Comment by Wryte** [comment] 2024-02-02 15:19
I ran that script both after and before pressing `crtrl+C` and it printed success both time. I modified my `.zshrc` file to run it before booting oh-my-zsh and p10k and it worked fine followed by p10k/gitstatus hanging.

```
+/home/username/test-thing.sh:6> fifo=/tmp/test-fifo
+/home/username/test-thing.sh:7> [[ -e /tmp/test-fifo ]]
+/home/username/test-thing.sh:10> mkfifo -- /tmp/test-fifo
+/home/username/test-thing.sh:13> pids=( 357613 )
+/home/username/test-thing.sh:15> pids+=( 357614 )
+/home/username/test-thing.sh:17> sleep 3
+/home/username/test-thing.sh:18> kill -0 -- 357613 357614
+/home/username/test-thing.sh:22> print SUCCESS
SUCCESS
+/home/username/test-thing.sh:24> wait -- 357613 357614
+/home/username/test-thing.sh:25> rm -- /tmp/test-fifo
```

It is a corporate machine/vm that I dev on. I wasn't the one who set up the environment but I may be able to dive into what is needed.

Is there a way to disable gitstatus in the mean time?

**Comment by romkatv** [comment] 2024-02-04 18:25
> I ran that script both after and before pressing `crtrl+C` and it printed success both times.

I guess something else is necessary to reproduce this issue. Maybe the double fork, or maybe `sysread`.

If you can figure this out by yourself, that might be helpful. I'm afraid I won't offer to help with this, for this sort of remote debugging is often extremely time consuming.

> Is there a way to disable gitstatus in the mean time?

Sure. The best way would be to remove `vcs` from `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` in `~/.p10k.zsh`. This will remove git status from prompt altogether. If you do need git status in prompt, you can leave `vcs` in and define `POWERLEVEL9K_DISABLE_GITSTATUS=true`. This may make your prompt *really* slow.

**Comment by Wryte** [comment] 2024-02-05 16:07
Thank you, removing `vcs` from `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` did work as a temporary solution.

I couldn't figure out how to set `POWERLEVEL9K_DISABLE_GITSTATUS` and have it listen to that though. I tried exporting it in my `~/.zshrc` and using `typeset -g` in `~/.p10k.zsh` but it still tried to boot it.

**Comment by romkatv** [comment] 2024-02-05 16:12
`typeset -g POWERLEVEL9K_DISABLE_GITSTATUS=true` in `~/.p10k.zsh` is the way. You'll need to restart zsh twice afterwards if you are using instant prompt.

**Comment by romkatv** [comment] 2024-02-05 16:22
Sure, let's close this. It's almost certainly an issue caused by corporate spyware. As I mentioned, I've seen this before. Certain kinds of spyware break guarantees around pipes provided by system calls (inadvertently, I'm sure).

**Closed by romkatv** 2024-02-05 16:22 UTC
