### ISSUE TITLE
The Icon "took time" is huge on WezTerm until a run a non-instant command

### ISSUE THREAD

**Issue by D00mch** [romkatv/powerlevel10k#2448] opened 2023-10-09 10:35 UTC
Today I reconfigured, and have this problem.

When open a new session:
![image](https://github.com/romkatv/powerlevel10k/assets/14236531/5bf36089-dfa3-4b9d-87ab-43b4aa3ba857)

After run `sleep`:
![image](https://github.com/romkatv/powerlevel10k/assets/14236531/c744c01f-bf38-4193-a263-97dc666bc801)

OSX Ventura 13.2
wezterm 20230712-072601-f4abf8fd
zsh 5.8.1 (x86_64-apple-darwin22.0)

In the default OSX terminal the icon is fine.
I have a [font settins in my wezterm config](https://github.com/D00mch/dotfiles/blob/bb7d7fdf892944fc8515c730e0103c2cb7c9e1f3/.wezterm.lua#L299), but chaning it didn't help.

**Comment by romkatv** [comment] 2023-10-09 10:52
If you copy-paste the icon from the two prompts on your screenshot, do you get the same icon? If so, that sounds like a bug in WezTerm.

**Comment by romkatv** [comment] 2023-10-09 10:54
By the way, the checkmark isn't "took time". It's "success". You can compare how it looks after running `true` vs `false` vs `true | false` vs `sleep 10` that you kill with Ctrl-C.

**Comment by D00mch** [comment] 2023-10-09 13:03
When is large: ✔
When is fine: ✔

`true` doesn't do anothing to the initial "broken" mark symbol.
`false`, `true | false` act as `sleep`.

**Comment by romkatv** [comment] 2023-10-09 15:51
> When is large: ✔
> When is fine: ✔

Thanks for confirming that this indeed looks like a bug in the terminal. In short: the terminal displays the same symbol differently for no apparent reason.

Closing as the issues lies outside of powerlevel10k. If you file a bug against WezTerm, or find an existing bug, or figure out that it's not a bug, please post an update here.

**Closed** 2023-10-09 15:51 UTC
