### ISSUE TITLE
There is some weird triangle at the right

### ISSUE THREAD

**Issue by rluvaton** [romkatv/powerlevel10k#1736] opened 2022-01-25 19:03 UTC
First of all, great project! thank you very much

After I configure the theme using `p10k configure` and select my desired setting there is some weird triangle at the rightmost of the screen.
<img width="574" alt="final-result" src="https://user-images.githubusercontent.com/16746759/151042289-96318b9c-10f7-4650-a1d0-e463e5c8f771.png">

When configuration this, this doesn't happen:
<img width="823" alt="config-good" src="https://user-images.githubusercontent.com/16746759/151042326-4d827c1b-366d-4c8f-b9e6-427581b080bd.png">

**Environment:**
- OS: macOS Monetary 12.1
- Terminal: iTerm2 Build 3.4.15
- Font: JetBrains Mono

Also, run the script from https://github.com/romkatv/powerlevel10k/issues/180#issuecomment-522978183 and the output is:
```
ZSH_PATCHLEVEL=zsh-5.8-0-g77d203f
ZSH_VERSION=5.8
POWERLEVEL9K_MODE=nerdfont-complete
Darwin <name>-MacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
```

**Comment by romkatv** [comment] 2022-01-25 20:08
> After I configure the theme using `p10k configure` and select my desired setting there is some weird triangle at the rightmost of the screen.

If by the leftmost you mean rightmost, that's iTerm2 doing it. You can hide these marks in iTerm2 preferences: Profiles -> Open Profiles -> Edit Profiles -> Select your profile -> Terminal -> Uncheck "Show mark indicators".

**Comment by romkatv** [comment] 2022-01-25 20:23
> If by the leftmost you mean rightmost

LOL, I've no idea how that happened 🤣

**Comment by romkatv** [comment] 2022-01-25 20:24
OK, I know how that happened. You initially wrote "rightmost", which I thought wrong. But when I quoted your reply, you've already replaced rightmost with leftmost and I automatically wrote my reply with the correction as intended earlier.

Anyway, I believe I've addressed the actual problem you are having. Closing.

**Comment by rluvaton** [comment] 2022-01-25 20:25
![image](https://user-images.githubusercontent.com/16746759/151053902-e62ba189-2499-4778-aebe-a4e4a4be6ec5.jpeg)

**Closed by romkatv** 2022-01-25 20:24 UTC

**Comment by rluvaton** [comment] 2022-01-25 20:38
Thank you for your quick reply!, that fixed it, sorry 😬
