### ISSUE TITLE
Tails have wrong color in VSCode

### ISSUE THREAD

**Issue by MetaMmodern** [romkatv/powerlevel10k#1802] opened 2022-03-16 20:41 UTC
Hi, I did not want to actually create an inssue in the first place but I just can't find th solution for this.
I''ve installed WSL, zsh, oh-my-zsh and p10k, selected themes and all that stuff. When I open VSCode Terminal and open Ubuntu WSL I see this:
![image](https://user-images.githubusercontent.com/42899786/158686284-dd00822a-962a-45c5-9819-325bea76565c.png)
Slanted edges are off color. And also there is a black one on the left side.

However it shows everything correctly in Windows Terminal:
![image](https://user-images.githubusercontent.com/42899786/158686445-6c7f5518-e729-4291-90ea-584ffaeac9b3.png)
(font enlarged to be sure)

BUT the most mindblowing part for me is: 
if I run `code` inside VSCode terminal in Ubuntu WSL, which brings a VSCode instance, attached to WSL itself.
and then if I open terminal inside of it--the slantings are all good!
![image](https://user-images.githubusercontent.com/42899786/158686656-8ff1dc82-a175-440e-b8f6-35a2c02f6215.png)
(check the left bottom corner: I've connected to wsl)

Now I can't understand whether it is shell, or wsl, or p10k, or vscode issue) Would be glad if someone helped here, thanks in advance.

**Comment by romkatv** [comment] 2022-03-18 12:15
Your terminal defines how foreground and background colors with a certain color code look like. Directory uses color 4, status uses 0, and time uses 7. Your first screenshot shows that the terminal shows a different hue for the foreground and background 7. That's almost never what you want. Decent terminals allow you to customize this but I don't know whether your terminal allows that. We can also see that that the background 0 is the same as default background. This is also almost never what you want.

There is a bit more info here: https://github.com/romkatv/powerlevel10k#how-do-i-change-prompt-colors. Also relevant: https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols.

The practical advice is to use *Lean* style. It's more robust in the face of terminal rendering bugs and quirks. Also see https://github.com/romkatv/powerlevel10k#what-is-the-best-prompt-style-in-the-configuration-wizard.

**Comment by MetaMmodern** [comment] 2022-03-18 13:50
Hi, @romkatv , thank you  for the review. Well, the style that I'm using is the main reason I installed p10k actually)))) So I'll try to figure out the way to keep it(especially while it works on third screenshot). Will inspect what you've shared, thank you.

**Comment by MetaMmodern** [comment] 2022-03-18 14:27
okay, I checked a little bit of vscode settings and what I see:
1. There is a settings which defines tails color, it is terminal.foreground: 
![image](https://user-images.githubusercontent.com/42899786/159020423-bc00377c-06a3-486b-bf54-f28620ac05fd.png)
And it solves the _grayed out tails_ problem.
2. The status bar of p10k uses color 0, which as a I understood is black and we can tell VSCode to change black in settings also as on screenshot below:
![image](https://user-images.githubusercontent.com/42899786/159020589-00ed92d7-737e-443b-8362-3689b33638fd.png)

So in p2 we see that `terminal.ansiBlack` is responsible for black color not only in status, but also in branch name and status tail. 
The hard part left is to figure out why it renders correctly in WSL VSCode while dropping the status background in default VSCode.

**Comment by romkatv** [comment] 2022-03-18 14:30
Closing as the issue is not with powerlevel10k.

**Closed by romkatv** 2022-03-18 14:30 UTC

**Comment by asash3** [comment] 2022-04-03 19:26
https://github.com/microsoft/vscode/issues/146406#issuecomment-1084825473

**Comment by 47AD0** [comment] 2023-10-18 04:47
#
```javascript
function VSCode(WPF){
return 'codespace_'  + WPF.romkatv + '#newFunction'
};

var vscode1802='#2454'+WPF;
var WPF1739={

WPF:'#1808',
};
VSCode(WPF1739)
`
<details><summary>
</summary>```html
[1067613551893](http://html-css-js.com)
```
<p style="color : green">

```css

```
```node
``` 

</p>
</details>
