### ISSUE TITLE
bad math expression when using vcs

### ISSUE THREAD

**Issue by leonard-henriquez** [romkatv/powerlevel10k#110] opened 2019-07-07 15:39 UTC
I get `left_prompt_segment:87: bad math expression: illegal character: ^/` when the working repository is a git repository **ahead of remote repository**

I am using:
- Arch Linux
- ZSH: 5.7.1
- Oh my ZSH

I manually installed Powerlevel10k with
`git clone https://github.com/romkatv/powerlevel10k.git`

```
$ZSH_CUSTOM/themes/powerlevel10k

## ZSH config
ZSH_THEME=powerlevel10k/powerlevel10k

## Powerlevel
POWERLEVEL9K_MODE=nerdfont-complete
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs dir_writable root_indicator status)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(nvm rbenv ram load)

## Useful plugins
plugins=(git gitfast ruby rails command-not-found python pip github last-working-dir common-aliases zsh-syntax-highlighting history-substring-search fasd docker docker-compose)

## Actually load Oh-My-Zsh
source "${ZSH}/oh-my-zsh.sh"
```

**Comment by romkatv** [comment] 2019-07-07 15:41
Can you reproduce this if you disable all plugins?

**Comment by romkatv** [comment] 2019-07-07 16:01
I'm unable to reproduce this with ZSH 5.7.1 and your config. Here's the full script:

```zsh
docker run -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 -e TERM=$TERM -it --rm debian:buster bash -uexc '
  apt update && apt install -y git zsh

  cd
  git clone https://github.com/robbyrussell/oh-my-zsh.git
  cd oh-my-zsh/custom
  git clone https://github.com/romkatv/powerlevel10k.git themes/powerlevel10k
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git plugins/zsh-syntax-highlighting

  >~/.zshrc echo "
    ZSH=~/oh-my-zsh
    plugins=(git gitfast ruby rails command-not-found python pip github last-working-dir common-aliases zsh-syntax-highlighting history-substring-search fasd docker docker-compose)
    ZSH_THEME=powerlevel10k/powerlevel10k
    POWERLEVEL9K_MODE=nerdfont-complete
    POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
    POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs dir_writable root_indicator status)
    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(nvm rbenv ram load)
    source \$ZSH/oh-my-zsh.sh"

  git config user.email example@example.com

  touch x
  git add -f x
  git commit -m x

  exec zsh'
```

Could you run the following command on your machine and check whether it gives you an error or not?

```zsh
(
  emulate -L zsh && setopt err_return
  local tmp && tmp=$(mktemp -d "${TMPDIR:-/tmp}"/gitstatus.XXXXXXXXXX)
  {
    cd $tmp
    git clone https://github.com/robbyrussell/oh-my-zsh.git
    cd oh-my-zsh/custom
    git clone https://github.com/romkatv/powerlevel10k.git themes/powerlevel10k
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git plugins/zsh-syntax-highlighting

    >$tmp/.zshrc echo "
      ZSH=$tmp/oh-my-zsh
      plugins=(git gitfast ruby rails command-not-found python pip github last-working-dir common-aliases zsh-syntax-highlighting history-substring-search fasd docker docker-compose)
      ZSH_THEME=powerlevel10k/powerlevel10k
      POWERLEVEL9K_MODE=nerdfont-complete
      POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
      POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs dir_writable root_indicator status)
      POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(nvm rbenv ram load)
      source $tmp/oh-my-zsh/oh-my-zsh.sh"

    git config user.email example@example.com

    touch x
    git add -f x
    git commit -m x

    ZDOTDIR=$tmp zsh
  } always {
    rm -rf $tmp
  }
)
```

If it doesn't produce an error, could you figure out how this error can be reproduced?

**Comment by romkatv** [comment] 2019-07-07 16:08
Cannot reproduce on Arch. What's missing?

docker run -e LANG=en_US.utf8 -e LC_ALL=en_US.utf8 -e TERM -it --rm archlinux/base bash -c '
  set -uex
  pacman -Sy --noconfirm git zsh gawk

  cd
  git clone https://github.com/robbyrussell/oh-my-zsh.git
  cd oh-my-zsh/custom
  git clone https://github.com/romkatv/powerlevel10k.git themes/powerlevel10k
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git plugins/zsh-syntax-highlighting

  >~/.zshrc echo "
    ZSH=~/oh-my-zsh
    plugins=(git gitfast ruby rails command-not-found python pip github last-working-dir common-aliases zsh-syntax-highlighting history-substring-search fasd docker docker-compose)
    ZSH_THEME=powerlevel10k/powerlevel10k
    POWERLEVEL9K_MODE=nerdfont-complete
    POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
    POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs dir_writable root_indicator status)
    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(nvm rbenv ram load)
    source \$ZSH/oh-my-zsh.sh"

  git config user.email example@example.com
  git config user.name example

  touch x
  git add -f x
  git commit -m x

  exec zsh'

**Comment by leonard-henriquez** [comment] 2019-07-07 16:20
I don't seem to be able to reproduce the issue on my own computer...
Sorry for the inconvenience. I'll come with a script to reproduce the issue next time it happens.

**Comment by romkatv** [comment] 2019-07-07 16:24
> I'll come with a script to reproduce the issue next time it happens.

Please do. This the second report of this error that I've got today. Unfortunately, the other reporter also wasn't able to reproduce this after filing an issue. There is a bug somewhere and I'd really like to know how to trigger it so that I can fix it. You don't have to produce a small config for me that demonstrates the error. Even a hairy config would do as long as it triggers the bug.

**Comment by mmariani** [comment] 2019-07-08 09:51
I can reproduce this with

```
git add ..
git commit ...
git branch -m ...
```

If I push before branch -m, all is good. If I don't push, I have the error.
If I change the name of the branch back to the initial one, the error goes away.

Of course I can only reproduce on a specific fork of a private repository, I cannot reproduce by forking it in another location. I kept a backup of the directory, will investigate when/if I have time.

**Comment by romkatv** [comment] 2019-07-08 09:56
When you see the error, type `typeset -m 'VCS_STATUS_*'` and post the output here. If there is something sensitive that you have to censor, mention what you've censored.

Also post the output of this command:

```zsh
zsh -dfic 'GITSTATUS_LOG_LEVEL=DEBUG && source ~/gitstatus/gitstatus.plugin.zsh && gitstatus_start MY && gitstatus_query MY && typeset -m VCS_STATUS_\* && cat $GITSTATUS_DAEMON_LOG_MY'
```

Both commands must be run from the directory of the problematic repository.

**Comment by mmariani** [comment] 2019-07-08 10:15
I censored the remote url and some pathnames.
The error is only triggered if:

 - the local and remote branches do not match
 - there is at least one untracked file.

```
$ typeset -m 'VCS_STATUS_*'         
VCS_STATUS_COMMITS_AHEAD=1
VCS_STATUS_COMMITS_BEHIND=0
VCS_STATUS_TAG=''
VCS_STATUS_REMOTE_NAME=origin
VCS_STATUS_NUM_STAGED=0
VCS_STATUS_HAS_UNTRACKED=1
VCS_STATUS_NUM_UNTRACKED=1
VCS_STATUS_RESULT=ok-sync
VCS_STATUS_STASHES=2
VCS_STATUS_INDEX_SIZE=49
VCS_STATUS_HAS_UNSTAGED=0
VCS_STATUS_WORKDIR=[...]
VCS_STATUS_NUM_CONFLICTED=0
VCS_STATUS_NUM_UNSTAGED=0
VCS_STATUS_ACTION=''
VCS_STATUS_LOCAL_BRANCH=code_showcase
VCS_STATUS_REMOTE_BRANCH=code_showcse
VCS_STATUS_COMMIT=f13b48a4d2d204bee07f32db7ad6dddc0bdcaf09
VCS_STATUS_REMOTE_URL=...
VCS_STATUS_HAS_CONFLICTED=0
VCS_STATUS_HAS_STAGED=0
```


```
$ zsh -dfic 'GITSTATUS_LOG_LEVEL=DEBUG && source /home/marco/.zplug/repos/romkatv/powerlevel10k/gitstatus/gitstatus.plugin.zsh && gitstatus_start MY && gitstatus_query MY && typeset -m VCS_STATUS_\* && cat $GITSTATUS_DAEMON_LOG_MY'
VCS_STATUS_LOCAL_BRANCH=code_showcase
VCS_STATUS_REMOTE_BRANCH=code_showcse
VCS_STATUS_WORKDIR=[...]
VCS_STATUS_TAG=''
VCS_STATUS_NUM_CONFLICTED=0
VCS_STATUS_REMOTE_NAME=origin
VCS_STATUS_NUM_UNSTAGED=0
VCS_STATUS_NUM_STAGED=0
VCS_STATUS_COMMIT=f13b48a4d2d204bee07f32db7ad6dddc0bdcaf09
VCS_STATUS_HAS_UNTRACKED=1
VCS_STATUS_COMMITS_AHEAD=1
VCS_STATUS_COMMITS_BEHIND=0
VCS_STATUS_REMOTE_URL=[...]
VCS_STATUS_NUM_UNTRACKED=1
VCS_STATUS_RESULT=ok-sync
VCS_STATUS_STASHES=2
VCS_STATUS_INDEX_SIZE=49
VCS_STATUS_HAS_CONFLICTED=0
VCS_STATUS_HAS_UNSTAGED=0
VCS_STATUS_ACTION=''
VCS_STATUS_HAS_STAGED=0
[...]
+zsh:2> /home/marco/.zplug/repos/romkatv/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64 '--lock-fd=3' '--parent-pid=19995' '--num-threads=8' '--max-num-staged=1' '--max-num-unstaged=1' '--max-num-conflicted=1' '--max-num-untracked=1' '--dirty-max-index-size=-1' '--log-level=DEBUG'
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/gitstatus.cc:157] argv[0]: "/home/marco/.zplug/repos/romkatv/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64"
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/gitstatus.cc:157] argv[1]: "--lock-fd=3"
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/gitstatus.cc:157] argv[2]: "--parent-pid=19995"
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/gitstatus.cc:157] argv[3]: "--num-threads=8"
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/gitstatus.cc:157] argv[4]: "--max-num-staged=1"
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/gitstatus.cc:157] argv[5]: "--max-num-unstaged=1"
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/gitstatus.cc:157] argv[6]: "--max-num-conflicted=1"
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/gitstatus.cc:157] argv[7]: "--max-num-untracked=1"
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/gitstatus.cc:157] argv[8]: "--dirty-max-index-size=-1"
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/gitstatus.cc:157] argv[9]: "--log-level=DEBUG"
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/thread_pool.cc:81] Spawning 8 thread(s)
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/gitstatus.cc:171] Processing request: "hello" for ""
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/response.cc:69] Replying without git status
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/timer.cc:67] Timing for: request: 0.034ms cpu, 0.03371ms wall
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/gitstatus.cc:174] Successfully processed request: "hello" for ""
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/gitstatus.cc:171] Processing request: "1562580509.7826769352 " for "/home/marco/[...]"
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/repo_cache.cc:45] Initializing new repository: "/home/marco/[...]"
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/repo.cc:319] Splitting 49 object(s) into 1 shard(s)
[2019-07-08 12:08:29 00007f6bc8073740 DEBUG src/index.cc:308] Repository capabilities for "/home/marco/[...]": is_filemode_trustworthy = true, index_supports_symlinks = true, index_is_case_sensitive = true, precompose_unicode = false
[2019-07-08 12:08:29 00007f6bc7070700 DEBUG src/repo.cc:297] git_diff_tree_to_index from "" to ""
[2019-07-08 12:08:29 00007f6bc686f700 DEBUG src/index.cc:158] Dirty candidate (new): ".eggs/"
[...]
[2019-07-08 12:08:29 00007f6bc686f700 DEBUG src/index.cc:158] Dirty candidate (new): "venv/"
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/repo.cc:174] Found 10 dirty candidate(s) spanning from ".eggs/" to "venv/"
[2019-07-08 12:08:29 00007f6bc606e700 DEBUG src/repo.cc:253] git_diff_index_to_workdir from ".eggs/" to "venv/"
[2019-07-08 12:08:29 00007f6bc606e700 INFO src/repo.cc:205] Found untracked file: "foo"
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/response.cc:69] Replying with git status
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/timer.cc:67] Timing for: request: 2.623ms cpu, 2.18439ms wall
[2019-07-08 12:08:29 00007f6bc8073740 INFO src/gitstatus.cc:174] Successfully processed request: "1562580509.7826769352 " for "/home/marco/[...]"
```

**Comment by romkatv** [comment] 2019-07-08 10:24
Cannot reproduce :-/ It probably depends on your `POWERLEVEL9K` configuration. Could you post all your config options?

**Comment by romkatv** [comment] 2019-07-08 10:26
Never mind, reproduced it! Debugging now.

**Comment by mmariani** [comment] 2019-07-08 10:26
Good! I was going to say I have a default configuration.

**Comment by romkatv** [comment] 2019-07-08 10:33
Should be fixed now. Please update powerlevel10k and try again. Many thanks for helping with tracking this bug down!

**Closed** 2019-07-08 10:33 UTC

**Comment by mmariani** [comment] 2019-07-08 11:21
I can confirm. Thanks for the good work!
