### ISSUE TITLE
gitstatus_start_impl:echo:46: write error: invalid argument

### ISSUE THREAD

**Issue by jimcornmell** [romkatv/powerlevel10k#63] opened 2019-04-30 12:57 UTC
I'm using pl10k on WSL with Pengwin and get the following error:

`gitstatus_start_impl:echo:46: write error: invalid argument`

This equates to line 284 of `gitstatus.plugin.zshin gitstatus`.  You can mask the error by redirecting line 297 to `/dev/null` and all seems to still work fine, but this is nasty!

This error does not appear on WSL with Ubuntu, so it must be a slight issue with Pengwin:

`
$ uname -a
Linux 7LYLVP2 4.4.0-17763-Microsoft #379-Microsoft Wed Mar 06 19:16:00 PST 2019 x86_64 GNU/Linux
`

**Comment by romkatv** [comment] 2019-04-30 13:10
Wow, this is weird.

If I understand correctly, apart from the error message everything seems to work (that is, you aren't getting "gitstatus failed to initialize" on zsh startup). Given that this code runs with `err_return` option enabled, the `echo` command on line 284 must have succeeded despite complaining about `invalid argument`. You can try adding `false` before or after that `echo` to see that errors indeed will lead to "gitstatus failed to initialize".

I'll try to reproduce this and post an update here.

P.S.

Thanks for reporting this issue!

**Comment by jimcornmell** [comment] 2019-04-30 13:36
hi Romkatv,

Wow fast response!  Impressive.

I've changed line 284 from:

`echo -nE $'hello\x1f\x1e' >&$req_fd`

to

`false || echo -nE $'hello\x1f\x1e' >&$req_fd`

with no change.

And yes you are right everything seems to still work fine, just the error on startup.

Jim

**Comment by romkatv** [comment] 2019-04-30 13:43
> `false || echo -nE $'hello\x1f\x1e' >&$req_fd`

Of course. If `echo` succeeds, as I expect, then it's essentially `false || true`, which is `true`.

My point is that you can be sure that `echo` succeeds by adding `false` on the previous line.

```zsh
false
echo -nE $'hello\x1f\x1e' >&$req_fd
```

If you do that, you'll see  "gitstatus failed to initialize". Alternatively, you can do this:

```zsh
echo -nE $'hello\x1f\x1e' >&$req_fd && echo "pengwin is weird" >&2
```

You should see "pengwin is weird".

On a more depressing note, I've just wasted half an hour trying to spend $10 on Microsoft Store to buy Pengwin. Microsoft keeps insisting that I specify an address in United States when my default billing address and shipping address is set to Switzerland. How are they still in business?

I gave up and am now trying to build Pengwin from source. The instructions are the worst I've dealt with in a long time but I'm hopeful.

**Comment by jimcornmell** [comment] 2019-04-30 14:23
Oh gotcha.

```bash
false
echo -nE $'hello\x1f\x1e' >&$req_fd
```

Gives just "gitstatus failed to initialize" from line 305 and then the normal prompt all seems fine after that.

Option 2 does not print "pengwin is weird".  It behaves as before and you get the error and  "gitstatus failed to initialize".

**Comment by romkatv** [comment] 2019-05-01 10:03
After jumping through quite a few hoops I managed to get Pengwin working on WSL. Unfortunately, the error you are seeing doesn't show up. Here's what I did.

1. Install Ubuntu on WSL. Start it and create a new user.
2. Execute the following commands:

```zsh
sudo apt update -y
sudo apt upgrade -y
sudo apt install -y git

git clone https://github.com/WhitewaterFoundry/Pengwin.git
cd Pengwin
./create-targz-x64.sh
cd x64
sudo chown root:root .
sudo tar xf install.tar.gz
env -i sudo chroot .

su
cd

export LANG=C.UTF-8
export LC_ALL=C.UTF-8
export TERM=xterm-256color
 
apt update -y
apt upgrade -y
apt install -y git curl zsh gawk

git clone https://github.com/romkatv/powerlevel10k.git
curl -fsSLO https://raw.githubusercontent.com/romkatv/dotfiles-public/master/.purepower
echo 'source ~/.purepower' >> ~/.zshrc
echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >> ~/.zshrc

exec zsh
```

This gave me the expected Pure Power prompt with no errors.

Note that I haven't built or installed the Windows-specific parts of Pengwin. It's possible that these parts are the culprit of the error but it's not very likely. (I haven't installed them because the build instructions are awful. I gave up after half an hour.)

There is probably something in your setup that doesn't exist in mine. Let's try to figure out what it is. Please do the following:

1. Update Powerlevel10k.
2. Run this command:

```zsh
GITSTATUS_ENABLE_XTRACE=1 GITSTATUS_ENABLE_LOGGING=1 zsh -is <<<'cat $GITSTATUS_DAEMON_LOG_POWERLEVEL9K' &>/tmp/log
```

3. Post the content of `/tmp/log`.
4. Post the output of `echo $ZSH_VERSION`.

**Comment by jimcornmell** [comment] 2019-05-01 11:26
I ran the following (to remove my workaround and start affresh):

```bash
$ cd .oh-my-zsh/custom/themes/
$ rm -rf powerlevel10k
$ git clone https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k
$ GITSTATUS_ENABLE_XTRACE=1 GITSTATUS_ENABLE_LOGGING=1 zsh -is <<<'cat $GITSTATUS_DAEMON_LOG_POWERLEVEL9K' &>/tmp/log
$ echo $ZSH_VERSION
5.7.1
```
Log attached here: [log.txt](https://github.com/romkatv/powerlevel10k/files/3134350/log.txt)

Here is the error:

```bash
$ zsh
gitstatus_start_impl:echo:46: write error: invalid argument
gitstatus failed to initialize
$
```

I have installed all sort of things on Pengwin (usual apt install ...) but apart from that it's not been fiddled with.  I have an WSL-Ubuntu install which is the same (with no zsh errors).  So it looks to me to be something weird with Pengwin, as you suggest.

BTW I have a workaround so its no biggy (plus its someone else's problem), but am happy to help if you wish to dig deeper.

**Comment by romkatv** [comment] 2019-05-01 11:43
Thanks, this narrows the problem down a little bit. Please do a couple more things.

1. See if this reproduces in a clean zsh instance. Run the following command:

```zsh
zsh -dfis <<END
source $ZSH_CUSTOM/themes/powerlevel10k/powerlevel10k.zsh-theme
END
```

Does it print the same error?

2. Run `type echo`. What does it say?

**Comment by jimcornmell** [comment] 2019-05-01 12:24
```bash
$ zsh -dfis <<END
source $ZSH_CUSTOM/themes/powerlevel10k/powerlevel10k.zsh-theme
END

gitstatus_start_impl:echo:46: write error: invalid argument
gitstatus failed to initialize

$ type echo
echo is a shell builtin
```

**Comment by romkatv** [comment] 2019-05-01 12:36
Thanks for running the tests.

To summarize:

- gitstatus works for me when I `chroot` into Pengwin from Ubuntu distro on WSL.
- gitstatus doesn't work in a clean `zsh` on your system.

There are two tests in between that could be tried.

1. I install Pengwin the same way you did it instead of building from source. As I mentioned earlier, Microsoft Store won't let me buy Pengwin. I've spent half an hour trying to pay the $10 with no success and I'd rather not waste more of my time on it.
2. You install a clean Pengwin distro from Microsoft Store and then try Powerlevel10k with no extra software except for the absolutely necessary. That is, run the following commands from a clean Pengwin distro:

```zsh
sudo apt update -y && sudo apt upgrade -y && sudo apt install -y git zsh gawk

git clone https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >> ~/.zshrc

zsh
```

Is (2) something you can try or is it too much?

**Comment by jimcornmell** [comment] 2019-05-01 12:44
I'll dust off an old machine tonight and try 2.  Watch this space....

**Comment by jimcornmell** [comment] 2019-05-01 21:19
OK Works fine in a clean install.

So I've then used my .zshrc with the plugins I use and the issue came back.  I then repeated this on WSL+Ubuntu and the issue went away.

So it looks like a combination of my use of zsh+oh-my-zsh etc on Pengwin.

So I will perform a "binary-chop" on my setup of oh-my-zsh+et al until I can make the issue come and go.  I'll then post my results here once I've narrowed it down.

Sorry to waste your time, but if it does appear to be some weird combination I'll post that here to help others.

**Comment by romkatv** [comment] 2019-05-01 21:22
> So I will perform a "binary-chop" on my setup of oh-my-zsh+et al until I can make the issue come and go. I'll then post my results here once I've narrowed it down.

Sounds good. Thanks for digging into it!

**Comment by jimcornmell** [comment] 2019-05-04 16:40
So this is weird..... I've attached my .zshrc with a commented out line 8.

So with this defined I get the error on Pengwin:
```bach
export TMPDIR=/mnt/c/tmp
```
With it commented/removed, no error.

Am I making a schoolboy error by forcing all my tmp folders to one location for windows 10 and wsl?  I'm just trying to ease cleanup/maintenance, but maybe this is just a bad idea.

[zshrc.txt](https://github.com/romkatv/powerlevel10k/files/3144577/zshrc.txt)

**Comment by romkatv** [comment] 2019-05-05 09:42
> export TMPDIR=/mnt/c/tmp

The fact that you are getting an error makes sense although the actual error doesn't.

`/mnt/c` is a limited filesystem. Depending on how it was mounted, it may or may not support ownership or permissions. Crucially, it may not support special files such as fifos. These limitations make it an unwise choice for a temporary directory.

When I run `TMPDIR=/mnt/c/tmp zsh` in Ubuntu distro on WSL, I get the following error:

```
mkfifo: cannot create fifo '/mnt/c/tmp/gitstatus.27367.pipe.req.VzAQncfdCY': Operation not permitted
[ERROR]: gitstatus failed to initialize.
```

This is as expected. I'm getting the same error from `mkfifo /mnt/c/tmp/fifo`. However, there are different ways to mount drvfs, and some of them should allow you to create fifos. If gitstatus initializes successfully on your Ubuntu distro with `TMPDIR=/mnt/c/tmp`, it means you are using non-default mounting options (and perhaps the insider build). Pengwin is using some other options, which results in inadequate filesystem behavior.

You can test filesystem support for fifos with the following code:

```zsh
f=/tmp/fifo; mkfifo $f && exec {fd}<>$f && echo success >&$fd && head -c 8 <&$fd
```

If this fails with `cannot create fifo` when trying to create a fifo on drvfs, this is normal (that's what I get on Ubuntu distro with default settings). If it fails with `write error` on Pengwin, I suggest filing a bug against Pengwin.

On a more practical level, it's best to not set `TMPDIR` or set it to `/tmp` if you really must set it. This will let all temporary files go on the posix-compliant rootfs.

**Comment by romkatv** [comment] 2019-05-08 10:58
Closing this issue. I believe powerlevel10k behaves as expected. It uses `/mnt/c/tmp` to store temporary files as instructed, and fails to initialize gitstatus due to the limitations of this filesystem. The solution is not set `TMPDIR` or set it to a directory on a POSIX-compliant filesystem.

**Closed by romkatv** 2019-05-08 10:58 UTC

**Comment by jimcornmell** [comment] 2019-05-08 17:49
Many thanks for your help.  Its working fine, issue was not a Powerline10k issue.
